### ISSUE TITLE
Add core API for password authentication

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#100]
BothcqlshandJDBC(SQL) clients ask for username/password on the client side, but there's no authentication API defined in Stargate core that allows validating passwords (without creating tokens).

It would be nice to add an API specifically for validating username/password combinations.

**Comment by tatu-at-datastax** [comment]
Would need to be rethought if this is needed, or something similar, how and so on. Closing this issue since there are no current on-going plans.
