### ISSUE TITLE
Create common backing services for REST v1 and v2

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#101]
Much of the logic between v1 and v2 of the REST API is shared so rather than duplicating in each resource we should instead create common objects for them to interact with. For example, rather than duplicating the same code in io.stargate.web.resources.v2.schemas.ColumnsResource and io.stargate.web.resources.ColumnResource instead create a SchemaService (or something to that effect) that will allow for interacting with persistence and returning the relevant values

**Comment by tatu-at-datastax** [comment]
Plan is to eventually deprecate V1, but until then it will only be supported by Stargate V1 (embedded in Coordinator) whereas new REST V2 is supported by Stargate V2 (separate, stand-alone REST service).
So no unification planned, rather deprecated.
