### ISSUE TITLE
Primary key field in Swagger for v2 REST GET operations does not appear

### ISSUE THREAD

**Issue by jdavies** [stargate/stargate#1011]
When using the Swagger API to test a v2 REST GET. query, the required primary key field does not appear and therefore I cannot test the API through swagger.
![](https://user-images.githubusercontent.com/297151/121746748-301f8800-cabb-11eb-9c91-d989c22b1332.png)
EDIT - Ignore this. The field shows up when you press the "Try It Out" button. The UI still seems misleading though. he other fields are not editable before you press the Try It Out button, but they are still visible. I suggest that the primary key fields also be visible, but disabled.

**Comment by dougwettlaufer** [comment]
This is an artifact of how swagger renders its UI and not something we have control over.
