### ISSUE TITLE
GraphQL schema-first: fix type checks for conditions

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1013]
`ConditionModelBuilder.checkArgumentIsListOf` uses `isEqualTo` to compare the expected and actual types. This will always succeed if both types are lists, because it doesn't recurse into subtypes. We need to compare the element types instead.

`ConditionModelBuilder.checkArgumentIsSameAs` might be subject to the same issue.

**Comment by tomekl007** [comment]
I don't see a problem with `checkArgumentIsSameAs`. I think it does not need to check recursive types.

**Comment by olim7t** [comment]
> I don't see a problem with `checkArgumentIsSameAs`. I think it does not need to check recursive types.

See [this test](https://github.com/stargate/stargate/blob/gql-conditions-type-checks/testing/src/main/java/io/stargate/it/http/graphql/graphqlfirst/SelectInvalidConditionsTest.java#L96-L123).
