### ISSUE TITLE
Stargate doesn't pull large schema correctly from Cassandra nodes

### ISSUE THREAD

**Issue by marksurnin** [stargate/stargate#1017]
Creating this issue to track two problems [discussed](https://discord.com/channels/745831180213158001/766642967976476672/851856938215931964) in #graphqlapi on Discord. These problems happen in a multi-region cluster with around 40 nodes. The schema has ~50 keyspaces and ~130 tables; its total size is 150KB. The cluster is running OSS Cassandra 3.11.3.

1. Sometimes Stargate fails to pull the schema from C* nodes. I see many 
`WARN  [MigrationStage:1] 2021-06-03 16:40:19,623 MigrationTask.java:67 - Can't send schema pull request: node /10.100.10.100 is down.` This is logged in [MigrationTask.java#L67](https://sourcegraph.com/github.com/apache/cassandra@cassandra-3.11.3/-/blob/src/java/org/apache/cassandra/service/MigrationTask.java?subtree=true#L67). According to the code, C* nodes are marked as down by FailureDetector (`nodetool failuredetector` reports Phi values much smaller than `phi_convict_threshold`).

Increasing `cassandra.migration_task_wait_in_seconds`,`stargate.schema_sync_grace_period_ms`, and `stargate.startup_delay_ms` didn't help. I ended up doubling `request_timeout_in_ms` in cassandra.yaml to 20000, which resulted in almost the entire schema being pulled (only the `cdc` table params were missing, as described in the next problem).

1. The schema has tables with `cdc=true` and this table param isn't always included in the table schemas on Stargate nodes. This leads to a schema disagreement and SG nodes not passing their readiness check.
My initial guess was that this is caused by [CASSANDRA-12697](https://issues.apache.org/jira/browse/CASSANDRA-12697) (relevant [commit](https://github.com/apache/cassandra/commit/57e9a83b2abf08d7a1261e8f7a9f435d221a1f81#diff-44546e8ca2f2a8a986ec2b16f837b7526f2444e5fb2c6367abf35d8756fd0e51R386-R399)). Setting cdc_enabled: true in cassandra.yaml should ensure that cdc param ends up in the schema, but that might actually enable CDC on Stargate nodes.

Notes:

* We've discussed fixing the Stargate-specific problem with `nodetool resetlocalschema` to have a mechanism to force a schema update since the schema migration task isn't retried. However, subsequent schema migration tasks might time out as well with the original `request_timeout_in_ms` value.
* I was wondering whether pulling the schema from C* nodes in the local DC would be sufficient, provided that the C* schema is in agreement.

**Comment by dimas-b** [comment]
> Setting cdc_enabled: true in cassandra.yaml should ensure that cdc param ends up in the schema, but that might actually enable CDC on Stargate nodes

Interesting :thinking: I suppose enabling CDC in cassandra.yaml on Stargate nodes should not be harmful because Stargate does not actually write much data to commit log or SSTables locally. I believe it might write some data to unreplicated (system) tables, but the amount of that data is minimal. Plus actuall CDC files should not be produced because per-table CDC flags are likely not set for this tables.

That said, we should probably double check CDC use cases :)

**Comment by marksurnin** [comment]
Hi @dimas-b you're right, enabling CDC in cassandra.yaml is not harmful but it doesn't lead to the cdc table param being included in the schema.

We have a multi-DC cluster and nodes in 1 DC have cdc enabled. I noticed that when I add a Stargate instance to that DC, Stargate receives the schema _with_ cdc table params.

### Steps to reproduce
I found a way to reproduce this locally by starting a 2 node (later, nodes A and B) cluster with `ccm create stargate -v 3.11.6 -n 2 -s -b`. I set `cdc_enabled: true` in node B's cassandra.yaml and restarted it to take effect. I then created a keyspace with RF=2 and created 2 tables (any columns, just make sure to set `cdc='true'`). I created one table on node A and the other on the node B. At this point, running `desc schema` showed that _the cdc table param only shows up in the table that was created on node B where CDC is enabled_, which is odd.
This is likely due to [SchemaKeyspace.java:L430](https://sourcegraph.com/github.com/apache/cassandra@cassandra-3.11.6/-/blob/src/java/org/apache/cassandra/schema/SchemaKeyspace.java?L430&subtree=true) skipping the cdc table param if the node has cdc disabled.

Then I launched Stargate and saw that `nodetool describecluster` showed one schema version, which means that the cdc table param was in Stargate's schema. I then stopped Stargate and node B (where cdc is enabled) and restarted Stargate. `nodetool describecluster` showed 2 schema versions and the cdc table param was missing in both tables in Stargate's schema.

### Takeaways
I believe this happens because newer mutations override old ones in [MigrationTask.java:L91](https://sourcegraph.com/github.com/apache/cassandra@cassandra-3.11.6/-/blob/src/java/org/apache/cassandra/service/MigrationTask.java?L91&subtree=true#L80:69). I've shared relevant logs and the call stack in https://gist.github.com/marksurnin/01e174621c5ac39f105eaff28f707b68. I'm not sure we can control the order in which schema mutations are merged. As I understand, they are applied in the order they are received.

What are your thoughts about this? The schema version is the same in C* nodes but nodes that don't have cdc enabled don't include the cdc table params when they share their schema.

**Comment by dimas-b** [comment]
@marksurnin : Thanks for the update! I started investigating this in more depth from our side.

Meanwhile I noticed that schema handling has been refactored in 3.11.10 and 4.0-beta4. The `MigrationTask` class has been deleted and `MigrationCoordinator` added. I'm not sure if this refactoring helps in this particular case, though... Just FYI.

**Comment by dimas-b** [comment]
It looks like the handling of CDC flags is not 100% robust even in plain C*. Here's my test case with 3.11.8:

1. Create and start a two node cluster with `ccm`: `ccm create stargate -v 3.11.8 -n 2 -s -b`
2. Set cdc flags: `ccm updateconf 'cdc_enabled: true'`
3. Restart node1
4. Now node1 runs with CDC _enabled_, while node2 runs with CDC disabled
5. Create table X in node2, table Y in node1 (table structure or per-table CDC flags are irrelevant)
6. The cluster is in schema agreement at this point because each node sends its version of the schema to the other node
7. Stop node1
8. Add node3 to the cluster
9. Now node3 runs with CDC _enabled_, while node2 runs with CDC disabled
10. Schema is in disagreement now:
```
Cluster Information:
	Name: stargate
	Snitch: org.apache.cassandra.locator.SimpleSnitch
	DynamicEndPointSnitch: enabled
	Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
	Schema versions:
		5e48875b-eb12-30e4-88fe-dfdeaa8f7c50: [127.0.0.2]

		f25cef0c-77ae-338f-868b-6c3c9d73a2c1: [127.0.0.3]

		UNREACHABLE: [127.0.0.1]
```

As far as I can tell this happens because when node2 sends schema information to node3 it _excludes_ CDC table options and they end up being `null` on node3, while they are set to some value for table Y on node2:
```
 $ ./cqlsh 127.0.0.2
Connected to stargate at 127.0.0.2:9042.
[cqlsh 6.8.0 | Cassandra 3.11.8 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> select * from system_schema.tables where keyspace_name = 'test1';

 keyspace_name | table_name | bloom_filter_fp_chance | caching                                       | cdc   | comment | compaction                                                                                                                | compression                                                                             | crc_check_chance | dclocal_read_repair_chance | default_time_to_live | extensions | flags        | gc_grace_seconds | id                                   | max_index_interval | memtable_flush_period_in_ms | min_index_interval | read_repair_chance | speculative_retry
---------------+------------+------------------------+-----------------------------------------------+-------+---------+---------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+------------------+----------------------------+----------------------+------------+--------------+------------------+--------------------------------------+--------------------+-----------------------------+--------------------+--------------------+-------------------
         test1 |          x |                   0.01 | {'keys': 'ALL', 'rows_per_partition': 'NONE'} |  null |         | {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'} | {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'} |                1 |                        0.1 |                    0 |           {} | {'compound'} |           864000 | e24453e0-e4be-11eb-a7eb-8f94be225fa1 |               2048 |                           0 |                128 |                  0 |      99PERCENTILE
         test1 |          y |                   0.01 | {'keys': 'ALL', 'rows_per_partition': 'NONE'} | False |         | {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'} | {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'} |                1 |                        0.1 |                    0 |           {} | {'compound'} |           864000 | f9067040-e4be-11eb-ac21-719258a37c46 |               2048 |                           0 |                128 |                  0 |      99PERCENTILE

(2 rows)
```

```
$ ./cqlsh 127.0.0.3
Connected to stargate at 127.0.0.3:9042.
[cqlsh 6.8.0 | Cassandra 3.11.8 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> select * from system_schema.tables where keyspace_name = 'test1';

 keyspace_name | table_name | bloom_filter_fp_chance | caching                                       | cdc  | comment | compaction                                                                                                                | compression                                                                             | crc_check_chance | dclocal_read_repair_chance | default_time_to_live | extensions | flags        | gc_grace_seconds | id                                   | max_index_interval | memtable_flush_period_in_ms | min_index_interval | read_repair_chance | speculative_retry
---------------+------------+------------------------+-----------------------------------------------+------+---------+---------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------+------------------+----------------------------+----------------------+------------+--------------+------------------+--------------------------------------+--------------------+-----------------------------+--------------------+--------------------+-------------------
         test1 |          x |                   0.01 | {'keys': 'ALL', 'rows_per_partition': 'NONE'} | null |         | {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'} | {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'} |                1 |                        0.1 |                    0 |           {} | {'compound'} |           864000 | e24453e0-e4be-11eb-a7eb-8f94be225fa1 |               2048 |                           0 |                128 |                  0 |      99PERCENTILE
         test1 |          y |                   0.01 | {'keys': 'ALL', 'rows_per_partition': 'NONE'} | null |         | {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'} | {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'} |                1 |                        0.1 |                    0 |           {} | {'compound'} |           864000 | f9067040-e4be-11eb-ac21-719258a37c46 |               2048 |                           0 |                128 |                  0 |      99PERCENTILE

(2 rows)
```

Note: the non-null CDC option values for table Y on node2 were received from node1 while it was running.

**Comment by dimas-b** [comment]
@marksurnin : If I understand correctly, in your env. CDC is disable and enabled is different DCs, right? I'd guess the above schema disagreement scenario might be possible in your env. even without Stargate. Did you hit anything like that before?

**Comment by dimas-b** [comment]
@marksurnin : I suppose it may be possible for Stargate to poll C* storage nodes for schema data from its own code, then collect schema mutations and apply those the have data for the CDC column. This should ensure that we receive CDC options from nodes that have CDC enabled.

However, it feels a bit too hacky to me. I think it would be preferable to address this problem in C* code, if it is feasible. WDYT?

**Comment by marksurnin** [comment]
Thanks for the detailed comments, @dimas-b!

> As far as I can tell this happens because when node2 sends schema information to node3 it excludes CDC table options and they end up being null on node3, while they are set to some value for table Y on node2:

Yes. I verified that this happens on 3.11.10 and 4.0 as well (I see this logic in 4.0 [source code](https://sourcegraph.com/github.com/apache/cassandra@cassandra-4.0/-/blob/src/java/org/apache/cassandra/schema/SchemaKeyspace.java?L434&subtree=true)).

> If I understand correctly, in your env. CDC is disabled and enabled is different DCs, right? I'd guess the above schema disagreement scenario might be possible in your env. when new nodes are added even without Stargate. Did you hit anything like that before?

Yes, we have a DC with cdc enabled that's only used for change data capture. Since it doesn't receive any traffic directly (only through replication), we haven't had to change the number of nodes in a while. I agree with you that based on what we've observed, the schema issue can happen just with C* nodes. I'll try it out and get back to you.

> However, it feels a bit too hacky to me. I think it would be preferable to address this problem in C* code, if it is feasible. WDYT?

My answer will depend on whether the issue is reproducible when increasing the number of C* nodes in a DC where nodes have CDC enabled. Fixing it in C* sounds more appropriate but I understand it may be tricky. The comment in [SchemaKeyspace.java](https://sourcegraph.com/github.com/apache/cassandra@cassandra-4.0/-/blob/src/java/org/apache/cassandra/schema/SchemaKeyspace.java?L435-436&subtree=true) mentions 2 issues which are related to upgrading the cluster to 3.8 because the `cdc` table param was new then. I don't think that upgrading from 3.11.* to 4.* requires this logic as the cdc table param is not new, but I might be wrong.

Regarding your last point: this is not a blocker for us. We worked around the issue by adding a periodic schema agreement check just for the storage nodes and removing the `schema-agreement` readiness check from Stargate. It isn't a perfect solution but it covers the majority of problems we might encounter.

**Comment by marksurnin** [comment]
> If I understand correctly, in your env. CDC is disabled and enabled is different DCs, right? I'd guess the above schema disagreement scenario might be possible in your env. when new nodes are added even without Stargate. Did you hit anything like that before?
I added C* nodes in both datacenters (cdc is enabled in one DC and disabled in the other DC) and they received the full schema in both cases. Then I removed all nodes from the DC where cdc is enabled and added one node back, it did not receive the CDC table param in the schema as I expected.

**Comment by dimas-b** [comment]
Thanks for the update @marksurnin !

Looking at C* code I get the impression that a lot of the logic around sending or not sending CDC flags was added to support older C* versions during rolling upgrades. Now that all node are likely running a version of C* that can deal with CDC flags (I assume), excluding them when CDC is not enabled may no longer be necessary. I imagine it may be possible to add `-D` setting to C* code to make it always send CDC flags in schema change events, regardless of the `cdc_enabled` flag. This way all nodes will have `true` or `false` CDC flags in the schema table as opposed to `true` or `null`. WDYT?

**Comment by marksurnin** [comment]
Sounds good to me!
