### ISSUE TITLE
GraphQL endpoints are slowed down by reading system_auth.roles

### ISSUE THREAD

**Issue by tub** [stargate/stargate#1021]
I spent some time this evening trying to debug some performance issues we've been seeing with the /graphql/{keyspace} 
The throughput on the `system_auth.roles table` was 2-3x the GraphQL throughput.

I managed to breakpoint where this was happening on `master`@`578c6936`:

```
getRoleFromTable:542, CassandraRoleManager (org.apache.cassandra.auth)
getRole:522, CassandraRoleManager (org.apache.cassandra.auth)
canLogin:322, CassandraRoleManager (org.apache.cassandra.auth)
canLogin:292, ClientState (org.apache.cassandra.service)
login:282, ClientState (org.apache.cassandra.service)
loginInternally:437, CassandraPersistence$CassandraConnection (io.stargate.db.cassandra.impl)
login:144, AbstractCassandraPersistence$AbstractConnection (io.stargate.db.datastore.common)
create:58, PersistenceDataStoreFactory (io.stargate.db.datastore)
create:84, PersistenceDataStoreFactory (io.stargate.db.datastore)
buildUserDatastore:149, GraphqlCache (io.stargate.graphql.web.resources)
getDml:97, GraphqlCache (io.stargate.graphql.web.resources)
getGraphql:169, DmlResource (io.stargate.graphql.web.resources)
postJson:117, DmlResource (io.stargate.graphql.web.resources)
[snipped servlet stack]
```

This is called three times for a single curl, for example:

```
curl 'http://localhost:8080/graphql/system' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:8080' -H 'x-cassandra-token: $TOKEN' --data-binary '{"query":"# Write your query or mutation here\n{\n  batches{\n    values{\n      version\n      mutations\n    }\n  }\n  paxos{\n    values{\n      row_key\n    }\n  }\n\n  \n}"}' --compressed
```

And four times for this curl:

```
curl 'http://localhost:8080/graphql/system' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:8080' -H 'x-cassandra-token: $TOKEN' --data-binary '{"query":"# Write your query or mutation here\n{\n  IndexInfo {\n    values{\n      table_name\n    }\n  }\n  peers{\n    values{\n      data_center\n    }\n  }\n  prepared_statements{\n    values{\n      query_string\n    }\n  }\n  \n}"}' --compressed
```

It looks like login is being called & not cached for every single select in each data fetcher.

**Comment by dimas-b** [comment]
@tub : this is very strange. From the stack trace it looks like the user should be "anonymous", but the anonymous user should be able to login without the `canLogin` check.

Since you have a debuggable env. already, could you verify why the `user.isAnonymous()` check does not short-circuit in C* `ClientState` (line 282)?
```
    public void login(AuthenticatedUser user) throws AuthenticationException
    {
        // Login privilege is not inherited via granted roles, so just
        // verify that the role with the credentials that were actually
        // supplied has it
        if (user.isAnonymous() || canLogin(user))
            this.user = user;
        else
            throw new AuthenticationException(String.format("%s is not permitted to log in", user.getName()));
    }
```

**Comment by dimas-b** [comment]
Sorry, my mistake. I guess the user comes from `AuthnTableBasedService` in Stargate, so it would not be considered "anonymous".

**Comment by dimas-b** [comment]
From my POV there are two separate problems here:

1. GraphQL API performs login more than once per HTTP request

We have to login each user at least once into `ClientState`. I'm not sure how feasible it is to share the same `ClientState` across all GraphQL fetchers (we can certainly investigate this deeper), but in the best case one login will still have to happen.

2. Role data is reloaded from `system_auth.roles` on every Stargate-level login

As for role caching, this is C* OSS code and we do not really control it at SG level. However, Stargate supports the notion of "external" users. Those users are validated by Stargate itself and runs as an "anonymous" superuser at C* storage level.

If this is something of interest for your use case, @tub , then there is another fork here:

2a: Make a custom `AuthenticationService`, mark validated users as `isFromExternalAuth` and add `-Dstargate.cql_use_transitional_auth=true` to Stargate system properties.

2b: It should be possible to update `AuthnTableBasedService` to respect `-Dstargate.cql_use_transitional_auth=true` or use some other property for producing "external" users. In this case it might be worth opening a separate issuet to track this work.

**Comment by tub** [comment]
We could work around this with an 'external' user for now, but we're really hoping to use role-based auth at the cassandra level with stargate at some point in the future.

I'll look into the external user option now, thanks for the pointers @dimas-b!

**Comment by dougwettlaufer** [comment]
> Role data is reloaded from system_auth.roles on every Stargate-level login

@dimas-b isn't role/permission data cached in persistence? Or is that only in the actual storage node?

**Comment by dougwettlaufer** [comment]
> GraphQL API performs login more than once per HTTP request

@olim7t is there anything we can do here?

**Comment by tub** [comment]
> 2a: Make a custom `AuthenticationService`, mark validated users as `isFromExternalAuth` and add `-Dstargate.cql_use_transitional_auth=true` to Stargate system properties.

@dimas-b Just confirmed that this workaround does indeed stop the system_auth.roles calls! I'll try rolling this out tomorrow & see if we get a performance boost.

**Comment by dimas-b** [comment]
> isn't role/permission data cached in persistence?

DSE caches roles, but C* 3.11 apparently does not.

The code in question (`login:282, ClientState (org.apache.cassandra.service)`) is not in Stargate persistence but in actual C* (or DSE) jars. So if we try to login a C* user (not "external") C* will do what it normally does on login.

**Comment by dimas-b** [comment]
>  we're really hoping to use role-based auth at the cassandra level with stargate at some point in the future.

It may be possible to implement another `AuthorizationService` that would delegate to C* roles, but with caching.

**Comment by olim7t** [comment]
> is there anything we can do here?

Yes. The repeated logins happen because each fetcher creates its own `DataStore` (see [CassandraFetcher.get()](https://github.com/stargate/stargate/blob/master/graphqlapi/src/main/java/io/stargate/graphql/schema/CassandraFetcher.java#L32-L40)), in order to customize certain execution parameters (CL, page size, etc). But there is actually a simpler way: `DataStore.execute(query, parametersModifier)` allows ad-hoc parameters _per query_, on a single datastore instance.

So we should be able to create a single `DataStore` at the beginning of the HTTP request, and reuse it. This is definitely an oversight and I'll start working on a fix.

Note however that the best we can achieve is one login per HTTP request. Caching can still yield better results if the eviction time spans multiple requests.
