### ISSUE TITLE
Document population and full search could be restricted to the field paths

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1024]
Currently when the documents are populated in the docs api, the query is fetching all the rows of that document. This could be improved if the user specifies the fields to be returned:

* fetching only the columns in needed max depth (max field depth + 1)
* limit the rows by actually setting shared pre-path between all rows

Example: If the user requests the fields `['a.b', 'a.c.d']`, the query should fetch only `p0 = a`, `p1 > ''` and make `p3 = ''`.

This also requires that `JsonConverter` supports population based on the requested max depth.

**Comment by jeffreyscarpenter** [comment]
Won't make enhancements like this to Docs API, will recommend moving to JSON API which supports projection
