### ISSUE TITLE
Query executor should record execution context on the execute method

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1025]
The `QueryExecutor` should add to the execution context when `execute` method is called. This will allow to call the execute and thus skip the `seed` process when it's actually not needed. Furthermore, this method is public and thus should expose the same behavior as the other public methods.

Once this is done, we could use it directly in the `CandidatesFilter` implemenations when we fetch one row only, as then we don't need seeding.

**Comment by jeffreyscarpenter** [comment]
Not pursuing improvements on Docs API since we are focusing on JSON API
