### ISSUE TITLE
Validating data store should compare against externalQueryString

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1026]
Currently the validating data store compares against the prepared query, which is wrong, because it should compare against the query defined by the user. The placeholder `?` should be used in the asserting query only for the values that are directly binded after the preparation.

**Comment by dimas-b** [comment]
@ivansenic : I poked around the related code a bit, but unfortunately, I did not see how using `Query.toString()` vs. `queryStringForPreparation` (current behaviour) is going to help with testing APIs that use the `QueryBuilder`.

Currently, queries constructed via the `QueryBuilderImpl` get their pre-set parameters automatically extracted into `?` placeholders. Essentially, at the `DataStore` level, those "known" parameters look the same as the parameters bound after query construction (i.e. by calling `Query.bindValues()`).

User-provided parameters are currently passed to `QueryBuilderImpl` methods at query construction time. Post-creation bind variables are not used, at least by Docs API code, which is the only module that validates constructed queries, AFAIK.

Did you mean this issue to drive the refactoring of the Docs API production and test code to actually use explicit bind markers?

**Comment by ivansenic** [comment]
So consider a situation where you build and bind a query in the following way:

```
dataStore.queryBuilder().
....
  .where(BuiltCondition.of("first", Predicate.EQ, "v1")
  .where("second", Predicate.EQ)
  .build()
  .bind("v2");
```

I would expect to write it like this in a test:

```
withQuery(
        TABLE,
        "SELECT .. WHERE first = 'v1' AND second = ?",
        "v2")
```

Right now it's possible only to do smth like:

```
withQuery(
        TABLE,
        "SELECT .. WHERE first = ? AND second = ?",
        "v2")
```

So matching `first = 'v1'` is impossible and thus missed.

**Comment by dimas-b** [comment]
@ivansenic : your example is great, but what I meant to say is that existing code that uses `ValidatingDataStore` does not use that kind of bind workflow. Currently all values are bound as `.where("second", Predicate.EQ, "v2")`... at least as far as I can tell.

**Comment by dimas-b** [comment]
> So matching first = 'v1' is impossible and thus missed.

It should be possible, unless there's a bug. You match it as:

```
withQuery(TABLE,  "SELECT .. WHERE first = ? AND second = ?", "v1", "v2")
```

Since all values are actually extracted from the CQL string by the `QueryBuilder`, there is little difference in runtime. The CQL string that has `first = 'v1'` is not actually used in runtime, IIRC, it is provided only for debugging, AFAIK.

**Comment by dimas-b** [comment]
To clarify my points: I think we _can_ support differentiating the `v1` and `v2` case in test code, but it's extra work and I'm not sure it is actually critical, given that the `QueryBuilder` automatically extracts bind variables and we do not build CQL strings "by hand". WDYT?

**Comment by ivansenic** [comment]
So `withQuery(TABLE,  "SELECT .. WHERE first = ? AND second = ?", "v1", "v2")` this is not working.. Only `v2` is recognized as binded value.. Maybe it s a bug..

It's not critical, but in my `AbstractSearchQueryBuilder` and sub-classes I am using prebuilt `BuiltCondition`s and I can not verify completely the CQL.

**Comment by dimas-b** [comment]
@ivansenic : Do you have a particular test code snippet that fails?
