### ISSUE TITLE
Document search service to support in document search

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1028]
The new reactive service should also support in document search. This would align the two search types to the same. Right now, there are some differences as the collection search provides some extra features and better performance.

Implementing this would allow us to remove a majority of code from the `DocumentService`.

**Comment by ivansenic** [comment]
After a small analysis I did today, I would like to summarize the needed requirements and approach we will take for refactoring the in-document search.

The main goal is that this search behaves in the same way as the full collection search, where we would consider all the key/value pairs of the prepend path of a single document as many documents you can search for. Example, having a document id `p1` and following payload:

```
{
   "name":"Samsung TV",
   "price":99.99,
   "currency":"USD",
   "tags":[
      "electronics",
      "tv",
      "samsung"
   ],
   "categories":[
      {
         "id":"c1",
         "name":"Electronics"
      },
      {
         "id":"c2",
         "name":"Sale"
      }
   ],
   "reviews":{
      "r1":{
         "status":"APPROVED",
         "rating":4.5,
         "text":"",
         "user":{
            "id":"u1",
            "fullName":"Ivan Senic"
         }
      },
      "r2":{
         "status":"PENDING",
         "rating":2,
         "text":"Don't buy",
         "user":{
            "id":"u2",
            "fullName":"Dmitri B."
         }
      }
   }
}
```

we could enable an easy way to search for all the reviews for this product. 

**Requirements**

* `prepend path` defines where to search for
    * valid example: `collections/products/p1/reviews`
    * globs are not supported, `collections/products/p1/*` or `collections/products/p1/[*]` is invalid and results in `400 Bad request`
    * paths ending in value nodes are not supported, `collections/products/p1/name` is invalid because there are no documents under this path, and results in empty response
    * array paths are support if the array elements are not value nodes:
        * `collections/products/p1/categories` is valid, the key for each document is array index in form `[0]`, `[1]`, etc
        *  `collections/products/p1/tags` is not valid, as the array elements are values, and results in empty response
    * array indexes are supported in the same way as array paths 
        * `collections/products/p1/categories/[1]` is valid, the key for the document is array index in form `[1]`
        *  `collections/products/p1/tags/[1]` is not valid, as the array elements are values, and results in empty response
* `fields` are relative to the prepend path, everything is supported (globs, etc)
     * `collections/products/p1/reviews?fields=["text"]`  should result in: `{ "r1":{"text": ""}, "r2": {"text":"Don't buy"}}`
     *  `collections/products/p1/categories?fields=["name"]`  should result in: `{ "[0]":{ "name":"Electronics"}, "[1]": { "name":"Sale"}}`
* `where` conditions are relative to the prepend path, everything is supported (globs, path segments, etc)
     * `collections/products/p1/reviews?where={"status": { "$eq": "PENDING" }}`  should result in: `{ "r2":{
         "status":"PENDING",
         "rating":2,
         "text":"Don't buy",
         "user":{
            "id":"u2",
            "fullName":"Dmitri B."
         }
      } }`
* mixing `fields` and `where` is supported without any limitations
     * `collections/products/p1/reviews?fields=["text", "user.fullName"]&where={"rating": "$gt": 2}`  should result in: `{ "r1":{
         "text":"",
         "user":{
            "fullName":"Ivan Senic"
         }
      } }`
* empty prepend path is valid, considers the document itself (users should not be encouraged to use this)

**Implementation details**

I would propose that for the implementation we go for the following approach:

1. Load all the rows that match prepend path and do represent a nested object
2. Group them by the prepend path key depth (path size + 1 for doc id), this will effectively split them into multiple documents that can be paginated on
3. Do a complete expression tree evaluation using the `EvalEngine` and return only the matching portion of the sub-documents

*Pros*
* one query only
* since we have doc id, query should be fast
* we would support paging without any problems
* we would support all operations out of the box, including `$or` and `$not`
* we would add a code that could be used for full collection search with the jump to `EvalEngine` (opens possibility)

*Cons*
* amount of fetch data can be rather high depending on the object sizes in the prepend path, however since this is a single document and we are hitting a single partition, this could be justified

**Comment by dimas-b** [comment]
+1 to paginating over nested elements under `prepend path`

> * collections/products/p1/categories is valid, the key for each document is array index in form [0], [1], etc
> * collections/products/p1/tags is not valid, as the array elements are values, and results in empty response

Why would be not allow the second case? Strings are valid JSON values and can be used anywhere a JSON object can be used.

> one query only

I do not think we have to limit the implementation to one query. With very large docs it may be reasonable to use the candidates/populate approach we have in global search. Also, with `ORs` in the picture we may no longer to able to distill a `where` clause to exactly one CQL query anyway.

**Comment by dimas-b** [comment]
closed by accident :facepalm:
