### ISSUE TITLE
Incorrect pageState when get subdocument (AstraDb)

### ISSUE THREAD

**Issue by semichkin** [stargate/stargate#1039]
I have a document
`{
        "careerStartDate": "2012-04-23T18:25:43.511Z",
        "certified": true,
        "description": "Мы уже более 5 лет занимаемся лидогенерацией и продажами в ВК.<br>Легко настроим таргетированную рекламу и возьмем вашу группу на комплексное ведение и продвижение.",
        "name": "Сергей Смирнов",
        "reviews": {
            "review1": {
                "authorName": "Артем",
                "comment": "Пользуюсь услугами этой компании уже около года. Группа растет, клиенты звонят. Ребята всегда на связи. Рекомендую к сотрудничеству.",
                "rating": 5,
                "status": "moderation"
            },
            "review2": {
                "authorName": "Артем",
                "comment": "Пользуюсь услугами этой компании уже около года. Группа растет, клиенты звонят. Ребята всегда на связи. Рекомендую к сотрудничеству.",
                "rating": 4,
                "status": "resolved"
            },
            "review3": {
                "authorName": "Артем",
                "comment": "Пользуюсь услугами этой компании уже около года. Группа растет, клиенты звонят. Ребята всегда на связи. Рекомендую к сотрудничеству.",
                "rating": 3,
                "status": "rejected"
            },
            "review4": {
                "authorName": "Артем",
                "comment": "Пользуюсь услугами этой компании уже около года. Группа растет, клиенты звонят. Ребята всегда на связи. Рекомендую к сотрудничеству.",
                "rating": 4,
                "status": "resolved"
            },
            "review5": {
                "authorName": "Артем",
                "comment": "Пользуюсь услугами этой компании уже около года. Группа растет, клиенты звонят. Ребята всегда на связи. Рекомендую к сотрудничеству.",
                "rating": 4,
                "status": "resolved"
            },
            "review6": {
                "authorName": "Артем",
                "comment": "Пользуюсь услугами этой компании уже около года. Группа растет, клиенты звонят. Ребята всегда на связи. Рекомендую к сотрудничеству.",
                "rating": 4,
                "status": "resolved"
            },
            "review7": {
                "authorName": "Артем",
                "comment": "Пользуюсь услугами этой компании уже около года. Группа растет, клиенты звонят. Ребята всегда на связи. Рекомендую к сотрудничеству.",
                "rating": 4,
                "status": "resolved"
            }
        },
        "serviceUsingStartDate": "2012-04-23T18:25:43.511Z",
        "services": [
            "Создание чат-ботов",
            "Консультирование",
            "Настройка таргета ВК"
        ],
        "specialty": "Основатель SMMZAVOD"
    }
`

When i try load "reviews" with pagination `.../path/to/reviews/*?where={...}&page-size=3`,
I get pageState `JGRlNDgxMjk3LTBiN2QtNDMwZi04ZWRmLTAyOWE5NjhjZThkZST/VVVVVVVVVUAHcmV2aWV3cwdyZXZpZXc1BnN0YXR1c+FVVVXwf/////B/////`

When i paste this page-state to next request, i gets response with error:
`{
    "description": "Server error: Illegal base64 character 20",
    "code": 500
}`

**Comment by dougwettlaufer** [comment]
Hi @semichkin, this probably needs to be url encoded. We need to either update the swagger to mention this or possibly return pre-encoded.

**Comment by dimas-b** [comment]
I believe it's a bug on our side. We permitted paging state strings to contain `+` which got reinterpreted when passed back as a query parameter - #1041

**Comment by dimas-b** [comment]
The same problem occur with `curl`

**Comment by dimas-b** [comment]
@semichkin : please note that it may take a week or so before the fix is available in Astra.
