### ISSUE TITLE
Remove transitional base64 parameter decoding code

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#1044]
#1041 introduced some logic in decoding base64 parameters that is required only for supporting rolling upgrade scenarios.

This logic can be removed after the backward-compatible code has been released.

Users affected by this issue may need to upgrade through Stargate 1.0.28 to 1.0.29 and then to the latest.

**Comment by dimas-b** [comment]
@marksurnin : FYI

**Comment by jeffreyscarpenter** [comment]
no longer relevant.
