### ISSUE TITLE
Using "fields" without "where"

### ISSUE THREAD

**Issue by semichkin** [stargate/stargate#1046]
I want to get certain fields from a document. To do this, I send next request:
`/collections/mycollection/de481297-0b7d-430f-8edf-029a968ce8de?fields=["field1", "field2"]`. But i am getting an error response:
`{
    "description": "Selecting fields is not allowed without `where`.",
    "code": 400
}`

**Comment by dimas-b** [comment]
This may be covered by the work to fix #1040 (WIP...)
