### ISSUE TITLE
Include schema agreement into readiness probe

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#1051]
Currently Stargate validates whether it can use storage as part of the "readiness" probe.

However, schema may or may not be in agreement at that time. Using Stargate for queries when it is not in schema agreement with storage is likely to lead to runtime errors (e.g. missing tables, missing columns).

Stargate should validate whether it is in schema agreement with storage during the "readiness" probe. Note: validating schema agreement with other Stargate nodes is not necessary for this purpose.

Related issues: #934, #1017

**Comment by jeffreyscarpenter** [comment]
Won't do
