### ISSUE TITLE
Docs API getCollections should only return collections

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1052]
The `io.stargate.web.docsapi.resources.CollectionsResource#getCollections` method is returning all tables in a keyspace rather than just the collections. Instead we should either make use of `io.stargate.web.docsapi.dao.DocumentDB#isDocumentsTable` or the internal schema cache.

**Comment by dougwettlaufer** [comment]
@EricBorczuk would you recommend using the cache in `io.stargate.web.docsapi.service.DocsSchemaChecker` or should we call `io.stargate.web.docsapi.dao.DocumentDB#isDocumentsTable` on each table?

**Comment by EricBorczuk** [comment]
Using the cache should be valid, and I believe the cache calls `isDocumentsTable` when there is no valid entry
