### ISSUE TITLE
Add possibility to ingest multiple rows in one call using the REST API

### ISSUE THREAD

**Issue by michelderu** [stargate/stargate#1056]
Just like the GraphQL API already supports multiple mutations in one go, the REST API should allow this also. This will improve performance as there is less overhead to create and setup the connection again and again. Perhaps multi-part or jsonlines could help.

**Comment by dougwettlaufer** [comment]
Thanks @michelderu. Closing this in favor of the existing issue https://github.com/stargate/stargate/issues/821
