### ISSUE TITLE
Refactor in-document get/search code to be aligned with DocumentSearchService

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#1059]
At this point `DocumentSearchService` handles searches across document partitions, while in-partition search is still handled by `DocumentService`.

In order to simplify code management when we add `OR` support (#828) it probably makes sense to unify the two call paths to share as much code as possible, but at least to share `where` clause parsing and field paths/globbing.

**Comment by dimas-b** [comment]
Not really specific to this issue, but it probably makes sense to handle it during this refactoring.

`404` responses sometimes return HTML payload as opposed to JSON, e.g.:

```
$ curl -L -H "X-Cassandra-Token: $AUTH_TOKEN" -g '127.0.2.1:8082/v2/namespaces/demo1/collections/test2/invalid-doc-id'
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/v2/namespaces/demo1/collections/test2/invalid-doc-id</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>jersey</td></tr>
</table>

</body>
</html>
```

**Comment by ivansenic** [comment]
Duplicate of #1028

**Comment by dimas-b** [comment]
Closing as a duplicate of #1028
