### ISSUE TITLE
Support `$or` document search

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1063]
After having parsing for `$or` (#1031) and after having support for merging queries (#1091) we can fully support ORs. Note that #1080 will add the support for `$or` in the in-document search.
**Support this**:

* `a = 1 && (b = 2 || c = 3) && (d = 4 || e = 5)`
*  `(b = 2 || c = 3) && (b = 2 || e = 5)` -> because it resolves to `b = 2 && (c = 3 || e = 5)`
* `(b = 2 || c = 3)`
* `(b = 2 || c = 3) && (d = 4 || e = 5)`

**Comment by dimas-b** [comment]
#1091 is going to allow generating "candidates" from a top-level OR expression (e.g. `a == 2 || b == 3`) by merging the corresponding result sets.
