### ISSUE TITLE
Support `$not` for the collection search

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1071]
Add a possibility to add `$not` as the filter operation for the document API. This should effectively negate anything that is wrapped in the `$not`.

**Comment by ivansenic** [comment]
@dimas-b Don't we need the #1027 done first here? Or you have another idea?

**Comment by dimas-b** [comment]
Yes, for some reason I assumed #1027 was already done :thinking:

**Comment by dimas-b** [comment]
However, since we never push `$exists` down to persistence, this issue may be doable before #1027 :thinking:
