### ISSUE TITLE
Searching collection can fail due to the race condition in JavaRx

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1076]
We are seeing that `BaseDocumentApiV2Test#searchPathWildcardsCandidatesMatching` is failing nondeterministicly on C* 4.0. Running locally with the `@RepeatedTest(1000)` does not show the problem. We need to explore more.

Failing build reference: https://console.cloud.google.com/cloud-build/builds/f877c255-c9e5-4032-b214-130e6daa0296?project=stargateio

**Comment by ivansenic** [comment]
OK, I did a long lasting analysis here, and I can confirm that this issue can be reproduced locally and that I tried to track down the real problem. Catching a failing test is not easy, as in my local checks it turns out that chances of failing is app. 0.1%. However, I caught one and it seems that the analysis so far is the following.

Documents:
`key: "non-matching", payload: {"value": "b"}`
`key: "wild-card", payload: {"value": "b", "someStuff": {"1": {"value": "a"}, "2": {"value": "b"}}}`
`key: "wild-card-not-matching", payload: {"value": "b", "someStuff": {"1": {"value": "c"}, "2": {"value": "d"}}}`

* I am running with `where={"value": {"$eq": "b"}, "someStuff.*.value": {"$in": ["b"]}}` with three docs matching the first condition and only `"wild-card"` the both
* the execution plan tree looks good: 
```
[
   {
      "data":{
         
      },
      "profile":{
         "description":"root",
         "queries":[
            
         ],
         "nested":[
            {
               "description":"FILTER: value EQ b",
               "queries":[
                  {
                     "cql":"SELECT key, leaf, WRITETIME(leaf) FROM \"ks_1625144701391_BaseDocumentApiV2Test\".collection WHERE p0 = ? AND leaf = ? AND p1 = ? AND text_value = ? ALLOW FILTERING",
                     "executionCount":1,
                     "rowCount":3
                  }
               ],
               "nested":[
                  
               ]
            },
            {
               "description":"PARALLEL [ALL OF]",
               "queries":[
                  
               ],
               "nested":[
                  {
                     "description":"FILTER IN MEMORY: someStuff.*.value IN [b]",
                     "queries":[
                        {
                           "cql":"SELECT key, leaf, text_value, dbl_value, bool_value, p0, p1, p2, p3, WRITETIME(leaf) FROM \"ks_1625144701391_BaseDocumentApiV2Test\".collection WHERE p0 = ? AND p1 > ? AND p2 = ? AND leaf = ? AND p3 = ? AND key = ? ALLOW FILTERING",
                           "executionCount":2,
                           "rowCount":2
                        }
                     ],
                     "nested":[
                        
                     ]
                  }
               ]
            },
            {
               "description":"LoadProperties",
               "queries":[
                  
               ],
               "nested":[
                  
               ]
            }
         ]
      }
   }
]
```
* so we see that 3 rows were selected after the first query, this is perfectly correct
```
[
   {
      "key=wild-card",
      "leaf=value",
      writetime(leaf)=1625144798615000
   },
   {
      "key=non-matching",
      "leaf=value",
      writetime(leaf)=1625144798609000
   },
   {
      "key=wild-card-not-matching",
      "leaf=value",
      writetime(leaf)=1625144798621000
   }
]
```
* but the in memory filtering has only 2 execution, one returning 2 rows. We should have 3 executions!?!? It turns out that we get this back from these rows back form the data store:

```
[]
[
   {
      "key=wild-card-not-matching",
      "leaf=value",
      "text_value=c",
      "dbl_value=null",
      "bool_value=null",
      p0=someStuff,
      p1=1,
      p2=value,
      p3=,
      writetime(leaf)=1625144798621000
   },
   {
      "key=wild-card-not-matching",
      "leaf=value",
      "text_value=d",
      "dbl_value=null",
      "bool_value=null",
      p0=someStuff,
      p1=2,
      p2=value,
      p3=,
      writetime(leaf)=1625144798621000
   }
]
```
* so empty rows do match a query for doc with id `"not-matching"`, yes
* other two rows match perfectly the query for the doc with id `"wild-card-not-matching"`
* but what's wrong with our only matching document?!!?!? Seems like query for it was not executed and that it was swallowed on the way

**Comment by ivansenic** [comment]
Further analysis showed that problem is most likely around the `Flowable.withLatestFrom()`, apparently it depends on the time when the document and prepared queries resolve. If the query resolves after the two documents, first one gets discarded. This could be a JavaRx bug or our misuse. 

I will create a ticket on the JavaRx providing the example that outlines the problem. I will fix our code to not sue this function anymore.

**Comment by ivansenic** [comment]
https://github.com/ReactiveX/RxJava/issues/7288

**Comment by akarnokd** [comment]
Looking at the usages ([1](https://github.com/stargate/stargate/blob/ac39840e6773a8ebc1002e05f1125cee41b0e8d7/restapi/src/main/java/io/stargate/web/docsapi/service/query/DocumentSearchService.java#L155-L170), [2](https://github.com/stargate/stargate/blob/ac39840e6773a8ebc1002e05f1125cee41b0e8d7/restapi/src/main/java/io/stargate/web/docsapi/service/query/DocumentSearchService.java#L155-L170)), `withLatestFrom` is the wrong operator to use.

As I understand, you wanted to combine every `candidate` item with the same single async value of `preparedSingle`. You can achieve this by caching `preparedSingle` and then using another `concatMap` to get to the inner value:

```java
return candidate
.concatMapSingle(main -> preparedSingleCached.map(other -> Pair.of(main, other)))
.concatMap(p -> {
    // ...
})
```

However, the returned Flowable won't be reusable as it will keep combining with the same cached value. To resolve this, you'll have to put the whole method body into `Flowable.defer`:

```java
return Flowable.defer(() -> {
   Single<? extends Query<? extends BoundQuery>> preparedSingle = //...

   Single<? extends Query<? extends BoundQuery>> preparedSingleCached = preparedSingle.cache();

   return candidate
        .concatMapSingle(main -> preparedSingleCached.map(other -> Pair.of(main, other)))
        .concatMap(p -> {
            // ...
        });
});
```
