### ISSUE TITLE
404 error if send request to subdocument with "fields" but without "where".

### ISSUE THREAD

**Issue by semichkin** [stargate/stargate#1107]
I am using astra db.
I send request to `.../collections/{collectionName}/{documentId}/{someSubdocument}/*?where={...}&fields=[...]` and this works correctly. But if i send this request without "where" parameter `.../collections/{collectionName}/{documentId}/{someSubdocument}/*?fields=[...]` i get 404 error.

**Comment by EricBorczuk** [comment]
Hi @semichkin ,

I believe the intended usage is to request without the `*` in the request, so `.../collections/{collectionName}/{documentId}/{someSubdocument}?where={...}&fields=[...]` and `.../collections/{collectionName}/{documentId}/{someSubdocument}?fields=[...]`

Please try that out for me, and let me know if you aren't getting expected data out!

**Comment by ivansenic** [comment]
@semichkin And note that the response body format you get back depends if there is `where` or not. With `where` it's considered as the sub-document search and in other as sub-document get. The data format in the response would differ.

**Comment by dougwettlaufer** [comment]
@semichkin is this still an issue or can this be closed?
