### ISSUE TITLE
GraphQL: add a metric for errors

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1114]
Apart from upstream technical errors (auth, missing keyspace), we returns HTTP status 200 even when the GraphQL response contains errors.

This is the usual convention for GraphQL service, however it makes it difficult to monitor errors.
Add a custom metric to track errors.

**Comment by marksurnin** [comment]
@olim7t what do you think about making the status code configurable to 500 in this case? We got feedback from developers that they'd rather not have to check whether the GraphQL response contains an `errors` field every time :)

We use a common library that raises an exception in case of a non-2xx response status code so it would be a bit more convenient to return a 500 from the service instead.
