### ISSUE TITLE
Return DocumentSearchResponseWrapper from searchDoc

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1121]
In the docs API both `searchDoc` and `getDoc` return the same `DocumentResponseWrapper`. This overly generic wrapper is not conducive to generating docs or clients. Since the wrapper has a field 

```java
  @JsonProperty("data")
  T data;
```

which could be either a single object or an array this makes it confusing to generated clients. Plus there is a single `documentId` field which in the case of search doesn't make sense because it should be a list of documentIds.

To fix this we can keep `getDoc` as is but introduce a new `DocumentSearchResponseWrapper` for `searchDoc` that will be roughly the same except there will be a list of documentIds and instead of a generic data field it will instead specify a list.

Fortunately this change will not break the API contract but rather be more explicit about defining it.

**Comment by ivansenic** [comment]
Quick note, about the `documentId` field:

* if we get a single document, it will be set to that document id
* if we search the complete collection this field is not set at all, the data structure is `{"docId1": { ... }, "docId2": { ... }}`:
* if we search inside a single document, it will be set to that document id
