### ISSUE TITLE
Add comments to playground tabs

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1128]
We should add some comments and more documentation around the default tabs in graphql playground [here](https://github.com/stargate/stargate/blob/master/graphqlapi/src/main/resources/playground.html#L565-L577). 

Something to the affect of

```graphql
# This is a sample for schema related operations. Below is a sample query for listing your keyspaces
{ keyspaces{ name } }
```

then the other tab could say something like

```graphql
# This tab is identical to the first but is here as an example for working with your data. Note that the path 
# above includes the name of an existing keyspace. Feel free to close this tab or open as many as you like 
# while exploring the GraphQL API.
```

**Comment by polandll** [comment]
I have some ideas. Let me make some suggestions.

**Comment by dougwettlaufer** [comment]
> I have some ideas. Let me make some suggestions.

Much appreciated. I'm not sure how this will relate to https://github.com/stargate/stargate/issues/371 though. We might drop that one and just add some sample queries as comments.

**Comment by polandll** [comment]
The other choice is a "Import file" button in the playground. I can't tell you how many times I wished that existed.

**Comment by polandll** [comment]
File to be modified is: https://github.com/stargate/stargate/blob/6452957cd078f17f1c0067c943e3fc2129f61ceb/graphqlapi/src/main/java/io/stargate/graphql/web/resources/PlaygroundResource.java
