### ISSUE TITLE
Explore moving from playground to graphiql

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1129]
Per [this issue](https://github.com/graphql/graphql-playground/issues/1143) on playground it looks like playground is being merged with [graphiql](https://github.com/graphql/graphiql). We should look into updating. Github has a cool example of an embedded graphiql instance

https://docs.github.com/en/graphql/overview/explorer

**Comment by polandll** [comment]
List of GraphQL IDEs that is more current: https://hasura.io/blog/top-7-graphql-ides-you-should-know-about-in-2021/
