### ISSUE TITLE
Add a DELETE call that uses a WHERE clause

### ISSUE THREAD

**Issue by jdavies** [stargate/stargate#1135]
I have a feature request for Stargate as a result of using the REST API for my Hackathon project. I would like to issue a DELETE command on a table with a WHERE clause. I want to do this because at the end of my demo I want to reset (aka DELETE) the data that I created. Right now the delete command only lets me specify the primary key for the record. If it had a WHERE clause then I could use the SAI to identify the row(s) I want to delete. In my case I want to delete all records from the BAGGAGE table where the passenger_id = some uuid. Naturally a passenger may have multiple bags checked in per trip.
Obviously this is not a show-stopper issue, but is a quality-of-life request.

**Comment by dougwettlaufer** [comment]
Currently this isn't supported in C* or DSE, a delete can only include the primary key of the record. By including the SAI it would require a "read before write" which isn't supported.

An example of this in CQL would be

```
CREATE TABLE ks1.tbl1 (
    i int PRIMARY KEY,
    j text,
    k int
);

CREATE CUSTOM INDEX ks1_tbl1_sai_idx_j ON ks1.tbl1 (j) USING 'StorageAttachedIndex';

insert into ks1.tbl1 (i,j,k) VALUES ( 1,'1',1) ;

SELECT * FROM  ks1.tbl1 ;

DELETE from ks1.tbl1 WHERE i = 1 and j = '1';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Non PRIMARY KEY columns found in where clause: j "

DELETE from ks1.tbl1 WHERE j = '1';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Some partition key parts are missing: i"
```

**Comment by jeffreyscarpenter** [comment]
JSON API supports a deleteMany operation
