### ISSUE TITLE
gRPC: Waiting for schema agreement should be asynchronous 

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#1145]
Maybe not critical, but waiting for schema agreement after DDL queries currently uses `Persistence.waitForSchemaAgreement()` which synchronously waits (via `Uninterruptibles.sleepUninterruptibly()`) which blocks gRPC request processing event loops. Ideally, this would use an asynchronous mechanism to allow event loops to continue processing other requests.

**Comment by ivansenic** [comment]
Can this be connected to #1151. Not sure if we have there the DDL queries..
