### ISSUE TITLE
Possible lock in the reactive document service RX chain

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1151]
When getting a document and performing a dead leaves deletion, we might end-up in the dead-lock (or some other kind of issue) inside the `CoreThread`s that are used to actually communicate with DSE. This results in timeout error and is shown in the `DocumentApiV2Test.testPutReplacingWithArray` test.

I managed to grab the thread dump in the middle of the test when we are actually waiting for the result of dead leaves deletion. The full log is [here](https://gist.githubusercontent.com/ivansenic/eece0dffdd7b48b90e8915808c3ba532/raw/9683a785cf09dc89089c43e7113a92313adca430/gistfile1.txt).

As we can see, the log the `[CoreThread-4]` deletion of the dead leaves. However in the thread dump the thread is `parking to wait for  <0x000000073ed5d7b0>`. And it stays there until timeout is signaled. Right after we start the leave deletion, the message:

`WARN  [GossipStage:1] 2021-07-28 15:38:55,293 StorageService.java:3061 - /127.0.0.1 has the same server ID C0-3C-59-BF-C0-ED, and same DC dc1, but is placed in a different rack r1 - (/127.0.2.1, dc1, rack1) vs. (/127.0.0.1, dc1, r1)`

However, in the CI when the test fails the above message is not shown and instead we have:

```
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-28 10:00:33,633 ProcessRunner.java:78 - storage0-0> INFO  [OptionalTasks:1] 2021-07-28 10:00:33,633  Gossiper.java:546 - Destroying messaging connection to /127.0.2.33 due to endpoint being removed from cluster
Step #4 - "dse-6.8": INFO  [Exec Stream Pumper] 2021-07-28 10:00:56,392 ProcessRunner.java:78 - stargate33-0> INFO  [OptionalTasks:1] 2021-07-28 10:00:56,392 Gossiper.java:546 - Destroying messaging connection to /127.0.2.33 due to endpoint being removed from cluster
```

Any help is welcome.

**Comment by ivansenic** [comment]
I can confirm that this problem existed before the yesterday commit for moving to the Cassandra 4 GA. We just did not hit it in the tests.

**Comment by dimas-b** [comment]
I guess the Gossiper messages might be a side effect of having core threads locked up for a while. The Gossiper might have decided the node was dead or something like that.
