### ISSUE TITLE
Combining paging state does not maintain the order of single states

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1162]
For combining paging state we are getting state from two or more queries. However, if both queries produce the same row, then the combined state will be different depending which query was faster. This means that when combining state we can end up in `[q1s, q2s]` or `[q2s, q1s]`.

This is a problem because when using the combined state we always assume that the states are in by-query order. Meaning we expect to get `[q1s, q2s]`. We need to find a way to respect the order of the states as the provided queries.

In the tests, I got for the same query two different state values:

1. `AAAAAgAAAAAAAAAVCW1hdGNoaW5nMQDwf_____B_____`
2. `AAAAAgAAABUJbWF0Y2hpbmcxAPB_____8H____8AAAAA`

When decodeing this the results are:

1. [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 21, 9, 109, 97, 116, 99, 104, 105, 110, 103, 49, 0, -16, 127, -1, -1, -1, -16, 127, -1, -1, -1]
2. [0, 0, 0, 2, 0, 0, 0, 21, 9, 109, 97, 116, 99, 104, 105, 110, 103, 49, 0, -16, 127, -1, -1, -1, -16, 127, -1, -1, -1, 0, 0, 0, 0]

It's clearly see that the states index are rotated in two examples.

**Comment by dimas-b** [comment]
@ivansenic : in the description, by "faster" do you mean faster in preparation or faster in execution?

**Comment by ivansenic** [comment]
> @ivansenic : in the description, by "faster" do you mean faster in preparation or faster in execution?

Execution. So which row is the first to create the Accumulator. That one will have the index [0], and then as other resolved they will have index + 1.
