### ISSUE TITLE
Documents API support for specifying additional partition / clustered keys

### ISSUE THREAD

**Issue by alecl** [stargate/stargate#1169]
Support a way to modify the documents API PUT/POST creation to include additional partition / clustered order keys at the head of the list BEFORE the key (documentId)

This would allow us to localize certain documents in a collection to certain nodes and  potentially make the secondary indexes not have to hit every cluster node (I think... not sure if that optimization would occur).

DBAs I talk to really give engineering grief about using secondary indexes on big clusters and seeing if there's a path to mitigate.

**Comment by ivansenic** [comment]
Can you provide an example here?

This would be possible, we just need to see a clear use-case and find the way to support it.
