### ISSUE TITLE
Add OpenRPC / JSON-RPC 2.0 Endpoints

### ISSUE THREAD

**Issue by bschrenk-td** [stargate/stargate#1177]
I would love to see the addition of a third endpoint type for OpenRPC / JSON-RPC for the Stargate platform to access Cassandra data to go along with the REST and GraphQL implementations. 

[OpenPRC Docs](https://open-rpc.org/)
[JSON-RPC 2.0 Spec](https://www.jsonrpc.org/specification)

**Comment by dougwettlaufer** [comment]
@mpenick could this fall under future types in the existing gRPC module along with `CQL`?

**Comment by tatu-at-datastax** [comment]
Is JSON-RPC (still) widely used these days?
