### ISSUE TITLE
Ability to batch-upload a document array with heterogeneous idPath

### ISSUE THREAD

**Issue by Cienfueguero** [stargate/stargate#1191]
Currently, batch-uploading a document array with known id is only supported if the idPath is the same (single value) across all documents in the array. For example: `[{"id": "1","car":{"make":"Bentley","year":"2020"}},{"id": "2","car":{"make":"Bentley","year":"2018"}}]` in which case `id-path = "id"`.

But say we have a FHIR (Fast Healthcare Interoperability Resources) resource bundle. It's an array of documents, where each document is a different resource, with a potentially different idPath.

Request is to have the ability to batch-upload these bundles or compositions with a heterogeneous idPath defined. For example: `[{"id": "1","car":{"make":"Bentley","year":"2020"}},{"identifier": "2","car":{"make":"Bentley","year":"2018"}}]` in which case `id-path = ["id","identifier"]`.

**Comment by EricBorczuk** [comment]
So the idea here is that you would supply an id-path that is an array with exactly the same length as the array of documents provided? That should be simple enough to implement without breaking backwards-compat. And you'd still be able to do things like `id-path=["a.b.id", "b.c.id"]`, etc.

I will take a look at this!

**Comment by Cienfueguero** [comment]
We have something similar when performing a search with filter condition
`where = {"*.make":("$eq":"Bentley"}}`
on collection
`[{"id":"1","car":{"make":"Bentley","year":"2020"}},{"id":"2","vehicle":{"make":"Bentley","year":"2018"}}]`
and then selecting
`fields = ["car","vehicle"]`

**Comment by Cienfueguero** [comment]
I would argue that we can introduce some sort of notation, like ["id"(997),"identifier"(1),"id"(2)] instead of ["id", "id", "id", ..., "identifier"]. The program should take care of the rest.
