### ISSUE TITLE
No operation available for full or partial text search 

### ISSUE THREAD

**Issue by youngnishant** [stargate/stargate#1195]
I was trying to implement search query so i was not able to find the implementation of full text search or partial text search using collection api, Please help me to implement small search query using @astra/collections or rest api's.
Thank you

**Comment by dougwettlaufer** [comment]
Hi @youngnishant . The documents api does not currently support partial text search. Is this what you're looking for in astrajs for the full text search?

https://github.com/datastax/astrajs/blob/master/packages/collections/src/collections.test.js#L308-L313

**Comment by youngnishant** [comment]
As we can use wildcards in cql, can we not add some wildcards in documents api library ?

**Comment by dougwettlaufer** [comment]
Wildcards are allowed on the path side of the query but not for the search term. As far as I know wildcards in cql are only allowed with DSE Search and SASI indexes.
