### ISSUE TITLE
REST API and DocsAPI should both handle `fields` param in the same way

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1213]
In the REST API the fields param is expected to be a comma delimited list of field names like `fields=username,firstname,lastname` but DocsAPI is expecting a JSON list like `fields=["username","firstname","lastname"]`.

Since we can't change them now because it will break the API contract lets instead support both the json list and comma delimited format on both sides to avoid confusion of anyone using the API.

**Comment by Cienfueguero** [comment]
Excellent fix. Thanks for escalating it. I would also recommend to clarify the API documentation with valid examples.
