### ISSUE TITLE
Add health checks to grpc service

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1219]
Need to add health checks to grcp similar to those in the other services.

**Comment by tomekl007** [comment]
It seems that we already have a mechanism for automatically registering the health-check via `BaseActivator`:
```
public GrpcActivator() {
    super("gRPC", true); // true means register health check
  }
```
and it result in:
```
grpc: {
healthy: true,
message: "Available",
duration: 0,
timestamp: "2021-09-07T11:06:05.842+02:00"
},
```
so we don't need to do it here.

**Comment by dougwettlaufer** [comment]
@tomekl007 does that mean this issue can be closed?

**Comment by tomekl007** [comment]
Health check is registered, closing
