### ISSUE TITLE
External Auth/Adding Claims

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#122]
Pluggable auth is a current industry trend for handling authentication/authorization. Being able to add Claims in JWT tokens is a way for users to securely pass user, role, and other information into persisted queries in a way that does not rely on a bespoke auth implementation.

While Stargate appears to have the ability for pluggable auth, the current implementation track seems to be predicated on the idea that users will be using it in conjunction with c* row-level authorization and user accounts. It isn’t a common paradigm for frontend applications to create a database user for each application user and they may not want to take advantage of row level security. Additionally, the current graphql schema also doesn’t support the ability to define role permissions so it is unclear how a user would set this up without a backend service or manual intervention.

The current track for pluggable auth seems to disallow the ability for frontend developers to do their own user/role management. Developers may also want to utilize a different provider such as Facebook auth or Auth0 for auth. This may lead to a brittle second system of credential handling in a frontend application.

We can support external authentication mechanisms and custom user handling with only needing to support JWT claim parsing on the graphql endpoint. This would allow a bring-your-own auth with a clear separation of concerns for the underlying layers.

Graphql Schema Example:jwt:

```
{
  "user_id": "a4cd2479-9915-4b03-9f78-dca71dc81dac",
  "iat": 1516239022
}
```

```
mutation InsertCartEntry($cartId: TimeUuid, $quantity: Int) {
 insertCart(value: { cartId: $cartId, quantity: $quantity, _jwt_claim: {userId: "user_id"} }) {
  value {
   cartId
   quantity
  }
  applied
 }
}

query getCartByUser($pageState: String) {
 cart(options: {
     pageState: $pageState
 }, filter: {
    _jwt_claim: {userId: "user_id"} 
}) {
   value {
     product {
        name
        price
     }
     quantity
   }
   pageState
 }
}
```

**Comment by olim7t** [comment]
How does this relate to #339?

**Comment by dougwettlaufer** [comment]
Actually #339 closes this issue.
