### ISSUE TITLE
Malformed URL causing socket hang up

### ISSUE THREAD

**Issue by mbiciunas** [stargate/stargate#1226]
**Steps to Reproduce:**
Executing GET with a malformed URL (Note "api" misspelled as "a1pi"):  
https://b65d3f4e-0fb0-4375-b39c-3d6a07e25728-southcentralus.apps.astra.datastax.com/a1pi/rest/v2/schemas/keyspaces

Causes the following on Postman:
    Error: socket hang up
    Request Headers
    x-cassandra-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    content-type: application/json
    User-Agent: PostmanRuntime/7.26.8
    Accept: */*
    Cache-Control: no-cache
    Postman-Token: df954a9e-65ec-4c84-97a5-807cb01c4662
    Host: b65d3f4e-0fb0-4375-b39c-3d6a07e25728-southcentralus.apps.astra.datastax.com
    Accept-Encoding: gzip, deflate, br
    Connection: keep-alive

**Expected Outcome**
Either a "500 Internal Server error", which happens if you change the misspelling from "a1pi" to "api1" or "404 Not Found" which is what you get if you misspell "rest" as "rest1".

This behavior can be challenging during development (python 3.7 using requests library (2.26.0)) as socket hang up was leading me to believe an authentication error was happening as opposed to a malformed URL.

**Comment by mbiciunas** [comment]
Sorry I neglected to mention, this happens when accessing an Astra database.  So set up a free Astra database, set up the access credentials and attempt to use the REST API through postman. 

If "api" is misspelled as "a1pi", you'll get a socket hang up and no status code.  Oddly enough, misspelling it as "api1" will get you a "500 Internal Server error" so something changes when evaluating URL.  Either way, I think you should just be getting a "404 Not Found" as the most clear indication of an error in the URL.

**Comment by ivansenic** [comment]
Thanks @mbiciunas for the report, we will pass this along. Most likely the request is not even reaching the Stargate, but we will inform you when this gets solved.
