### ISSUE TITLE
Make fragments of Document and Sub-Document available using WHERE query parameter

### ISSUE THREAD

**Issue by ranjitg2021** [stargate/stargate#1242]
We notice that when searching within a collection using a WHERE clause/query parameter, it returns the whole document(s) including the sub-documents that do not qualify.

Here's a document:
`{
    "documentId": "104",
    "data": {
        "club_checkins": [
            {
                "checkin_date": "2021-02-03T18:25:43.511Z"
            }
        ],
        "club_expiration": "2021-10-13T18:25:43.511Z",
        "club_id": 12359,
        "club_joined": "2020-06-13T18:25:43.511Z",
        "club_membership": "50K",
        "contact": {
            "cell_phone": "+1 555-555-5555",
            "email": [
                "test+004@somebiz.com"
            ],
            "home_address": "104 Main St, Palo Alto, CA 95005",
            "opt_in": true,
            "work_address": "104 Main St, Palo Alto, CA 95005",
            "work_phone": "+1 555-555-5555"
        },
        "flight_history": {
            "domestic": [
                {
                    "bags_checked": 2,
                    "flight": "ABC0304",
                    "flight_date": "2012-04-23T18:25:43.511Z",
                    "miles_earned": 1795,
                    "ticket": "68780000-1111-1111-1111-000011110004"
                },
                {
                    "bags_checked": 1,
                    "flight": "ABC0305",
                    "flight_date": "2015-12-23T07:25:43.511Z",
                    "miles_earned": 891,
                    "ticket": "68780000-1111-1111-1111-000011110005"
                }
            ],
            "international": [
                {
                    "bags_checked": 2,
                    "flight": "ABC9303",
                    "flight_date": "2013-06-01T06:25:43.511Z",
                    "miles_earned": 3458,
                    "ticket": "68780000-1111-1111-1111-000011110006"
                }
            ]
        },
        "id": "104"
    }
}`

And we'd like to pull only those elements within Flight_History -->> Domestic array with bags_checked >= 2

Performing a GET request using returns the entire document:

> https://{{db}}-{{region}}.apps.astra.datastax.com/api/rest/v2/namespaces/{{keyspace}}/collections/customers?page-size=20&where={"flight_history.domestic.[*].bags_checked" : {"$gte" : 1}}

Is an enhancement feasible to support the requirement?

**Comment by ranjitg2021** [comment]
Thank you @EricBorczuk for clarifying

**Comment by ivansenic** [comment]
@ranjitg2021 @EricBorczuk Can you write in a comment a way to solve the problem described in the ticket, so that other people can have a clear picture as well?
