### ISSUE TITLE
Readiness check URI is truncated to include only the first query parameter

### ISSUE THREAD

**Issue by marksurnin** [stargate/stargate#1243]
I noticed that curling `localhost:8084/checker/readiness?check=datastore&check=graphql` results in only the first check being run. The `checks` variable in [CheckerResource.java](https://github.com/stargate/stargate/blob/6452957cd078f17f1c0067c943e3fc2129f61ceb/health-checker/src/main/java/io/stargate/health/CheckerResource.java#L70) would always contain the value of the first `?check` query parameter.

I added a breakpoint to CheckerResource and I noticed that the URI was truncated much higher in the call stack:
<img width="1479" alt="Screenshot 2021-09-13 at 18 57 35" src="https://user-images.githubusercontent.com/5126685/133133552-535dc875-3388-465c-8b18-93583939c575.png">

There's a note in [QueryParam docs](https://docs.oracle.com/javaee/7/api/javax/ws/rs/QueryParam.html):

> If the type is not one of the collection types listed in 5 above and the query parameter is represented by multiple values then the first value (lexically) of the parameter is used.

The type of `checks` is `Set<String>` which satisfies the condition above. However, the first value (lexically) of the parameter is used.

**Comment by ivansenic** [comment]
@marksurnin What client do you use to fire the request? Just tried it from the browser and it works fine.. 

If you are using cURL, this works as well `curl 'http://localhost:8084/checker/readiness?check=datastore&check=graphql'`.. However with curl a URL without the single quotes does not work -> `curl http://localhost:8084/checker/readiness?check=datastore&check=graphql`.

**Comment by marksurnin** [comment]
@ivansenic good catch, I missed that. Thanks!
