### ISSUE TITLE
Add metrics to our `LoadingCache` instances

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#1249]
We should add metrics to our cache instances to help users identify problems with cache settings. Caffeine supports supplying a custom `StatsCounter` that can be used to hook into Stargate's metrics system: https://javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Caffeine.html

We should also prefer using a single cache implementation in our modules, where possible, instead of using both Guava and Caffeine.

**Comment by tatu-at-datastax** [comment]
+1 for unification, and +1 for Caffeine over Guava (or anything newer), just because of Guava being a problem wrt version compatibility. I think Caffeine was considered a superset of Guava's caching anyway so there are other good reasons too.
