### ISSUE TITLE
Surface database field names

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#125]
Since we automatically convert field names to a graphql compliant names, we should also surface the original field name as well. If we do it in a comment, we can include the original UTF name.

This has the benefit of disconnecting our naming conventions with the underlying database so users can modify them at will.

```
type UserAddress @db(name: "user_address"){
  zipCode: String @db(name: "zip_code")
}
```

**Comment by olim7t** [comment]
Probably better to do it in a comment, it looks like schema directives will not be reflected via introspection (see discussion on #139).
