### ISSUE TITLE
Backport `NonBlockingRateLimiter` to the CQL module

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1254]
[CASSANDRA-16663](https://issues.apache.org/jira/browse/CASSANDRA-16663) adds a new rate-based limiter to the native protocol server.
Backport this to our CQL server, and expose the related configuration options as Stargate properties.

See also: #1250

**Comment by olim7t** [comment]
In fact we won't be backporting the class, just pulling it from the `cassandra-all` dependency (as we do currently for `ResourceLimits`). So this requires updating the dependency to 4.1.0.

**Comment by tatu-at-datastax** [comment]
Cassandra 4.1.0 is not out yet so would this need to wait for that release to happen first?
