### ISSUE TITLE
Introduce a schema migration feature for Stargate

### ISSUE THREAD

**Issue by adutra** [stargate/stargate#1295]
Currently Stargate manages the creation of the `data_endpoint_auth` keyspace and its contents.

The keyspace creation itself, as it seems, was introduced to allow newcomers to get easily started with Stargate. However, any serious production deployment is likely required to create that keyspace upfront, so that it is created with desired replication settings across DCs. Indeed, both the Astra and K8ssandra teams have opted for creating that keyspace before deploying Stargate nodes, and that's fine.

Managing _the contents_ of that keyspace is another story. For now, it's easy as there is only one single table to create: `token`, and that table definition has never changed. It is in theory possible to let Stargate create the table, but that solution is racy: if 2 Stargate nodes detect that the `token` table does not exist, they could both attempt to create it, and only one would succeed – the other would get a table ID mismatch and fail to start. Our teams (K8ssandra and Astra) are thus creating the table too, or planning to do so (see https://github.com/k8ssandra/k8ssandra-operator/issues/156). 

This approach, in conjunction with the `-Dstargate.auth_tablebased_init=false` system property, is working fine for now. But the table definitions and the data they contain may evolve over time and require migrations when Stargate is upgraded. 
This can only be done reliably by Stargate itself. Moreover, such a schema migration should not happen as part of the normal startup process, because schema migrations cannot happen concurrently, as illustrated above.

This is why we think there should be a schema migration feature in Stargate. This idea has been implemented in Reaper, see [the docs](https://github.com/thelastpickle/cassandra-reaper/blob/e82d464b15299445791bf71a4e43b0d84a131d9e/src/docs/content/docs/usage/_index.md#schema-migrations) and the corresponding [Docker entrypoint](https://github.com/thelastpickle/cassandra-reaper/blob/b9c7129361db47da70b56ca589db36929939e891/src/server/src/main/docker/entrypoint.sh#L49-L62). If such a feature existed, then the ideal procedure to deploy Stargate would be as follows:

1. The operator (Astra, K8ssandra) creates the `data_endpoint_auth` keyspace with desired replication.
2. The operator (Astra, K8ssandra) launches a Kubernetes Job that will invoke Stargate in schema migration mode. 
3. Once the schema is up-to-date, the operator proceeds with launching actual Stargate nodes, passing `-Dstargate.auth_tablebased_init=false` to the nodes.

**Comment by dougwettlaufer** [comment]
Thanks @adutra for the detailed write up on this. It's an interesting idea and if we make changes to the table based auth process we'll take it into consideration. For the time being we have no plans for altering table based auth since as you mention it's meant as a default, getting started sort of authentication. For most production use cases we'd expect users would want to either integrate with their existing auth providers or use the JWT based approach.
