### ISSUE TITLE
Add helper method for logging in Starter.java

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#1303]
In the starter class we `System.out` for "logging" since logback hasn't been enabled yet in this context. This is fine except it makes it a little difficult to grok for Starter related logs. 

Add a helper method to prepend levels to the messages to make it easier to identify errors versus info.

**Comment by shashankbrgowda** [comment]
Hi, Can I work on this issue ?

**Comment by ivansenic** [comment]
@shashankbrgowda Hi, we already have a PR for this issue in review: https://github.com/stargate/stargate/pull/1348.

**Comment by dougwettlaufer** [comment]
@Lukkaeuss are you still working this issue?

**Comment by Lukkaeuss** [comment]
> @Lukkaeuss are you still working this issue?

Hello, yes im still working on it. I expect to do PR in upcoming week if that's ok with you.
