### ISSUE TITLE
Wrong column type expected after dropping a keyspace and recreating it with different schema

### ISSUE THREAD

**Issue by pkolaczk** [stargate/stargate#1313]
Steps to reproduce:
1. Run a GRPC client that creates a keyspace and a table and inserts some data:

        CREATE KEYSPACE IF NOT EXISTS ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
        CREATE TABLE IF NOT EXISTS ks.test(pk BIGINT PRIMARY KEY);
        INSERT INTO ks.test(pk) VALUES(1);

2. Without restarting SG, launch cqlsh and drop the keyspace:

        DROP KEYSPACE ks;

3. Modify the client to use a schema with a different column type (BIGINT -> VARCHAR):

        CREATE KEYSPACE IF NOT EXISTS ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
        CREATE TABLE IF NOT EXISTS ks.test(pk VARCHAR PRIMARY KEY);
        INSERT INTO ks.test(pk) VALUES("1");

4. Attempt to run the INSERT statement fails with:

         InvalidArgument, message: "Invalid argument at position 1: Expected integer type", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

5. Restart SG (without restarting C* cluster)
6. Run the client again - this time it succeeds.

**Comment by mpenick** [comment]
Yeah, this is almost definitely a prepared statement caching issue. Maybe we can invalidate by store and invalid by keyspace?
