### ISSUE TITLE
Add batching to mutations

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#133]
Atomicity can be important for some applications. Since batches has additional limitations to be used successfully, we should provide an alternative path for mutations that can be batched.

Batched statements have the following restrictions:

No light weight transactions

No mix of batched and unbatched statements

Avoid the word 'batch' as it could be unclear of the desired use case

No range queries

```
# Atomic directives override the serial execution order of mutations and allow 
# mutations to be executed in an all-or-nothing manner. IfExists, IfNotExists, 
# and ranged partition updates and deletes are forbidden.
directive @atomic

mutation @atomic {
  insertCart(value:{cartId: "..."}) {
    applied
  }
  insertUser(value:{userId: "..."}) {
    applied
  }
}
```

Alternative we can redefine all functions with an atomic_ prefix that only allow sane use of atomic statements. This would be safer but adds a lot of extra definitions to the schema.

**Comment by tub** [comment]
I like the idea of the directive instead of the prefix, keeping the schema simple would be great. 👍

**Comment by jorgebay** [comment]
I think having `@atomic` directive at `MUTATION` location makes sense from the design perspective, it's clean and unintrusive.

I'll give it a try to see how graphql java can intercept it.

**Comment by jorgebay** [comment]
In GraphQL java, it's possible to obtain the parent operation and directive using:

```java
environment.getOperationDefinition().getDirectives().get(0).getName() // "atomic"
environment.getOperationDefinition().getSelectionSet().getSelections() // all mutations
```

Let's see how hard it will be to refactor existing data fetchers to handle it.
