### ISSUE TITLE
Add hasNextPage for exact paging

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#134]
For front end applications, people like to know if there are more results to iterate through. The pageState is not enough as it can return a page state but not return any additional records.

If the nextPage attribute is not requested then the query processor should skip doing additional work.

```
query carts(pageState: String){
  cart(pageState: $pageState, pageSize: 10) {
    values {
       cartId
    }
    pageState
    nextPage
  }
}
```

**Comment by olim7t** [comment]
`pageState` should normally be absent if there is no next page. But as noted, there is a corner case where Cassandra can return a last page containing 0 elements.

If we want to truly know if there are no more results we'll need to pre-fetch the next page. This is somehow related to the offset paging feature I mentioned in #135 (the Java driver feature I linked to in that ticket does that pre-fetching thing).
