### ISSUE TITLE
Refactor private copies of `slf4j-api`, `logback` from bundles into shared OSGi context

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1345]
Currently we have about 12 copies of all slf4j API and implementation classes within various bundles: basically, all modules that do logging have their own copy. This seems unnecessary since OSGi allows use of shared dependencies, by combination of something Exporting required classes, using side Importing what is needed.

At the same time it is not immediately clear how this can be done: some dependencies (like `java-driver-shaded-guava`) are shared this way, but I cannot see jar itself either under `stargate-lib/` or embedded in any of bundles (for Export)

**Comment by jeffreyscarpenter** [comment]
@tatu-at-datastax is this still an issue?

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter I think this falls under category of "fixed by getting rid of OSGi". I assume copies might exist, but at the same time do not recall any actual problems we would have seen. So probably harmless.

So, I'll go ahead and close as not planned.
