### ISSUE TITLE
PageSize may return inaccurate number of rows

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#135]
Under the hood, graphql uses the fetchSize function to complete the page size request. Because cassandra does not always return the exact number of elements when using fetchSize, we should add additional checks to assure that the page size returns exactly the number of items requested.

We should expose fetchSize for applications that do not care about an exact number of records.

Making this change is important for front end applications as it would directly impact the user experience.

```
query {
  cart(value: {pk:"pk1"}, pageSize: 10) {
    values {
       cartId
    }
  }
}

query {
  cart(value: {pk:"pk1"}, fetchSize: 10) {
    values {
       cartId
    }
  }
}
```

**Comment by olim7t** [comment]
This will require fetching an additional page in the background if necessary (but that's not too hard to do).

If we're going to provide exact page size, we might as well support a page number, like [this](https://docs.datastax.com/en/drivers/java/4.9/com/datastax/oss/driver/api/core/paging/OffsetPager.html).

I'm not sure if it's worth exposing fetchSize, that makes the API most complicated and I think most people would prefer the exact variant if it's there.
