### ISSUE TITLE
Query TTL Function

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#138]
Add the ability to query for a ttl on a table.

```
type Cart {
  cartId: TimeUuid
  _ttl(field: CartFields): Int
}
```

**Comment by olim7t** [comment]
If we query multiple fields, we can't return a single int. I think the most pragmatic solution would be:
```
_ttl(fieldName: String): Int
```
And then it can be called multiple times with aliases.

We'll also need to handle the case where a CQL row happens to be called `_ttl`, we can escape it like we already do in other places.

**Comment by olim7t** [comment]
Or maybe we could generate an enum for the column names (maybe that's what `CartFields` is in the original example).
