### ISSUE TITLE
Improve JWT documentation

### ISSUE THREAD

**Issue by caniko** [stargate/stargate#1384]
Please provide a guide on what is required from our side, and then you should add a quick start guide. Currently, I am stuck not knowing where to start.

Thank you :)

**Comment by dougwettlaufer** [comment]
Hi @caniko. Are you wanting to make changes to the JWT code or just trying to run Stargate with JWT based auth? 

If you're trying to run Stargate have you seen our docs [here](https://stargate.io/docs/stargate/1.0/developers-guide/authnz.html#_jwt_based_authenticationauthorization)? These provide more info about JWT support along with a quick start guide using Keycloak and docker compose as an example (we picked Keycloak for ease of use but you can swap in your auth provider). If you would like to see some improvements to the linked docs can you please open an issue at https://github.com/stargate/docs and we'd be happy to help make those changes.

**Comment by caniko** [comment]
Run Stargate with JWT based auth. I have a Django server with JWT authentication, and wanted to use the same token for authentication for the Stargate API. Django uses a secret to generate the tokens, so I want to share this secret with Stargate for authentication.

I could not find a way to do this on the docs.

I am using K8ssandra.

**Comment by dougwettlaufer** [comment]
Have you looked at the example [here](https://stargate.io/docs/stargate/1.0/developers-guide/authnz.html#_jwt_based_authenticationauthorization)? To make this work you'll need to run Stargate with `-Dstargate.auth.jwt_provider_url=http://your-auth-provider-url` we have a docker-compose example [here](https://github.com/stargate/docker-images/blob/master/examples/stargate-jwt-auth/docker-compose.yml#L55). Then for every request from your Django to Stargate you would add the JWT to the `X-Cassandra-Token` header like [this](https://github.com/stargate/docker-images/blob/master/examples/stargate-jwt-auth/smoke_test.sh#L25-L26).

Stargate will then take the JWT from the request header and validate it against the auth provider URL you set on startup. The claim from the JWT will then be used to query Cassandra which will authorize based on the role and permission set up in your cluster.

**Comment by caniko** [comment]
FYI, the request to Stargate will be from the client-side (with JWT from Django), and not the Django server; moreover, I believe that the design still holds! Thank you!

This should be described explicitly in documentation.

Any ideas on how I can use JWT on K8ssandra with this configuration? I believe that it is currently limited to table-based authentication only.

Also, just because I am curious. Is it possible to have several JWT providers?

**Comment by dougwettlaufer** [comment]
> This should be described explicitly in documentation.

This should all be described in the docs with examples but if something is missing please feel free to open an issue in https://github.com/stargate/docs so we can get it added.

> Any ideas on how I can use JWT on K8ssandra with this configuration? I believe that it is currently limited to table-based authentication only.

It looks that functionality isn't currently available in k8ssandra so you'll need to directly edit https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/templates/stargate/stargate.yaml#L91-L95 to include the necessary system properties.


> Also, just because I am curious. Is it possible to have several JWT providers?

Currently, no, but you could fork stargate and update [io.stargate.auth.jwt.AuthnJwtService#validate](https://github.com/stargate/stargate/blob/master/auth-jwt-service/src/main/java/io/stargate/auth/jwt/AuthnJwtService.java#L121) to support multiple providers.

**Comment by dougwettlaufer** [comment]
FYI I've logged https://github.com/k8ssandra/k8ssandra/issues/1179 for adding the functionality to k8ssandra

**Comment by caniko** [comment]
Great! Now that [this](https://github.com/k8ssandra/k8ssandra/pull/1184) has been merged, is this supposedly possible without manual edition?

**Comment by dougwettlaufer** [comment]
Yes, now that they've made the change in that PR you can add the properties I referenced above without needing to fork.

**Comment by caniko** [comment]
@dougwettlaufer, is this configuration correct?

cassandra:
  version: "3.11.10"
  cassandraLibDirVolume:
    storageClass: local-path
    size: 5Gi
  allowMultipleNodesPerWorker: true
  heap:
    size: 1G
    newGenSize: 1G
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  datacenters:
  - name: dc1
    size: 1
    racks:
    - name: default
kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin123
stargate:
  enabled: true
  replicas: 1
  heapMB: 256
  cpuReqMillicores: 200
  cpuLimMillicores: 1000
  java_opts: -Dstargate.auth_id=AuthJwtService -Dstargate.cql_use_auth_service=true -Dstargate.auth.jwt_provider_url=http://127.0.0.1:8000/api-token-auth/

**Comment by dougwettlaufer** [comment]
I'm not very familiar with k8ssandra config but the `java_opts` seem right. Although you'll probably need to change the host in `jwt_provider_url` to point to a kubernetes service or hostname for your auth provider since localhost will try to look inside of the container in the stargate pod.
