### ISSUE TITLE
Add primary key directives to types

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#139]
It is difficult to determine the primary key columns when looking at the graphql schema. Adding directives would give people additional insight on the structure of the underlying tables.

Proposed directives:

Primary Key

Clustering Key

Static

MaterializedView

```
@MaterializedView(baseTable: "Cart")
@PrimaryKey(fields: ["cartId"])
@ClusteringKey(fields: [{field: userName, direction: DESC}]
type Cart_MV {
  cartId: TimeUuid
  quantity: Int
  userId: Uuid @static
  userName: String
}
```

**Comment by mpenick** [comment]
There's no way to add directives to fields and types in the schema introspection:
https://spec.graphql.org/June2018/#sec-Schema-Introspection

The only directive supported is `@deprecated` via `isDeprecated`.

**Comment by csplinter** [comment]
@mpenick is there any way that we can communicate to the user which fields are part of the primary key? This is critical for them to be able to know what they can use in filters

**Comment by jorgebay** [comment]
I'm giving it a try but I'm having a hard time defining the directive at object / input object level in the schema, it's not getting recognized by the builder... I might be doing something wrong.

**Comment by mpenick** [comment]
@jorgebay You can added it the the builder, but it won't make it into the fields schema (per my previous comment).

**Comment by mpenick** [comment]
I see two option:  1) We add to the comments for the fields, but that doesn't show up in things like graphiql or graphql playground, 2) have a naming convention where we add it to the field names e.g. `pk_title`, `ck_author`.

**Comment by jorgebay** [comment]
I'm not sure I understand what you are saying. The spec allows declaring directives at TypeSystemDirectiveLocation (i.e. `OBJECT` or `INPUT_OBJECT`) https://spec.graphql.org/June2018/#sec-Type-System.Directives
and there are examples object level directives in the wild: https://www.graphql-tools.com/docs/schema-directives/

**Comment by jorgebay** [comment]
https://www.apollographql.com/docs/apollo-server/schema/creating-directives/#declaring-schema-directives

**Comment by mpenick** [comment]
@jorgebay It'll never make it into the schema introspection json: https://spec.graphql.org/June2018/#sec-Schema-Introspection. There's no directives on fields in the schema introspection json spec. So you can add directives, but there's no way to associate those directives with fields that's useful the the client.

**Comment by jorgebay** [comment]
Wow, nice findings!

True, it doesn't look it would surface via introspection.

Weird that Apollo Federation project is using it ([see `@key`](https://www.apollographql.com/docs/federation/federation-spec/#key)). 

I only see it at `__InputValue` level...
