### ISSUE TITLE
Result structure for REST GET `/v2/schemas/keyspaces` (and `/v2/schemas/keyspaces/{keyspaceName}`) different from Swagger model in "simple" topology case

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1396]
Looks like results one gets for "Keyspace" entries (whether individual or List) does not conform to what Swagger API suggests. Individual keyspaces are expected to look like:

```
{
  "name": "{KEYSPACE_NAME}",
  "datacenters": [
    {
      "name": "{DC-NAME}",
      "replicas": 0
    }
  ]
}```

but in actuality for "simple" keyspaces (ones with topology other than networked) no `datacenters` is included at all:

```
{
  "name": "{KEYSPACE_NAME}"
}
```

Similarly I think "NetworkTopologyStrategy" would produce different, but incompatible, output (looks like that'd give `"dc-name":replica-count` instead of Object with `name` and `replicas`).

**Comment by dougwettlaufer** [comment]
The API is correct but the swagger needs updated. For SimpleStrategy we're returning just the name which doesn't match the Swagger and this is the current response fo NetworkTopologyStrategy which does match.

```
{
            "name": "testks",
            "datacenters": [
                {
                    "name": "dc1",
                    "replicas": 3
                }
            ]
        }
```

**Comment by tatu-at-datastax** [comment]
Thank you @dougwettlaufer for verifying this.

**Comment by tatu-at-datastax** [comment]
Due to conversion to Quarkus, OpenAPI, I think this as specific individual issue can be closed; we need to verify OpenAPI definitions as a whole.
