### ISSUE TITLE
Create Docker image for REST API Service

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#1400]
As part of Stargate v2, we want to make it easier to deploy Stargate in containerized environments. Part of this will consist of building Docker images as part of the regular build scripts. Since the REST API service is the first separate process being built for v2, we should start building a Docker image for that service.

**Comment by jeffreyscarpenter** [comment]
There are a couple of ways of doing this. Preliminary investigation:

- Jib, specifically the Maven Plugin https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin. This is easy to use and would integrate nicely into our build, but is not oriented toward the "fat jar" approach we have initially taken for the REST API service. Using Jib is probably the ideal end state, but not until we modernize the REST API service implementation from it's current use of Dropwizard and "fat jar" style deployment. Useful reference on why fat jars aren't a good fit for Docker: https://phauer.com/2019/no-fat-jar-in-docker-image/.
- Other Maven plugins. This post is useful on building Docker container for a Dropwizard microservice: https://phauer.com/2015/building-dropwizard-microservice-docker-maven/, however the plugin it recommends appears to be a dormant project. If we want to use a Maven plugin in the short term while the service is based on Dropwizard, this looks like the best choice: https://github.com/fabric8io/docker-maven-plugin.

**Comment by ivansenic** [comment]
Could be helpful: https://github.com/paketo-buildpacks/java

**Comment by jeffreyscarpenter** [comment]
Fixed by #1535
