### ISSUE TITLE
Support Map, Set, and List types

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#141]
Graphql does not have native support for Map types. I'm not familiar with a syntax that makes sense here. Suggestions?

```
type Example {
  exampleSet: [Type] @set
  exampleList: [Type] #default as list
  exampleMap: [MapExample] ##?
}
```

**Comment by jorgebay** [comment]
For https://github.com/datastax/cassandra-data-apis we used a custom key value type for map.
