### ISSUE TITLE
Enhancement request to include TTL for Documents in Astra DB

### ISSUE THREAD

**Issue by ranjitg-ds** [stargate/stargate#1414]
A client currently using Couchbase has indicated Astra DB is missing the Document Expiry feature. We like to suggest an enhancement request to include TTL for Documents in Astra DB.

Please refer to Couchbase documentation for details: https://docs.couchbase.com/server/current/eventing/eventing-examples-docexpiry.html

**Comment by msmygit** [comment]
Could we not directly alter the table to adjust the default time to live property of the document API table? 💡

**Comment by ivansenic** [comment]
@msmygit It's not that simple, as you might have different rows for the same document. Meaning if document was patched at some point, the TTL for the original rows and updated/patches rows would not be the same.

Please check the https://github.com/stargate/stargate/pull/1428 for current discussions around the implementation proposed.
