### ISSUE TITLE
Relay nested pagination

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#142]
Nested pagination is very difficult from an api perspective because there could be a large number of pageState parameters being passed in. The other option is to utilize connections which will allow new pages to be streamed in without having to recall the entire api.

For example:

```
fragment Feed_user on User {
  # This connection, under a specific User, will be uniquely identified by
  # the key "Feed_feed" and the value of `$orderBy` (given that no `filters` were provided)
  feed(
    first: $count
    after: $cursor
    orderby: $orderBy
  ) @connection(key: "Feed_feed") {
    edges {
      node {
        id
      }
  }
}
```

https://relay.dev/docs/en/pagination-container

**Comment by olim7t** [comment]
The Relay example is a client-side feature:

> Relay uses directives to add additional information to GraphQL documents, which are used by the Relay Compiler to generate the appropriate runtime artifacts. These directives only appear in your application code and are removed from requests sent to your GraphQL server.

(https://relay.dev/docs/en/graphql-in-relay#directives)

We don't control which client is used to access our API, so we should limit ourselves to standard GraphQL as defined by the spec. If we want streaming, we should look at subscriptions and maybe continuous paging on the server side (but that is only available with DSE).

**Comment by olim7t** [comment]
After reading up a bit more on Relay, it turns out I didn't have the full picture there ☝️ 

Relay directives are indeed compiled at build time, but Relay's pagination feature assumes a particular schema on the server. So we could support that structure (either in the CQL-first or the GraphQL-first API) for Relay users.
