### ISSUE TITLE
Explore using rest-assured for testing restapi

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#145]
Seems like it could clean up a lot of code and make things more readablehttps://github.com/rest-assured/rest-assured

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1197965991209714/1198118696004151) by [Unito](https://www.unito.io/learn-more)

**Comment by FRosner** [comment]
As it seems that dropwizard is already in use, the dropwizard-testing library might also be sufficient.

**Comment by dougwettlaufer** [comment]
The idea was that rest-assured would help make our integration tests a little more readable
https://github.com/stargate/stargate/blob/master/testing/src/test/java/io/stargate/it/http/RestApiv2Test.java

**Comment by FRosner** [comment]
For integration tests it makes sense! Sorry for all the questions I'm slowly getting comfortable with the code base when I got some spare time :D

**Comment by tatu-at-datastax** [comment]
May be tackled with Quarkus conversion, driven by how Integration Tests converted. But part of bigger discussions, closing this as part of backlog clean up (not because it's not a good idea)

**Comment by ivansenic** [comment]
It's rest-assured in Docs V2 already..
