### ISSUE TITLE
Add `timestamp()` method to `io.stargate.grpc.Values` helper class

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#1487]
We missed the `timestamp`  type here. Maybe we should also take the opportunity to make sure we're not missing any other type.

**Comment by jeffreyscarpenter** [comment]
Does this same change also need to be made on the bridge component? https://github.com/stargate/stargate/blob/v2.0.0/bridge-proto/src/main/java/io/stargate/bridge/grpc/Values.java
