### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#1490]
Rename the `master` branch to `main` for diversity and inclusion reasons.

**Comment by jeffreyscarpenter** [comment]
See also: https://github.com/stargate/stargate/discussions/1489

**Comment by tatu-at-datastax** [comment]
So, renaming as suggested (current `master` renamed as `v1`; current `v2.0.0` renamed as `main`) is what we plan to do. This will require local changes to Stargate project, as well as likely changes to C2 sister-project. This includes:

* [TO BE WRITTEN]

**Comment by jeffreyscarpenter** [comment]
@tatu-at-datastax I've created draft PRs for changes to docs and website to reflect these new branch names.

**Comment by tatu-at-datastax** [comment]
I added a separate google doc with details; unfortunately this requires changes to non-OSS parts as well so can't link from this issue.

**Comment by tatu-at-datastax** [comment]
Progress so far:

* `main` points to Stargate v2 (former `v2.0.0`)
* `v1` points to Stargate v1 (former `master`)

Yet to do:

* Change default branch to be `main` -- is currently `v1`

**Comment by tatu-at-datastax** [comment]
Change the default branch to be `main`, task completed.
