### ISSUE TITLE
Submit CSV to CQL

### ISSUE THREAD

**Issue by caniko** [stargate/stargate#1512]
Is it possible to [submit CSV](https://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useInsertCopyCSV.html) text along with delimiter and other options with Stargate REST?

Couldn't find anything in the docs.

**Comment by dougwettlaufer** [comment]
This isn't something currently supported but we do have https://github.com/stargate/stargate/issues/821 which is a similar issue. Also, any such batch operations would most likely be implemented as json rather than csv.

**Comment by caniko** [comment]
> Also, any such batch operations would most likely be implemented as json rather than csv.

Very sound logic :)
