### ISSUE TITLE
How to run a query (REST or GraphQL) with ALLOW FILTERING clause

### ISSUE THREAD

**Issue by rlebreto** [stargate/stargate#1513]
Hi everybody

Do you know when ALLOW FILTERING query will be allowed on REST or GraphQL query ?
We have some queries using it, and not having such a possibility is a blocking point.

Thx in advance.

PS : happy new year to everybody, and great thx to work you make !

**Comment by rlebreto** [comment]
Hi @dougwettlaufer 
Thanks a lot for the answer.

To be franc, I don't fell very confortable with this answer. According to me, it is not the role of stargate to define if a query if good or not.
Use an "ALLOW FILTERING" query can make sense in some cases (I will explain above why we do that...), and if cassandra engine  accept such a query, it is not logical that stargate does not allow it. What I mean is that, if ALLOW FILTERING should forbidden, then it should be rejected by cassandra and not by stargate 🤔

**Comment by tatu-at-datastax** [comment]
@rlebreto "According to me, it is not the role of stargate to define if a query if good or not."
I assume you mean "in my opinion ..." :)

One thing to note is that Stargate is not merely a thin proxy in front of Cassandra: it is a gateway with different APIs that may extend or limit access, add other ways to interact with Cassandra-backed storage. But there is nothing saying APIs should only do what Cassandra do, and allow everything Cassandra allows. This is not a definition of Stargate.

So the question of allowing or not of queries that require "ALLOW FILTERING" is something that APIs need to tackle.
Not allowing -- at least by default -- of such potentially wasteful queries, initially, makes sense as it is possible to loosen restrictions later on. The opposite is not true: something that is allowed is much more difficult to disallow in future.

To consider allowing such queries there are multiple things to consider. For example:

1. Should there be a global setting (per Stargate installation) to allow-always/disallow-always/allow-on-query -- and perhaps by API?
2. Should there be setting on per-query basis to allow filtering (assuming installation allows)
3. Or should specific queries of specific API allow it? (there are requests to allow non-primary key scans)

It seems most likely that allowing of such queries must have somewhat more granular settings: especially considering that some Stargate installations support multi-tenancy. In multi-tenant use case limitations are even more important to reduce impact across tenants.

**Comment by rlebreto** [comment]
Here is our use case.
Basically we have a table that stores messages beetwen users.
Tables has following fields :
- thread_id : text that contains a UUID generated on code side
- message_id : text that contains a incremental sequence generated on code side
- message_direction : 'sent' or 'received'
- message_content : text containing the message
- message_validation : 'pending', 'validated', 'not_validated'

PK is (thread_id, message_id) and messages are ordered by message_id DESC.

Messages are created on pending status. They are validated or unvalidated by an automate or if the automate is not able to make a decision, messages are validated in less than 1 hour by an operator. So pending is a very transient state and message_status are mainly (98%) validated.

So basic query is :
```
select * from messages where thread_id='XXXXXX' and message_status='validated' ALLOW FILTERING limit 50;
```
and to show the new 50 messages, query is :
```
select * from messages where thread_id='XXXXXX' and message_id>'last id of previous page' and message_status='validated' ALLOW FILTERING limit 50;
```
... and it works fine !

We do not separate messages by status because operators that have to validate pending messages must see all messages independantly of their status :
```
select * from messages where thread_id='XXXXXX' limit 50;
select * from messages where thread_id='XXXXXX' and message_id>'last id of previous page' limit 50;
```

Implemente something that transfere or duplicate messages for the 2 usages is very complidated. ALLOW FILTERING here is very fast because we stop the query with a LIMIT clause and because 98% of our messages are validated.

We proceed that for years without no performance issue on our cluster.
🤔

**Comment by rlebreto** [comment]
```
@rlebreto "According to me, it is not the role of stargate to define if a query if good or not."
I assume you mean "in my opinion ..." :)
```
@dougwettlaufer Sorry, I am not english native.

I understand many of your arguments but our usage is dedicated and not muti tenancy... I saw that some people proposed to enable ALLOW FILTERING with a global settings. If you have internal discussions about this, we are interested :-)

Thanks a lot from Paris/France

**Comment by ivansenic** [comment]
@rlebreto wouldn't an index on `message_status` be able to help you here?

**Comment by rlebreto** [comment]
HI @ivansenic and @tatu-at-datastax 
I did some tests with an index on message_validation_status. I am not sure that indexes can cover all our use cases but I did tests ;-)

Basically, it seems to works with graphQL but not with REST API (if my query is right).

```
cassandra@cqlsh:test_rlb> select * from messages ;

 thread_id | message_id | message_content | message_date                    | message_direction | message_type | message_validation_status
-----------+------------+-----------------+---------------------------------+-------------------+--------------+---------------------------
       AAA |        114 |      hello me 4 | 2022-01-12 13:03:28.902000+0000 |              sent |         null |                 validated
       AAA |        113 |      hello me 3 | 2022-01-12 13:03:21.852000+0000 |              sent |         null |             not_validated
       AAA |        112 |      hello me 2 | 2022-01-12 13:03:10.187000+0000 |              sent |         null |                 validated
       AAA |        111 |      hello me 1 | 2022-01-12 13:03:02.303000+0000 |              sent |         null |                 validated

(4 rows)

cassandra@cqlsh:test_rlb> select * from messages where thread_id='AAA' and message_validation_status='validated';

 thread_id | message_id | message_content | message_date                    | message_direction | message_type | message_validation_status
-----------+------------+-----------------+---------------------------------+-------------------+--------------+---------------------------
       AAA |        114 |      hello me 4 | 2022-01-12 13:03:28.902000+0000 |              sent |         null |                 validated
       AAA |        112 |      hello me 2 | 2022-01-12 13:03:10.187000+0000 |              sent |         null |                 validated
       AAA |        111 |      hello me 1 | 2022-01-12 13:03:02.303000+0000 |              sent |         null |                 validated

(3 rows)
```

With graphQL (OK) :
```
query get_thread_for_AAA {
    messages (value: {thread_id:"AAA",message_validation_status:"validated"}) {
      values {
      	thread_id
      	message_id
        message_content
        message_validation_status
      }
    }
}
```
returns
```
{
    "data": {
        "messages": {
            "values": [
                {
                    "thread_id": "AAA",
                    "message_id": "114",
                    "message_content": "hello me 4",
                    "message_validation_status": "validated"
                },
                {
                    "thread_id": "AAA",
                    "message_id": "112",
                    "message_content": "hello me 2",
                    "message_validation_status": "validated"
                },
                {
                    "thread_id": "AAA",
                    "message_id": "111",
                    "message_content": "hello me 1",
                    "message_validation_status": "validated"
                }
            ]
        }
    }
}
```

But REST API fails (KO) :
```
http://10.120.10.67:8082/v2/keyspaces/test_rlb/messages?where={"thread_id":{"$eq":"AAA"},"message_validation_status":{"$eq":"vallidated"}}

{
    "count": 0,
    "data": []
}
```

I think that the REST is fine because if I change criteria on message_validation_status with a criteria on message_id, it works fine :
```
http://10.120.10.67:8082/v2/keyspaces/test_rlb/messages?where={"thread_id":{"$eq":"AAA"},"message_id":{"$eq":"113"}}

{
    "count": 1,
    "data": [
        {
            "message_content": "hello me 3",
            "thread_id": "AAA",
            "message_date": {
                "nano": 852000000,
                "epochSecond": 1641992601
            },
            "message_id": "113",
            "message_type": null,
            "message_validation_status": "not_validated",
            "message_direction": "sent"
        }
    ]
}
```

**Comment by rlebreto** [comment]
Hi
Aftering discussing with some people knowing well cassandra, I think that the proposal using index is not a good solution.
Indexes are not recommanded when a column has a very low cardinality. As explain above, we only have 3 values for messages_status and "validated" is the principal one.
Here, the cardinality on my table :
```
+-------------------------+----------+
|message_validation_status|  count(1)|
+-------------------------+----------+
|            not_validated|   1122498|
|                validated|2146316686|
|                  pending|     43618|
+-------------------------+----------+
```
Some people recommended me to use a SASI index... but status of such a feature that has moved to "experimental" appears to us risky.

I will make a pause on my tests and see if position about ALLOW FILTERING can change in the future.
Thanks a lot to @ivansenic and @tatu-at-datastax.

**Comment by ivansenic** [comment]
@rlebreto Well, I know that this page states it differently -> https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useWhenIndex.html
