### ISSUE TITLE
How to run a query (REST or GraphQL) with "SELECT count(*)"

### ISSUE THREAD

**Issue by rlebreto** [stargate/stargate#1514]
Hi everybody

Also the same request as #1513 , but this time with "SELECT count(*) AS c". We use such query to get a counter before to drill down  on a next page.

Thx in advance.

**Comment by dougwettlaufer** [comment]
Aggregation functions are not currently supported in REST but they are in GraphQL.

The docs for count in GraphQL are still pending (https://github.com/stargate/docs/issues/117) but you can see some sample in the test [here](https://github.com/stargate/stargate/blob/master/testing/src/main/java/io/stargate/it/http/graphql/cqlfirst/AggregationFunctionsTest.java#L227)

**Comment by rlebreto** [comment]
Hi @dougwettlaufer 
thx a lot for your answer...
Indeed, what I wanted to do is :

```
query get_nb_thread_for_AAA {
    message (value: {thread_id:"AAA"}) {
      values {
      	c: _bigint_function(name: "count", args: ["message_id"])
      }
    }
}
```

It works for me. Thx a lot.
