### ISSUE TITLE
Support appending and deleting values from collections in GraphQL CQL-first API

### ISSUE THREAD

**Issue by marksurnin** [stargate/stargate#1522]
I was wondering if there are plans to add support for appending and deleting values from collections?

Perhaps the closest prior art is in https://github.com/stargate/stargate/issues/986 as the syntax for updating counters is similar.

**Comment by jeffreyscarpenter** [comment]
On which API are you looking for this feature? Thanks!

**Comment by marksurnin** [comment]
My bad, GraphQL CQL-first.

**Comment by jeffreyscarpenter** [comment]
The core team will likely need to look at this after we complete the Stargate v2 work. In the interim, if you want to elaborate on the desired syntax or take a shot at starting work on this let me know.

**Comment by marksurnin** [comment]
Sounds good, we can get around to this in a few weeks and we'll elaborate on the syntax then.
