### ISSUE TITLE
Support GraphQL queries without primary key(s)

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1525]
I would like to have a possibility to iterate all rows of a table in the GraphQL API using the page size and page state. I tried this for the schema-first and it was not working, however I guess that both schema-first and cql-first should allow this.

I tried making something like this and it was not working, schema update was declined with message all primary keys must be the parameters of the query.

```
type SelectBookResult @cql_payload { 
  data: [Book]
  pagingState: String
}

type Query {
  books(
    pagingState: String @cql_pagingState 
  ): SelectBookResult @cql_select(pageSize: 10) 
}
```

**Comment by tatu-at-datastax** [comment]
This is not allowed with REST API either, I think. Would there be any concerns about overall functionality allowed, and if so, should REST API also allow such scans for sake of consistency?

**Comment by ivansenic** [comment]
@tatu-at-datastax Are you sure, seems to me that [io.stargate.web.restapi.resources.v2.RowsResource#getAllRows](https://github.com/stargate/stargate/blob/01a6b5743136317afbdd00a358ce8a3a4ffe679e/restapi/src/main/java/io/stargate/web/restapi/resources/v2/RowsResource.java#L286) allows exactly that?

**Comment by tatu-at-datastax** [comment]
@ivansenic Doh. You are right, of course. There is that method. Not sure what I was thinking.
