### ISSUE TITLE
Number of rows returned from HTTP-based APIs is less than page size (there are a sufficient number of rows at the current position)

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#1544]
Example: Query with page size 2000 (REST, GraphQL), receive 1618 rows. Total number available rows at the current position is 315k+ so this should have returned 2000 rows.

It's possible that the query is exceeding some threshold (likely a DSE guardrail setting for the total max bytes) in the persistence layer causing it to return less rows than wanted. There are a couple ways to address this:

1) Keep paging in the APIs until we hit the intended target. However, this could cause coordinators to exceed their memory resources.
2) Return an error i.e. "Result set is too big use a smaller page size"
3) ...

First, we should verify that it is indeed a persistent threshold/guardrail causing the issue an not something else.

**Comment by mpenick** [comment]
To be clear this affects both REST and GraphQL APIs.

**Comment by ivansenic** [comment]
And does not affect Docs API as the page size in docs in handled differently and is related to the number of documents.
