### ISSUE TITLE
Allow users to createKeyspace with GraphQL

### ISSUE THREAD

**Issue by csplinter** [stargate/stargate#155]
Users need to be able to create keyspaces via the GraphQL API w/o having to cross over into another API (ie CQL).

This should be configurable such that a user can disable this functionality at runtime in the case that they want to restrict allowing this capability on a cluster.

**Comment by dougwettlaufer** [comment]
Why disable rather than handle it with db permissions? As in don't allow the user access to creating a keyspace in which case graphql will return an error about the user not being authorized?

**Comment by csplinter** [comment]
Using db permissions to enforce should work. @jorgebay any thoughts here as you looked at this in the Go-based implementation?

**Comment by jorgebay** [comment]
The golang graphql implementation had a bunch of flags that could be set when deploying to allow schema mutations and stuff like that. From the user POV, I think its nice to only be shown queries and mutations that can be executed but erroring out is clear enough.

I think it's a good idea to error out as part of this task. We can look at ways to disable/enable stargate features in the future using a built-in config mechanism.
