### ISSUE TITLE
Integration test failure in CI due to failure to connect to Docker engine

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1580]
(see #1567 for some context)

Failure 

```
Step #4 - "cassandra-3.11": ERROR [main] 2022-01-19 19:06:27,600 DockerClientProviderStrategy.java:208 - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
Step #4 - "cassandra-3.11": ERROR [main] 2022-01-19 19:06:27,600 DockerClientProviderStrategy.java:210 -     UnixSocketClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause IOException (native connect() failed : Permission denied)
Step #4 - "cassandra-3.11": ERROR [main] 2022-01-19 19:06:27,600 DockerClientProviderStrategy.java:212 - As no valid configuration was found, execution cannot continue
Step #4 - "cassandra-3.11": [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.417 s <<< FAILURE! - in io.stargate.it.cql.JwtAuthTest
Step #4 - "cassandra-3.11": [ERROR] io.stargate.it.cql.JwtAuthTest  Time elapsed: 30.417 s  <<< ERROR!
Step #4 - "cassandra-3.11": java.lang.reflect.InvocationTargetException
Step #4 - "cassandra-3.11": 	at io.stargate.it.cql.JwtAuthTest.buildParameters(JwtAuthTest.java:53)
Step #4 - "cassandra-3.11": 
```

causes occasional failures of 3 integration tests that rely on `testcontainers`.

Would be good to fix this problem.

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter found this article -- https://dhananjay4058.medium.com/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket-2e53cccffbaa --  which suggests a likely fix:

```
sudo usermod -a -G docker $USER
```

which for us means

```
usermod -a -G docker ubuntu
```

and should resolve the issue if it is due to lack of access.

**Comment by jeffreyscarpenter** [comment]
This is still broken.

**Comment by ivansenic** [comment]
The #1588 is adding ignore for the tests that depend on the test containers if docker is not available. This issue however must stay open until we sort this out. We can come to the situation where those three tests depending on the keycloak are not checked at all..

**Comment by tatu-at-datastax** [comment]
I am fine leaving this issue open for now, but alternatively I could create a new specific issue about testing of Keycloak integration (and just have ref to this issue) -- solution might be to rewrite tests to use different technique. If docker-in-docker approach cannot be made to work.

**Comment by jeffreyscarpenter** [comment]
This is no longer an issue.
