### ISSUE TITLE
unable to retrieve the data from cassandra node though Stargate API (REST API)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1598]
### Discussed in https://github.com/stargate/stargate/discussions/1595

<div type='discussions-op-text'>

<sup>Originally posted by **Madhusudanarao123** January 27, 2022</sup>
Hi Team,

we are unable to retrieve the data from cassandra node though Stargate API

Thanks & Regards,
Madhu

</div>

**Comment by Madhusudanarao123** [comment]
GCP level create 3 node cluster and separate vm install stargate, We are facing the issue like Stargate API server not able to communicating with Cassandra node for Retrieve data.

PFB details..

Versions:
OS : Centos 7
Stargate Version : 1.0.41
Cassandra Version : 4.0.1

Using Command

curl -s -L -X GET '{emp2}{users_keyspace}/{rkeyspace}/{rtable}?where={"firstname":{"$in":["sai","Madhu"]}}' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json"

Issue: command excuted sucessfully but output not showing

**Comment by Madhusudanarao123** [comment]
Team,
please help on this issue..

**Comment by ivansenic** [comment]
We can not help until you show us the full URL you are trying to call?

**Comment by Madhusudanarao123** [comment]
[STARGATE GATEWAY.docx](https://github.com/stargate/stargate/files/8029772/STARGATE.GATEWAY.docx)

we are trying above document commands every command working fine expect GET DATA command. please find the attachment and do need full..

PFB details..

Versions:
OS : Centos 7
Stargate Version : 1.0.41
Cassandra Version : 4.0.1

Using Command

curl -s -L -X GET '{emp2}{users_keyspace}/{rkeyspace}/{rtable}?where={"firstname":{"$in":["sai","Madhu"]}}' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json"

Issue: command excuted sucessfully but output not showing

**Comment by ivansenic** [comment]
Your column is called `name` and you are searching for the `firstname`. :arrow_down: 

`curl -s -L -X GET '{emp2}{users_keyspace}/{rkeyspace}/{rtable}?where=\{"firstname":\{"$in":\["sai","Madhu"\]\}\}' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json"`

![image](https://user-images.githubusercontent.com/10600041/153839829-2f032f23-d065-4a61-bbc5-6034e3d43e4b.png)

**Comment by Madhusudanarao123** [comment]
Team i am excuted the below table only.
Keyspace name: users_keyspace
Table name : emp2
![image](https://user-images.githubusercontent.com/98576386/153978468-1aeac495-67d8-4141-8391-062bb4ce1de7.png)

**Comment by ivansenic** [comment]
Can you hit the command like below, but without any variables, substitute `{emp2}{users_keyspace}/{rkeyspace}/{rtable}` with real path. Note the `-v` after the `curl` please..

`curl -v -s -L -X GET '{emp2}{users_keyspace}/{rkeyspace}/{rtable}?where=\{"firstname":\{"$in":\["sai","Madhu"\]\}\}' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json"`

**Comment by ivansenic** [comment]
Just tried the same request on my machine and it works fine:

```
$ curl -v -s -L -X GET 'http://127.0.0.4:8082/v2/keyspaces/docs_search/products?where=\{"key":\{"$in":\["41613e59-5726-4240-84fb-31367ff35fc2","Madhu"\]\}\}' -H "X-Cassandra-Token: ff0b0f1b-8084-492b-9076-ac2d26a2f0d2" -H "Content-Type: application/json"
*   Trying 127.0.0.4:8082...
* TCP_NODELAY set
* Connected to 127.0.0.4 (127.0.0.4) port 8082 (#0)
> GET /v2/keyspaces/docs_search/products?where={"key":{"$in":["41613e59-5726-4240-84fb-31367ff35fc2","Madhu"]}} HTTP/1.1
> Host: 127.0.0.4:8082
> User-Agent: curl/7.68.0
> Accept: */*
> X-Cassandra-Token: ff0b0f1b-8084-492b-9076-ac2d26a2f0d2
> Content-Type: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 15 Feb 2022 09:24:48 GMT
< Content-Type: application/json
< Vary: Accept-Encoding
< Content-Length: 4182
< 
{"count":6,"data":[....]}
````

Please recheck the path you are trying to execute. Or give the output with `-v`.

**Comment by ivansenic** [comment]
@Madhusudanarao123 Any updates, can I close the issue or not yet?

**Comment by Madhusudanarao123** [comment]
still issue not resolved, alternatively working in java code and  spyspark side checking for resolution.

**Comment by tatu-at-datastax** [comment]
No updates for over a year, no new info, closing.
