### ISSUE TITLE
`@IfBundleAvailable` does not support nested tests classes

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1649]
The JUnit condition `BundleAvailableCondition` is not working with the nested test classes. Seems this is only used for gRPC test at the moment. I guess it was added once `grpc` modules were not in the default profile.

We can delete it or fix as this can be a valuable test util in the future.

**Comment by tatu-at-datastax** [comment]
While not against fix, I think maybe we should delete this usage altogether if and when this is OSGi-specific functionality -- for SGv2 we would not be using this anyway, correct? And we are not planning on adding new services on SGv1 that would be needing this, now that grpc is included by default.

**Comment by ivansenic** [comment]
Let s fix now and remove later on. I am also pro removing.

**Comment by tatu-at-datastax** [comment]
SGTM!
