### ISSUE TITLE
Metrics for non-API endpoints should be reported as different module

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1660]
Currently we have a set of the health and utility endpoints in each module. The metrics for those endpoints should not be recorded with module tag that is same as the module where they are existing. With this we want to have a clear aggregated metric views on the real API endpoints, without interference of those utility endpoints.

The endpoints are:

* *restapi*
   * `^root$`
   * `^/health$`
   * `^/swagger.*`
* *graphqlapi*
   * `^/playground$`
   * `^/graphql-schema$`

**Comment by tatu-at-datastax** [comment]
Sounds good to me.
