### ISSUE TITLE
What fields should my JWT define?

### ISSUE THREAD

**Issue by caniko** [stargate/stargate#1674]
**First:**
I have an authentication server that generates JWTs, and I would like to use it for authentication in StargateAPI. I couldn't find an explicit outline of fields that the JWT needs to store in the docs. What are these fields?

**Second:**
I am interested in implementing row-based permission for modification, and I would like to avoid creating roles in CQLSH, and do it purely over JWTs. The logical operation is simple: if the owner ID (table column) is not identical to the user ID (on the JWT) the client has no modication rights, but can still read the row. I believe at least some devs to be interested in this topic, it should be mentioned.

The authentication documentation should focus on defining/outlining more key concepts, including these.

**Comment by polandll** [comment]
This issue should be opened  at github.com/stargate/docs/issues, since it is a documentation issue, not a code issue.
@caniko, if you wish to follow the issue, could you do that?
