### ISSUE TITLE
Values.byteBuffer returns an empty buffer

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1676]
In [Values](https://github.com/stargate/stargate/blob/master/grpc-proto/src/main/java/io/stargate/grpc/Values.java#L232-L238):
```java
  public static ByteBuffer byteBuffer(Value value) {
    checkInnerCase(value, InnerCase.BYTES);

    ByteBuffer bytes = ByteBuffer.allocate(value.getBytes().size());
    value.getBytes().copyTo(bytes);
    return bytes;
  }
```

This does not reset the position after copying, resulting in an empty buffer.

Fix:

```java
  public static ByteBuffer byteBuffer(Value value) {
    checkInnerCase(value, InnerCase.BYTES);

    return value.getBytes().asReadOnlyByteBuffer();
  }
```

**Comment by olim7t** [comment]
Related: `Values.of(ByteBuffer)` "consumes" its argument (i.e. modifies the position marker).
This seems counter-intuitive to me, maybe it would be better to duplicate to leave the makers unchanged. Either way this should be documented.

**Comment by tatu-at-datastax** [comment]
Agreed that `Values.of(ByteBuffer)` returning seemingly empty buffer seems wrong to me as well.

With this change it might make sense to also see if some callers were already working around this issue? (I vaguely recall there being an older REST API issue that sounds similar). And if so, work-around(s) could be removed.
