### ISSUE TITLE
Unify configuration in Stargate v2 services

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1694]
Currently we have a mix of different approaches:
- command-line arguments managed with the "airline" library, for example in `RestServiceStarter`
- Dropwizard options, for example `sgv2-restapi/src/main/resources/config.yaml`
- system properties loaded at random places in the code, for example `BridgeConfig.ADMIN_TOKEN` (this one is mine, but there are others in the v1 code)

We should centralize options in one place. I think command-line arguments is the best place, as they are documented and easy to find.

**Comment by jeffreyscarpenter** [comment]
This is addressed by other issues/PRs that migrated GraphQL and REST APIs to Quarkus framework.

#1892 
#1980
