### ISSUE TITLE
GraphQL mutations do not respect camelCase definitions

### ISSUE THREAD

**Issue by polandll** [stargate/stargate#176]
So, explorations with alterTableAdd() and alterTableDrop() using a column called either "publishYear" or "publish_year" show that "publishYear" is changed to "publishyear". Here are mutations to test:

```graphql
mutation createLibraryTables {
  books: createTable(
    keyspaceName:"library", 
    tableName:"books", 
    partitionKeys: [ # The keys required to access your data
      { name: "title", type: {basic: TEXT} }
    ]
    values: [ # The values associated with the keys
      { name: "author", type: {basic: TEXT} }
      { name: "genre", type: {basic: TEXT}}
    ] 
  )
}
# alter the books table to add another column "publishYear" of data type INT
mutation alterTableAddPUBLISHYEAR {
  alterTableAdd(
    keyspaceName:"library",
    tableName:"books",
    toAdd:[{
      name: "publishYear",
      type: {
        basic: INT
      }
    }
    ]
  )
}
# alter the books table to delete that column
mutation alterTableDropPUBLISHYEAR {
  alterTableDrop(
    keyspaceName:"library",
    tableName:"books",
    toDrop:[ "publishYear"]
  )
}
# alter the books table to add another column "publish_year" of data type INT
mutation alterTableAddPUBLISH_YEAR {
  alterTableAdd(
    keyspaceName:"library",
    tableName:"books",
    toAdd:[{
      name: "publish_year",
      type: {
        basic: INT
      }
    }
    ]
  )
}
mutation alterTableDropPUBLISH_YEAR {
  alterTableDrop(
    keyspaceName:"library",
    tableName:"books",
    toDrop:[ "publish_year"]
  )
}
```

**Comment by denisekgosnell** [comment]
+1 on this.

The attached screen shots show how this is showing up for me.

In one of the images, we can see that the database reports the schema is `published_year`.

However, the mutations force me to use `publishedYear`.

As a user, I would expect my mutations to expose the schema as stored in the DB.

<img width="1792" alt="Screen Shot 2020-09-30 at 3 20 47 PM" src="https://user-images.githubusercontent.com/8419869/94733933-7d493880-0336-11eb-8350-ce272f4c0929.png">

<img width="1792" alt="Screen Shot 2020-09-30 at 3 20 56 PM" src="https://user-images.githubusercontent.com/8419869/94733936-7de1cf00-0336-11eb-90ca-a251b27d8386.png">

**Comment by polandll** [comment]
I see that this issue is related to #119.

**Comment by olim7t** [comment]
This also applies to the table name itself:
```graphql
mutation {
  createTable(
    keyspaceName: "test"
    tableName: "userActivity"
    partitionKeys: [{ name: "author", type: { basic: TEXT } }]
  )
}
```
Produces:
```
cqlsh:test> desc tables;

useractivity
```
