### ISSUE TITLE
Separate CI images

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1768]
Currently there is a single image that is used when running the CI. It's used for all C* version and DSE. However, it's like 5GB in size. this is because all target versions are initialized using the CCM.

We could optimize this by creating a dedicating images for each C* target versions. We would get way smaller images, that are easier to update and less heavy when needed to be downloaded in the CI running nodes.

```
gcr.io/stargateio/stargate-builder            v1.0.6                         99fc860aee88   3 months ago     4.63GB
gcr.io/stargateio/stargate-builder            v1.0.7                         5c666d75c516   19 minutes ago   5.13GB
```

**Comment by jeffreyscarpenter** [comment]
@ivansenic We can probably close this since we're migrating away from using GCB, right?

**Comment by ivansenic** [comment]
Yes, and even if we would not move, I am not sure if it really pays off to invest here.
