### ISSUE TITLE
Decouple Bridge from gRPC service

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#1770]
The Stargate v2 Bridge module is currently constructed as an extension of the gRPC module

- The bridge proto files are part of the `grpc-protos` module
- The bridge implementation reuses classes from the gRPC implementation

This coupling has had some benefits in terms of enabling us to bootstrap the bridge quickly, but also some undesirable side effects:

- on multiple occasions we have had to consider carefully changes we want to make to the bridge that actually require changes to classes in the gRPC module, potentially changing behavior for public API users
- under #1763 we're potentially making changes to the gRPC protos for behavior we want to add to the bridge. Even though these would be non-breaking changes to our public API, they are still changes, and we'd need to consider downstream impacts on documentation, etc.
- we've had at least one defect that is arguably caused by bridge changes impacting gRPC behavior in downstream projects (see https://github.com/riptano/c2/issues/453 where the bridge appears to be impacting gRPC metrics reporting)

We should consider making a clean break between these two modules with separate protos and separate implementations.

**Comment by ivansenic** [comment]
I am just afraid now how can we revert anything in the #1763 once it becomes the public API?

**Comment by jeffreyscarpenter** [comment]
> I am just afraid now how can we revert anything in the #1763 once it becomes the public API?
> 
> EDIT: OK, I forgot this is in V2 branch.

Agree, while v2 is still Alpha I think we are ok, but we do need to resolve sooner rather than later.

**Comment by olim7t** [comment]
I've started working on this. No blockers, but as expected almost all of the `grpc` module will now be duplicated in `bridge`.

Also I have to move the generated proto code for the bridge to a different package (technically because the `testing` module uses both, but also it makes sense conceptually). So all of v2 code that uses the bridge will be impacted.

**Comment by tatu-at-datastax** [comment]
@olim7t Can this be closed now?
