### ISSUE TITLE
Add Docs as source API in V2

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1786]
We should extend the protos and add Docs as an additional source API.

@olim7t Any chance you can quickly tackle this, should be easy for you.

**Comment by olim7t** [comment]
It's not as simple as adding a constant: the gRPC enum maps to `io.stargate.auth.SourceAPI` in the `authnz` module. In v1 the docs API is using `REST`. If we add a separate constant, there will probably also be impacts in authorization backends.

**Comment by ivansenic** [comment]
@olim7t So should we actually go all the way and add this as a new constant? Sure for now we can simply use the `REST` as up until now, but in long term should we split this? Is this being recorded in some type of auditing logs?

**Comment by olim7t** [comment]
It's not only used for logging, I think it's also an integral part of permission definitions. For example a token might be authorized to do certain operations via the GraphQL API, but not via the Documents API.

Adding the new constant to Stargate is a couple of lines of code. But the other aspect is whether the authorization service will understand what the constant means. Admittedly that's more of a deployment concern (Astra in our case), so maybe we should move the conversation to a private channel.
