### ISSUE TITLE
Bridge get supported features should be available without C* token

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1821]
Executing the get suported features on the bridge should not require the Cassandra token. Not only that the C* auth does not make sense here, it also disables any one-time initialization process on the startup. The auth interceptor should not require the token in this case.

**Comment by ivansenic** [comment]
@olim7t would you agree?

**Comment by olim7t** [comment]
I agree in principle, however disabling auth for a particular operation is cumbersome. I had to do it in a previous version of the code (when the schema cache used notifications IIRC), the only way I found was to test the operation name in `NewConnectionInterceptor`.

What I do instead in the `sgv2-service-common` client is memoize the response the first time it's invoked, see https://github.com/stargate/stargate/pull/1820.

**Comment by ivansenic** [comment]
> I agree in principle, however disabling auth for a particular operation is cumbersome. I had to do it in a previous version of the code (when the schema cache used notifications IIRC), the only way I found was to test the operation name in `NewConnectionInterceptor`.
> 
> What I do instead in the `sgv2-service-common` client is memoize the response the first time it's invoked, see https://github.com/stargate/stargate/blob/v2.0.0/sgv2-service-common/src/main/java/io/stargate/sgv2/common/grpc/DefaultStargateBridgeClient.java#L290-L303.

I know, but we depend on the set of the startup initializations, that we would otherwise need to do lazy and pass this all over the place. I know it s  cumbersome, but tests should be there to confirm correctness.

For now we have a workaround to not get the features from the bridge at all, but would be nice to have this in.

**Comment by olim7t** [comment]
> I had to do it in a previous version of the code

Actually the use case was not creating the connection. Here's the revision:
https://github.com/stargate/stargate/blob/3dde9d504db2cdd0c49037ca107728fa244b66e6/grpc/src/main/java/io/stargate/grpc/service/interceptors/NewConnectionInterceptor.java#L136-L139

> we would otherwise need to do lazy and pass this all over the place

Yeah I think I see what you mean. I'll give it a quick try.

**Comment by ivansenic** [comment]
I am certain this was fixed already in #1822.
