### ISSUE TITLE
Add instrumentation to SGv2 REST API for measuring timing and reporting timing breakdown

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1828]
As part of on-going performance analysis of Stargate v2 REST API (and eventually other APIs), it makes sense to add a mechanism that collects timing over specific tasks of request processing. Parts like:

* Input processing
* Schema access
* DB Read access
* DB Write access
* Output processing

(note that not all requests do all of above; also note that order of some operations also vary)

Timing of these should always be collected and used to update simple (dropwizard) Metrics objects (Timers likely) but also optionally logged to output (disabled by default but enabled by a System property) for more manual analysis.
Overhead of collection and DW metrics should not add measurable overhead; logging could and is therefore only enabled when requested.

**Comment by ivansenic** [comment]
Imo you should use Micrometer and not Dropwizard metrics objects.

**Comment by tatu-at-datastax** [comment]
@ivansenic Right now SGv2 REST and Graphql services use DWM so exposing those is quite natural and seems reasonable.
But I have tried to encapsulate use in a way that it will be easy to convert when the rest of processing moves to Micrometer. I suspect that timers, counters and meters have very similar APIs anyway.

**Comment by tatu-at-datastax** [comment]
No current plans to merge related PR; leaving issue itself open for now.

**Comment by tatu-at-datastax** [comment]
Will not implement in this form, closing.

**Comment by ivansenic** [comment]
@tatu-at-datastax can we actually do this using tracing now that everybody is on Quarkus? I would propose we have a ticket that actually adds proper tracing to all services, so we can actually use when needed.
