### ISSUE TITLE
Add instrumentation to SGv2 Schema Cache

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1829]
As part of on-going performance analysis of Stargate v2 REST API (and eventually other APIs), it will be useful to start collecting and exposing basic metrics of our caching Schema access used by APIs such as REST API.
Basic metrics like:

1. Call frequency (total cache lookups), with 1/5/15 minute rate
2. Hits, misses, to calculate hit ratio: expose at least one dynamic rate (5 or 15 minute)
3. Timing of cache loads

should be collected and exposed via simple Metrics (dropwizard at first, could be micrometer etc later on).
This can be achieved using `Caffeine.newBuilder().recordStats(....)`.

The idea is that these metrics allow both analysis during performance testing and may give an idea of cache hit rates during operation (operational metrics), without adding measurable overhead of its own.

**Comment by ivansenic** [comment]
Note that `sgv2-docsapi` already collects and exposes this metric.

**Comment by tatu-at-datastax** [comment]
@ivansenic ok that's good to know. Which classes are involved? I can have a look to see to get ideas.

**Comment by ivansenic** [comment]
@tatu-at-datastax Unfortunately, it's OOX feature: https://github.com/stargate/stargate/blob/94809e6d3e36a77b82ce3bccbbd40d127c031c4b/sgv2-docsapi/src/main/resources/application.yaml#L58-L65

But I gave some suggestions in #1834

**Comment by tatu-at-datastax** [comment]
Ok, I think this probably should not be pursued now; I did have changes to add metrics but since it is not immediately needed, and may make more sense in context of later conversion, no need to work on this right now before there's a use case -- I was able to verify that caching itself works as expected (practically all schema lookups did in fact come from cache).

**Comment by tatu-at-datastax** [comment]
Closing for now, can tackle with Quarkus conversion, or if there is specific need before that.
