### ISSUE TITLE
Prepared statement metadata is not refreshed when the table gets altered

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#184]
Possibly lower priority because this is specific to protocol v5, which is still beta.

In Cassandra 4 / protocol v5, prepared `SELECT *` statements should automatically adjust if the table structure changes. It doesn't seem to work with Stargate: the prepared id stays the same, and the result set definition doesn't change.

See `PreparedStatementAlterTableTest` in #169.

**Comment by jeffreyscarpenter** [comment]
can't repro
