### ISSUE TITLE
Update Stargate "org.json" dependency version

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1848]
Looks like there is a CVE reported against version of `org.json` dependency Stargate has.
So let's upgrade version from `20190722` to `20220320` (latest).

**Comment by ivansenic** [comment]
This work in #1849 is not enough. This dependency is pulled from the `com.datastax.oss:java-driver-core@4.13.0`: See:

```
Introduced through: io.stargate.db:persistence-api@1.0.56 › com.datastax.oss:java-driver-core@4.13.0 › com.esri.geometry:esri-geometry-api@1.2.1 › org.json:json@20090211 
```

**Comment by ivansenic** [comment]
@tatu-at-datastax Or I am wrong?

**Comment by ivansenic** [comment]
I am wrong. It's moved to main pom..
