### ISSUE TITLE
Improve Docs API V1 documentation exposed in Swagger

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1858]
As we are working on Docs API V2, we noticed some inconsistencies in V1 between API and the exposes documentation. We will solve this in V2, but want to back-port the fixes to the V1. 

Some of already noticed issues:

* namespace get all is not documented to return an array
* collection get all is not documented to return an array
* request bodies are not always documented with examples that would showcase the difference (like `SimpleStrategy` vs `NetworkTopologyStrategy` when creating a namespace)
* examples that return `ApiError` are generic and always the same, we should provide more examples for different failure types

**Comment by ivansenic** [comment]
cc @polandll

**Comment by polandll** [comment]
Yes, thanks for the heads-up. Sounds like some cleanup is definitely required.

**Comment by jeffreyscarpenter** [comment]
Agree, closing
