### ISSUE TITLE
Consider optimistic handling of schema metadata

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1873]
Stargate services often use the following pattern:
- get the schema metadata, for example with `StargateBridgeClient.getKeyspace()`
- build a DML query based on this schema
- execute that query

The current implementation of `getKeyspace()` (v2.0.0-ALPHA-11) uses a cache, but it sends a background gRPC query to check that the metadata is still up to date. We use `DescribeKeyspaceQuery.hash` to optimize the happy path when nothing has changed (by sending an empty response), but that's still an extra network hop.

We could save that call with an optimistic approach:
- the client builds its query based on its current version of the metadata
- it sends the query, keyspace name and keyspace hash to the bridge
- if the hash is up to date, the bridge returns the response
- otherwise:
  - the bridge sends a special response that contains the new keyspace metadata
  - the client rebuilds the query based on the new metadata, and retries
  - the client updates its cache

This retry process could be abstracted behind a new `StargateBridgeClient` method:
```java
Response executeQuery(String keyspaceName, Function<CqlKeyspaceDescribe, Query> query)
```

As a first step, we can implement a dummy version of that method (based on the current ones, no actual retries) and evaluate the impacts on the service code:
- do all cases fit the trivial scenario above?
- how does it affect readability?
- do we also need this for batches? (probably for docs)

Then we can add the actual implementation, which will require a new gRPC call.

**Comment by ivansenic** [comment]
What would the "failing" case look like then and how would the users of the client recover from the situations where the schema did change? Seems like in all cases where the execute query is called, it would require such a retry scenario?
