### ISSUE TITLE
CI for V2 broken with `RestApiv2SchemaTest.keyspaceCreateWithExplicitDC`

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1879]
Fails for all C* versions.. Examples:

* https://console.cloud.google.com/cloud-build/builds/30e3c134-5c29-49b7-a35a-bde87b1e6b3d?project=stargateio
* https://console.cloud.google.com/cloud-build/builds/cb575844-465e-414e-ba82-ebb3e374da4d?project=stargateio

**Comment by ivansenic** [comment]
Not sure what really caused the issue, but I am seeing:

```
ERROR [main] 2022-06-09 14:38:55,002 RestUtils.java:303 - {"description":"Malformatted JSON payload ({\"name\":\"ks_createkeyspace_1654778334996\",\"datacenters\":[{\"name\":\"dc1\",\"replicas\":1}]}) for Keyspace creation, problem Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.String,java.lang.Integer>` from Array value (token `JsonToken.START_ARRAY`)\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.stargate.sgv2.restsvc.resources.schemas.SchemaBuilderHelper$KeyspaceCreateDefinition[\"datacenters\"])","code":400}
```

and seems that payload does not match the `KeyspaceCreateDefinition` java class:

```
  @JsonIgnoreProperties(ignoreUnknown = true)
  static class KeyspaceCreateDefinition {
    public String name;
    public int replicas = DEFAULT_REPLICAS_FOR_SIMPLE;
    public Map<String, Integer> datacenters;
  }
}
```
as `datacenters` prop is `"datacenters":[{"name":"dc1","replicas":1}]`

**Comment by ivansenic** [comment]
Can we also do something about ensuring that no merge is actually happening on the `v2.0.0` branch without running the CI. We should not push stuff to `v2.0.0` manually. 

It's also problematic that same tests passes in V1, but not V2.

**Comment by tatu-at-datastax** [comment]
@ivansenic merging this way was intentional, as I wanted to add the test wrt regression for V1 while then fixing handling in V2. Unfortunately fix takes longer.

The actual issue is #1817 so will close this one as duplicate.
