### ISSUE TITLE
Type check in ExternalStorage#supportsParameter is too permissive

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#188]
Not an issue currently, but I ran into this on a temporary local branch.

```java
  @Override
  public boolean supportsParameter(
      ParameterContext parameterContext, ExtensionContext extensionContext)
      throws ParameterResolutionException {
    return parameterContext.getParameter().getType().isAssignableFrom(ClusterConnectionInfo.class);
  }
```
According to the API contract, this will match if the parameter type "is either the same as, or a superclass or interface of" `ClusterConnectionInfo`. In other words the connection info will be injected into any `Object` parameter.

This is too permissive: if you have parameterized tests, it's possible that one of them could use an `Object` parameter. Either explicitly, or via erasure if the test method is parameterized (that's how I ran into it, I can provide an example if this is not clear).

If Junit finds two parameter resolvers that handle the same type, it throws an exception.

I think exact equality would be sufficient in this case, `Cluster` is private so we know it can't be referenced from a test class:
```java
return parameterContext.getParameter().getType() == ClusterConnectionInfo.class;
```

**Comment by jeffreyscarpenter** [comment]
can't repro
