### ISSUE TITLE
CCM command on mac issues

### ISSUE THREAD

**Issue by mthahir** [stargate/stargate#19]
CCM start gives the following message:
Library/Python/2.7/site-packages/ccm-2.8.3-py2.7.egg/ccmlib/cluster_factory.py:21: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
/Library/Python/2.7/site-packages/ccm-2.8.3-py2.7.egg/ccmlib/node.py:128: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
[node1 ERROR] intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
Improperly specified VM option 'ThreadPriorityPolicy=42'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by dougwettlaufer** [comment]
Hi @mthahir you might want to try upgrading your ccm version, it looks like 3.1.5 is the latest. If that doesn't help you might want to try filing an issue at https://github.com/riptano/ccm, they should be able to get you up and running much faster than I would.
