### ISSUE TITLE
Integration test `it.test=io.stargate.it.bridge.SchemaTest#describeKeyspace` can fail the `isCustom()` index check

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#1919]
This [check](https://github.com/stargate/stargate/blob/v2.0.0-ALPHA-14/testing/src/main/java/io/stargate/it/bridge/SchemaTest.java#L86) can fail when "CREATE INDEX"  (not custom) uses a custom implementation (SASI, or SAI) by default. 

We might consider eliminating this check or checking the persistence backend to see if it's using SAI, or SASI for secondary indexes.

**Comment by mpenick** [comment]
This hypothetical at this point. I'm not sure if this fully the case and is just a guess.

**Comment by tatu-at-datastax** [comment]
Maybe @olim7t has an idea of what is the best way to go here?

**Comment by tatu-at-datastax** [comment]
Closed as not planned.
