### ISSUE TITLE
Consider alternative setup for sgv2-quarkus-common test JAR

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1976]
In #1965 we generate a Maven "test-jar" from sgv2-quarkus-common. Test JARs generally don't work well in reactor builds (e.g. you need to `mvn install` first before running the tests of `sgv2-docsapi`).

Maybe we should have a separate `sgv2-quarkus-test-common` that is a regular module:
```
sgv2-quarkus-common <--- sgv2-quarkus-test-common <--- sgv2-docsapi
```
This also means moving some tests out of `sgv2-quarkus-common` to avoid a circular dependency, but we can put them in `sgv2-quarkus-test-common`.

**Comment by ivansenic** [comment]
@olim7t So close this as not done?

**Comment by olim7t** [comment]
Actually not a problem.
