### ISSUE TITLE
Implement optimistic bridge queries in `sgv2-quarkus-common`

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#1977]
Original non-Quarkus version: #1876.
We need to do the same in the `sgv2-quarkus-common` module introduced in #1965.

Note that only the REST API uses optimistic queries at the moment. So:
- if the REST API uses `sgv2-quarkus-common/src/main/java/io/stargate/sgv2/api/common/grpc/StargateBridgeClient.java`, then it needs to be done there (there is a TODO in `StargateBridgeClientImpl`).
- if the REST API uses the Mutiny gRPC API directly, then it needs to be done at that level, and the method can be removed in the interface above.

**Comment by ivansenic** [comment]
I would advise that `StargateBridgeClient` is not used and that eventually we remove this when possible.. Another layer on top what's already provided imo..

**Comment by tatu-at-datastax** [comment]
I guess it's the question of how much work is done by `StargateBridgeClient` in helping with retries, caching, processing (if any) of bridge datatypes. So if there is no value add, sure, no need add layers.

**Comment by ivansenic** [comment]
I guess `StargateBridgeClient` is mixed of functionality exposed by the auto-generated `StargateBridge` and `SchemaManager` atm..
