### ISSUE TITLE
Add tests for REST API to verify correct handling of `OverloadedException`

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1978]
(note: continuation from #1972 which was wrt Docs API)

When getting `OverloadedException` from persistence, REST API should translate this to HTTP response code 429.
If not explicitly handled will likely result in a 500 error instead; the problem being that client cannot react properly.
It is not clear if the current handling is correct since there do not seem to be tests to verify this.
We should add at least one test for one of REST API endpoints.

**Comment by ivansenic** [comment]
@tatu-at-datastax is this done?

**Comment by tatu-at-datastax** [comment]
@ivansenic No. If there's a test to copy/modify, would be nice to do.
