### ISSUE TITLE
gRPC Dart client

### ISSUE THREAD

**Issue by caniko** [stargate/stargate#2005]
As a flutter app developer, I would love to have Dart client for Stargate gRPC

**Comment by mpenick** [comment]
Stargate is not well suited for client-side application with its current APIs.

**Comment by caniko** [comment]
I disagree, the JWT is excellent for this

**Comment by mpenick** [comment]
> I disagree, the JWT is excellent for this

**Comment by caniko** [comment]
Yes! Exactly :)

**Comment by caniko** [comment]
I believe writes are also OK, considering you setup your `stargate-claims` [correctly](https://github.com/stargate/docs/issues/201#issuecomment-1108851023).

Any chances of this being implemented?
