### ISSUE TITLE
Revisit `ClientMetrics` in CQL module

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2016]
Looking into the `ClientMetrics` metrics in the CQL module, there are few things that needs to be clarified:

* Is `RequestDiscarded` correctly being invoked only when `connection.isThrowOnOverload()` is `true`
* Is `RequestProcessed` metric needed, it's not existing anymore in C* `4.x`
* Why is the `AuthSuccess` always zero for us, we do get `AuthError` and `AuthFailure`, but success is always zero?
* Should `AuthChallendge` be also included in order to get total amount of auth requests

**Comment by ivansenic** [comment]
@mpenick Can we have a look into this together once you are back?

**Comment by mpenick** [comment]
We ported the CQL module from some early version of C* 4.0. I'd have to dig into why each of those metrics is broken or wrong in some way. Maybe it's good to revisit this as part of merging in the latest transport code when doing https://github.com/stargate/stargate/issues/770.
