### ISSUE TITLE
Tracing is enabled client-side by default?

### ISSUE THREAD

**Issue by tlasica** [stargate/stargate#203]
In the stargate logs we can can see tons of
```
INFO  [ScheduledTasks:1] 2020-10-06 09:39:56,592 MessagingService.java:1246 - _TRACE messages were dropped in last 5000 ms: 70489 internal and 0 cross node. Mean internal dropped latency: 0 ms and Mean cross-node dropped latency: 0 ms
```
when putting system under some stress.

I wonder if maybe communication with backend has tracing enabled by default or maybe some other misconfiguration is the root cause here.

**Comment by jeffreyscarpenter** [comment]
Unable to reproduce
