### ISSUE TITLE
Unify developer docs for Quarkus-based APIs

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#2052]
The [Docs API README](https://github.com/stargate/stargate/blob/v2.0.0/apis/sgv2-docsapi/README.md) contains useful information about running the application and integration tests.

This will (hopefully) be similar for the REST and GraphQL APIs once they are migrated to Quarkus, so we should pull that information up in `apis/README.md`.

**Comment by ivansenic** [comment]
Did some work here lately, but this still need finalizing.
