### ISSUE TITLE
Enable gRPC Server Reflection to help with API Consumer on-boarding

### ISSUE THREAD

**Issue by kevinswiber** [stargate/stargate#2068]
To help API Consumers on-boarding to Stargate's gRPC service, it would be helpful to enable gRPC Server Reflection.  This allows client tools to pull the proto files at runtime.  More info here: https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md#enable-server-reflection.

This came up while exploring Stargate's gRPC service using Postman.  Server Reflection offers a much faster time to first API call, especially among developers new to gRPC.

**Comment by prabhatjha** [comment]
Thank you Kevin for your interest. One of Stargate engineers will follow up asap. Looking forward to more engagement from you and Postman community. :)

**Comment by ivansenic** [comment]
There is a PR for this: https://github.com/stargate/stargate/pull/1853
