### ISSUE TITLE
GraphQL: Improve error messages

### ISSUE THREAD

**Issue by csplinter** [stargate/stargate#207]
The error messages for the GraphQL API do not give enough context to the user to be able to troubleshoot or figure out what they should fix. We should enumerate common error cases and ensure that we have thorough error messages for them.

For example, if you run a mutation that is not supported:
```
mutation {
  createKeyspace(
    name:"library", 
    dcs: { name:"dc1", replicas: 1 } 
  )
}
```

The only response is
```
{
  "data": null
}
```

TODO: fill in more examples

**Comment by jorgebay** [comment]
I was experiencing the same thing while troubleshooting another issue... we should address this asap.
