### ISSUE TITLE
Unify default port value for SGv2 HTTP APIs

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2084]
In Stargate v1, different http APIs had to have different port numbers as they were all run on Coordinator nodes.
With Stargate v2 this is no longer necessary as they are run independently, not co-located.
But right now we still mostly use different port numbers as defaults (except for GraphQL) ; while this works it can be confusing to developers as this is different from the common pattern of simply using "default" port number of 8080 and letting Docker mapping be used when deploying to change that.

So we should probably change this for SGv2. If we do that, small (?) changes are needed to existing deployment definitions, startup scripts.

Current port numbers for SGv2 are:

* Docs API: 8180
* GraphQL API: 8080
* REST API: 8082

**Comment by jeffreyscarpenter** [comment]
IMO the gains of consistency are outweighed by the potential confusion and downstream work this change could cause.

**Comment by tatu-at-datastax** [comment]
Will discuss with team, weigh pros and cons and decide what is the final word wrt Stargate V2, default port numbers.
Most deployments will override defaults anyway, but we want documentation to be fully aligned & not keep changing things.

**Comment by ivansenic** [comment]
What's the proposal? I see two options:

1. All APIs have `8080` as default
2. Each defines a port in the non-`80xx` port number, for example `8180`, `8181` `8182`..

**Comment by tatu-at-datastax** [comment]
Correct @ivansenic. Based on our discussion the decision is "leave as is", with definitions listed in the original description.
Since there is no work to be done here, closing. May still need work on docker-compose, starctl, documentation, just no change to default settings.
