### ISSUE TITLE
Publish `sgv2-quarkus-common` jar to Maven Central

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2085]
While Stargate v1 publishes all artifacts as jars, even if many/most are not needed (Coordinators), Stargate v2 stops publishing of all APIs as jars: they are published as Docker images which makes more sense. But there is one component, `sgv2-quarkus-common` that is a library and will be needed by anyone implementing Stargate V2 APIs/Services.
It should be published as a jar, to Maven Central to be accessible by external developers.

**Comment by ivansenic** [comment]
Done in #2085.
