### ISSUE TITLE
Remove in-coordinator Docs API implementation, update `stargate.rest.enableV1`

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2106]
In Stargate V2, all HTTP APIs are moved to stand-alone services, out of coordinator.

Since then we have removed GraphQL implementation from Coordinator, and can now remove Document API as well, having first removed Integration Tests that rely on it.

This still leaves REST API,  and for that we have `stargate.rest.enableV1` system property that was added earlier.
We need to change that a bit to allow for disabling RESTv2 part of API only, leaving RESTv1 as that is still needed for time being (for Stargate V2 deployments; new REST API only implements RESTv2 part of API).

**Comment by jeffreyscarpenter** [comment]
Final removal on 2.1 branch in #2640.
