### ISSUE TITLE
Remove in-coordinator (SGv1) GraphQL-api

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2117]
As part of Stargate V2 clean up we can now remove:

1. `graphqlapi` main-level Stargate V1 implementation (all ITs removed earlier), replaced by Quarkus-based `apis/sgv2-graphqlapi`
2. RESTv2 half of `restapi` (need to leave RESTv1), replaced by Quarkus-based `apis/sgv2-restapi`. Module will remain for time being, until we can deprecate RESTv1.

**Comment by tatu-at-datastax** [comment]
Ok: already merged PR for GraphQL removal (#2119) but based on further discussions, reverted -- we need to wait until successful deployment to production: this way we have easy/easier rollback path, having the old implementation still available.

Leaving the issue itself open.

**Comment by jeffreyscarpenter** [comment]
Fixed on 2.1 branch in #2640.
