### ISSUE TITLE
Swagger in Docs API v2 creates a wrong curl command

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2131]
We need to investigate further, but I noticed that query parameters are not correctly being mapped to the curl command:

* non defined parameters still appear
* parameters having values that are JSON objects are not encoded correctly
* we should also re-check the token, as it seems not to work once removed (token still sent with `MY_AUTH_TOKEN` value)

Labeling with REST as well, as it could be a problem there too.

**Comment by ivansenic** [comment]
@tatu-at-datastax

**Comment by tatu-at-datastax** [comment]
Yes that is very strange. So this via Swagger UI, getting extra parameters defined (including multiple auth-related ones).

**Comment by ivansenic** [comment]
Done in #2157.
