### ISSUE TITLE
Test handling of "where" clause for REST API that does NOT escape curly braces

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2142]
It looks like PostMan does not escape `{` and `}` characters in query parameters, although it should. This seems to lead to an odd 400 failure with no response with REST API

This needs to be investigated; it probably makes sense to add a new Integration Test.

Note: this requires disabling of URL encoding of query parameters as per:

https://stackoverflow.com/questions/55019246/restassured-disable-url-encoding-not-working-correctly

that is, using:

   given().urlEncodingEnabled(false)....

**Comment by ivansenic** [comment]
@tatu-at-datastax I will add on a docs test on top of your PR..

**Comment by tatu-at-datastax** [comment]
Hmmh. This gets tricky. Although I can disable URL encoding for RestAssured query builder, it still validates things so I get failure on test:

```
java.lang.IllegalArgumentException: Illegal character in query at index 126: /v2/keyspaces/rowget_ks_getRowsWithQueryNoEscape_1665168115418/rowget_t_getRowsWithQueryNoEscape_1665168115418?raw=true&where={%22id%22:{%22$eq%22:%223c4daf7b-1571-4f98-ab74-0afc0b5be44a%22}}

	at java.base/java.net.URI.create(URI.java:906)
	at java.base/java.net.URI.resolve(URI.java:1089)
	at io.restassured.internal.http.URIBuilder.setQueryNVP(URIBuilder.java:174)
	at io.restassured.internal.http.URIBuilder.addQueryParams(URIBuilder.java:287)
        ....
```
and the index is for the opening curly brace. So need to figure out something else.

**Comment by tatu-at-datastax** [comment]
Worse: HttpClient from JDK 11 ALSO validates `URI`, failing on client side without sending anything.

**Comment by tatu-at-datastax** [comment]
Not considered a priority as we have work-around to allow such requests, closing.
