### ISSUE TITLE
Docker-compose scripts should allow enabling request log by Quarkus

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2148]
By default, Quarkus does not output request information on output logs. But it seems useful to enable this if there is a Quarkus setting to easily do so, and add a switch (`-q` since `-r` is taken) to startup scripts for doing so.

I think this doc:

https://quarkus.io/guides/http-reference#configuring-http-access-logs

suggests use of following:

* System property: `quarkus.http.access-log.enabled=true`
* ENV: `QUARKUS_HTTP_ACCESS_LOG_ENABLED=true`

and we could also configure pattern to use with:

* `quarkus.http.access-log.pattern`
* `QUARKUS_HTTP_ACCESS_LOG_PATTERN`

**Comment by ivansenic** [comment]
@tatu-at-datastax Isn't this done?

**Comment by tatu-at-datastax** [comment]
Not yet; the other one (default log level) is.

**Comment by tatu-at-datastax** [comment]
Created PR that implements this: #2161
