### ISSUE TITLE
gRPC service exception handlers should log exceptions

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2166]
We should at least log the exceptions that's considered server-side errors.. A good example of those exists already in the:

```
io.stargate.sgv2.restsvc.impl.GrpcExceptionMapper#grpcResponseAndLog
```

A set of status codes that do not have to be logged: `OK|CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|UNAUTHENTICATED|PERMISSION_DENIED`

Because there is no logging, the original exceptions are lost.

**Comment by jeffreyscarpenter** [comment]
Just to be clear, this is an issue in v1, you're just suggesting code from v2 as an example of how to handle?

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter Correct: for some reason V1 handler has bit better handling, V2 is missing it. I'll have PR soon.

**Comment by ivansenic** [comment]
This is issue in V1 and V2, in the public grpc api.. The fix in #2171 handles logging on the client side.. We need server side fixed as well..

**Comment by ivansenic** [comment]
@jeffreyscarpenter @tatu-at-datastax @versaurabh Any chance we can speed things here up? We need to have this soon, all the exceptions are not logged in the public grpc api

**Comment by tatu-at-datastax** [comment]
I think @versaurabh is working on this. It sounds like we need to make sure both gRPC servers log exceptions: public gRPC API one, and Bridge service.

**Comment by ivansenic** [comment]
Done in several PRs #2208 and #2225.
