### ISSUE TITLE
Add Stargate homepage to the V2 services

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2177]
Should replace the current home page generated by Quarkus. See https://github.com/stargate/stargate/blob/v2.0.0/apis/sgv2-docsapi/src/main/resources/META-INF/resources/index.html for reference.

**Comment by jeffreyscarpenter** [comment]
@ivansenic can we close this issue?

**Comment by ivansenic** [comment]
> @ivansenic can we close this issue?

I guess so.
