### ISSUE TITLE
Bridge service is not handling runtime exceptions

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2179]
Bridge service currently silently ignores the `RuntimeExceptions`, if they occur in the methods that are not handled with the `MessageHandlers`. Basically:

* `executeQueryWithSchema`
* `describeKeyspace`

The proper try/catch must be included, so that any runtime exception is handled. Current situation is that client side hangs, because observer on the server side is not informed on the error.

We need to catch that hang in test first. This can be easily done, mock the `Persistence` and for example throw exception on `persistence.decorateKeyspaceName`..

In addition to this, these exceptions should be logged. Also we should log possibly all the exceptions that we catch in the `io.stargate.bridge.service.ExceptionHandler`, which is not done right now.

**Comment by ivansenic** [comment]
The exception being thrown is the NPE, due to the https://github.com/stargate/stargate/issues/2181

**Comment by tatu-at-datastax** [comment]
Looks like the issue with `describeKeyspace()` is that `SchemaHandler` does not catch `RuntimeException`.
It needs to; and should also use `ExceptionHandler` to properly map exception to desired error to return to client (and log if need be).

But `executeQueryWithSchema()` may already be handling things properly if I am not mistaken: I will try to add a test to verify this.
