### ISSUE TITLE
Remove source api from schema reads

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2195]
Use the value passed in the metadata and intercepted by the bridge.

**Comment by ivansenic** [comment]
@tatu-at-datastax Why closing this? It's not done :)

**Comment by tatu-at-datastax** [comment]
@ivansenic  Because of PR that was merged and referenced... Ohhhh. That was for different issue, 2175 not 2195.

Ok, no sorry, my bad. :)
