### ISSUE TITLE
Update DSE to 6.8.28

### ISSUE THREAD

**Issue by devoshmathivanan** [stargate/stargate#2197]
A new version of DSE (6.8.27) has been released and should be used.

See release notes for issues resolved: https://github.com/datastax/release-notes/blob/master/DSE_6.8_Release_Notes.md#release-notes-for-6827

**Comment by devoshmathivanan** [comment]
6.8.27 is broken due to an issue with the packaging of the management API.
The current plan for the issue with 6.8.27 is:
1. Remove the broken 6.8.27 release.
2. Issue a new release with the fix to the management API.

I'll update here once we have a concrete plan.

**Comment by thobe** [comment]
DSE 6.8.28 has been released, [resolving the above mentioned issue in 6.8.27](https://github.com/datastax/release-notes/blob/master/DSE_6.8_Release_Notes.md#release-notes-for-6828). Please use version 6.8.28 instead.

**Comment by ivansenic** [comment]
Done, we are already on `6.8.29`
