### ISSUE TITLE
REST API V2 not including authentication token in Swagger when specified

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2200]
Seems that something is not correctly set in the REST API with respect to openapi/swagger. Once token is specified using the `:lock: Authorize` box, the request are not including it when clicking on `Try me`. It's most likely a missing notation like on all resources:

```
@SecurityRequirement(name = OpenApiConstants.SecuritySchemes.TOKEN)
```

See documents API for a working solution.

**Comment by tatu-at-datastax** [comment]
This was exactly the problem; fixed in #2002.
