### ISSUE TITLE
Issue with Timezones when writing timestamp data type

### ISSUE THREAD

**Issue by HiltonRosenfeld** [stargate/stargate#2223]
When inserting timestamp data to AstraDB via Stargate REST API, the only timezone that works is Z.
No other timezones or timezone offsets work. Here are the ones I've tested:

**Working:**
- 2022-11-08T10:30:00Z
- 2022-11-08T10:30:00.000Z

**Not Working**
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00.000' could not be parsed at index 23
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00.000+11' could not be parsed at index 23
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00.000+1100' could not be parsed at index 23
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00.000+11:00' could not be parsed at index 23
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00' could not be parsed at index 19
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00+11' could not be parsed at index 19
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00+1100' could not be parsed at index 19
- Bad request: Invalid Timestamp value: Text '2022-11-08T10:30:00+11:00' could not be parsed at index 19

### Test Environment

**Table definition**
```
CREATE TABLE demo.sendemail (
    timestamp timestamp PRIMARY KEY,
    emaildata text
)
```

**API POST**
```
curl --location --request POST 'https://1b44200e-93df-4b4e-b250-005c20557cde-australia-southeast1.apps.astra.datastax.com/api/rest/v2/keyspaces/demo/sendemail' \
--header 'X-Cassandra-Token: <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "timestamp": "2022-11-08T10:30:00.000",
    "emaildata": "this is my mail message"
}'
```

**Comment by ivansenic** [comment]
Is this more a better documentation request or support all timestamps?

**Comment by HiltonRosenfeld** [comment]
This is more a request to support all timezones.

**Comment by tatu-at-datastax** [comment]
Starting to investigate this now; here are some initial findings from modifying an existing Integration Test:

First, it looks like Stargate V1 does indeed fail on offsets, with or without colon.

Stargate V2 REST appears to accept offset with colon (`+02:00`, `-03:00`) but not without.

I will see if I can create unit tests for converters to dig deeper wrt Stargate V2 handling.

**Comment by tatu-at-datastax** [comment]
Ok, I found a way to improve REST implementation in Stargate V2 (`main` branch), added tests, PR is #2241. But I think I better try to cover all tests cases included -- the only I am not sure about is lacking timezone/offset indicator altogether as that seems like a dangerous usage.
But if that would result in same behavior as with `Z` maybe that is acceptable.
