### ISSUE TITLE
Update gRPC version on coordinator to `1.49.2`

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2224]

**Comment by tatu-at-datastax** [comment]
Since Quarkus 2.13.4 depends on version `1.49.0`, that seems like the specific version to use (currently we use older `1.45.1`):

https://mvnrepository.com/artifact/io.quarkus/quarkus-grpc/2.13.4.Final

2.14.0 will depend on `1.50.2` so we can and I think should upgrade this when upgrading Quarkus.
