### ISSUE TITLE
NPE in NativeTransportService.destroy

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#224]
Calling `persistence.destroy()`causes a NPE in `NativeTransportService.destroy` both for C* 3.11 and 4.0 persistence.

See "TODO" notes in:

https://github.com/stargate/stargate/blob/master/persistence-cassandra-4.0/src/test/java/io/stargate/db/cassandra/impl/CassandraPersistenceIT.java

https://github.com/stargate/stargate/blob/master/persistence-cassandra-3.11/src/test/java/io/stargate/db/cassandra/impl/CassandraPersistenceIT.java

**Comment by jeffreyscarpenter** [comment]
won't fix
