### ISSUE TITLE
Index Creation KO: mark existing column as not present.

### ISSUE THREAD

**Issue by clun** [stargate/stargate#2244]
**Stargate version**: `2.0.1`
*(Introduced in V2, this test is working in V1)*

**Behaviour:**
Given an existing table `videos`, in a keyspace `java` with column `title`.

<img width="1441" alt="Screenshot 2022-11-18 at 16 27 24" src="https://user-images.githubusercontent.com/726536/202645623-10a540b0-6dc0-4bc7-a9b7-73f7ce08a208.png">

The call is successful and return. I confirm this column exists in the table.
```json
{
  "data": {
    "name": "title",
    "typeDefinition": "text",
    "static": false
  }
}
```

*When trying to create an index on that column...*
<img width="1449" alt="Screenshot 2022-11-18 at 16 30 08" src="https://user-images.githubusercontent.com/726536/202646018-a7f146c6-cf63-49c4-af29-dd7e9a801f43.png">

The following message is returned

```json
{
  "description": "Column 'title' not found in table.",
  "code": 404,
  "grpcStatus": null,
  "internalTxId": null
}
```

The Table definition is the following:

```sql
CREATE TABLE java.videos (
    genre text,
    year int,
    title text,
    formats frozen<map<text, text>>,
    tuples frozen<tuple<text, text, text>>,
    upload timestamp,
    frames list<int>,
    tags set<text>,
    PRIMARY KEY (genre, year, title)
) WITH CLUSTERING ORDER BY (year ASC, title ASC)
```

Or as `Json` 
```json
{
  "data": {
    "name": "videos",
    "keyspace": "java",
    "columnDefinitions": [
      {
        "name": "genre",
        "typeDefinition": "text",
        "static": false
      },
      {
        "name": "year",
        "typeDefinition": "int",
        "static": false
      },
      {
        "name": "title",
        "typeDefinition": "text",
        "static": false
      },
      {
        "name": "formats",
        "typeDefinition": "frozen<map<text, text>>",
        "static": false
      },
      {
        "name": "frames",
        "typeDefinition": "list<int>",
        "static": false
      },
      {
        "name": "tags",
        "typeDefinition": "set<text>",
        "static": false
      },
      {
        "name": "tuples",
        "typeDefinition": "tuple<text, text, text>",
        "static": false
      },
      {
        "name": "upload",
        "typeDefinition": "timestamp",
        "static": false
      }
    ],
    "primaryKey": {
      "partitionKey": [
        "genre"
      ],
      "clusteringKey": [
        "year",
        "title"
      ]
    },
    "tableOptions": {
      "defaultTimeToLive": 0,
      "clusteringExpression": [
        {
          "name": "year",
          "order": "ASC"
        },
        {
          "name": "title",
          "order": "ASC"
        }
      ]
    }
  }
}
```

**Comment by ivansenic** [comment]
Hm, was there no test for this before or? Seems strange that some things are not working now and are OK in v1.

**Comment by tatu-at-datastax** [comment]
We do have tests for Index creation so it is not immediately clear why this would fail.
I will try to reproduce with an IT when I get to this one (there are couple of REST bugs to go through).

**Comment by tatu-at-datastax** [comment]
Ok, it looks like I can reproduce this issue with an Integration test -- will try to see how this is different from existing Index creation IT that passes.

**Comment by tatu-at-datastax** [comment]
Interesting. This is because `title` is part of primary key; check for column existence is looking at list of non-key columns (assuming probably that the list contains all columns).

Good catch; earlier tests was using non-key column and did not hit this problem.

**Comment by tatu-at-datastax** [comment]
PR ready for review.
