### ISSUE TITLE
Cannot retrieve tuples field from GET REST API V2 when value is null

### ISSUE THREAD

**Issue by clun** [stargate/stargate#2246]
Given the following data in the database:

- Table Structure
```sql
CREATE TABLE java.videos (
    genre text,
    year int,
    title text,
    formats frozen<map<text, text>>,
    tuples frozen<tuple<text, text, text>>,
    upload timestamp,
    frames list<int>,
    tags set<text>,
    PRIMARY KEY (genre, year, title)
) WITH CLUSTERING ORDER BY (year ASC, title ASC);
```

- Query
```sql
 select * from videos where genre='Sci-Fi' AND year=1990 AND title='line_update';
```

- Data 
```
 genre  | year | title       | formats | frames | tags | tuples | upload
--------+------+-------------+---------+--------+------+--------+---------------------------------
 Sci-Fi | 1990 | line_update |    null |   null | null |   null | 2022-11-18 08:16:35.243000+0000
```

When you want to retrieve the row providing the full primary key

- `GET` on `http://localhost:8082/v2/keyspaces/java/videos/Sci-Fi/1990/line_update`

The following error is thrown:

```json
{
    "description": "Internal error: failed to convert value of column #7/#8 ('tuples'), problem: Illegal Tuple representation, expected 3 values, received 0",
    "code": 500,
    "grpcStatus": null,
    "internalTxId": null
}
```

The field `tuples` is nullable and still an marshalling is expected.

**Comment by tatu-at-datastax** [comment]
Sounds like a problem with handling. One minor question/contemplation: should such "missing" Tuple value be represented as empty JSON Array (`[]`) or `null`? To me latter seems better so I'll proceed with that initially but wanted to hear how others feel about it.

**Comment by clun** [comment]
`null` would make the most sense as the field is nullable and not present in the record. 

It is different from an existing tuple with no value for its attributes.

**Comment by tatu-at-datastax** [comment]
Thank you @clun. I merged the fix so it can be tested locally if you can build a new version. Otherwise will be in 2.0.2.
