### ISSUE TITLE
Health Check endpoint on the coordinator nodes as they own grpc endpoints ?

### ISSUE THREAD

**Issue by clun** [stargate/stargate#2247]
To create a client-side load balancer i would need to get an HTTP endpoint to test the availability of the coordinator. 

I suspect this to also be required when deployed in Kubernetes as a liveness probe.

Maybe it does already exists, i simply tried `http://localhost:8081/stargate/health` like the other and got a 404 meaning that we have http server running we could leverage.

**Comment by jeffreyscarpenter** [comment]
yes, there are actually two health check endpoints on the coordinator: `http://localhost:8084/checker/liveness` and `http://localhost:8084/checker/readiness`

there's a PR in review which should help document this better https://github.com/stargate/stargate/pull/2243.
