### ISSUE TITLE
Use "Optimistic Query" functionality from common in SGv2/REST API

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2265]
(from #2213 code review)

`RestResourceBase` method

```
  protected Uni<QueryOuterClass.Response> executeQueryAsync(
```

has a TODO note 

```
    // TODO implement optimistic queries (probably requires changes directly in SchemaManager)
```

which might be doable as:

```
return findTableAsync(keyspaceName, tableName, true)
    .onItem()
    .transformToUni(table -> executeQueryAsync(queryProducer.apply(table)))
    .onFailure(t -> {// predicate for matching the optimistic schema failure}).retry().atMost(2);
```

**Comment by tatu-at-datastax** [comment]
@ivansenic Looking at this, I think that the problem is not the call sequence itself but that the method eventually called in `StargateBridge` needs to be `executeQueryWithSchema()` -- to use cached local copy of schema -- and not `executeQuery()`.

So it seems that we are not actually using optimistic table/schema lookup at all currently (by REST API at least, and I don't think GraphQL does it either) but blocking lookup, incurring that extra roundtrip.

**Comment by ivansenic** [comment]
> @ivansenic Looking at this, I think that the problem is not the call sequence itself but that the method eventually called in `StargateBridge` needs to be `executeQueryWithSchema()` -- to use cached local copy of schema -- and not `executeQuery()`.
> 
> So it seems that we are not actually using optimistic table/schema lookup at all currently (by REST API at least, and I don't think GraphQL does it either) but blocking lookup, incurring that extra roundtrip.

We have a ticket for this, let's make it work..

**Comment by tatu-at-datastax** [comment]
Note: #2355 adds support to `sgv2-quarkus-common`, to be used by REST API.
