### ISSUE TITLE
Enable Github Action based Coordinator Test to replace GCB for Stargate V2

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2281]
We should be able to enable `.github/workflows/coordinator-test.yml` on Stargate V2 active branches as well as PRs -- so far it has only been manually startable.
If and when this works well this should replace Google Cloud Build we have used so far.

We can also consider doing the same for `v1` (Stargate V1) but it as bit more testing as there are also tests for in-Coordinator APIs

**Comment by tatu-at-datastax** [comment]
Looks like tests run on GH take roughly 2x as long as on Google CB.
Also bit worried about instability of actions; one of 3 tests failed with some transient issue (passed on re-run later on).

**Comment by ivansenic** [comment]
This will be fine when v2 stuff and tests are moved out of the coordinator.. So maybe wait until then? We could also use more powerful machines on the GH..

**Comment by tatu-at-datastax** [comment]
@ivansenic All v2 service tests are moved out in `main` branch by now (except for RESTv1 that remains in coordinator) so runtime there is quite a bit shorter than in `v1`. This is why I was/am thinking to enable this just for `main` at first.

**Comment by ivansenic** [comment]
@tatu-at-datastax Aaah, was not aware of the fact that the tests are moved out..

**Comment by tatu-at-datastax** [comment]
@ivansenic Yeah it was done before I was about to remove services from coordinator, but that removal got reverted. Tests are still out tho (we have them in `v1` anyway, just not in `main` branch).

This did not reduce runtime quite as much as I thought (maybe 30%) but it is something. I guess main CQL tests take longest.

**Comment by tatu-at-datastax** [comment]
This has been achieved by other PRs, closing.
