### ISSUE TITLE
Inject build version number of APIs into `index.html` (or another easily accessible place)

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2285]
Currently there is no easy way to check the version of APIs deployed from resource endpoints or web UI.
But since the API frontpage comes from:

    sgv2-graphqlapi/src/main/resources/META-INF/resources/index.html

(etc for others)
It seems that we could perhaps embed version number there dynamically: either during release or perhaps during build, if templating is supported.

The point is that it should be easy to just check a web UI or call resource to get the version number that build has.

**Comment by tatu-at-datastax** [comment]
Reopening to do PR for Docs API and GraphQL (closed too early).

**Comment by tatu-at-datastax** [comment]
Also forgot to add: the initial idea was from having the issue of broken release for C2 where we had nominal 2.0.2 release but containing Stargate 2.0.1. This would have been visible via UI.
Another thing we could consider is adding version somewhere like in healthcheck, but for now this seems like a simple way to do it.

**Comment by ivansenic** [comment]
> Also forgot to add: the initial idea was from having the issue of broken release for C2 where we had nominal 2.0.2 release but containing Stargate 2.0.1. This would have been visible via UI. Another thing we could consider is adding version somewhere like in healthcheck, but for now this seems like a simple way to do it.

But UI should be visible only in dev mode.

**Comment by tatu-at-datastax** [comment]
> > Also forgot to add: the initial idea was from having the issue of broken release for C2 where we had nominal 2.0.2 release but containing Stargate 2.0.1. This would have been visible via UI. Another thing we could consider is adding version somewhere like in healthcheck, but for now this seems like a simple way to do it.
> 
> But UI should be visible only in dev mode.

It was visible via docker-compose deployment. Is that not running as Prod?
