### ISSUE TITLE
Support Cassandra 4.1 as a persistence backend

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2311]
Now that Cassandra 4.1 is generally available, add a C* 4.1 persistence backend implementation for Stargate.

**Comment by marianne-manaog** [comment]
I am currently running C* performance tests using `k8ssandra-operator` that would need to run the latest C* v4.1, which has the following Paxos v2 bug fixes:

1) fix of the `ContentionStrategy` backoff and `Clock.waitUntil`, as per [this Git commit](https://github.com/apache/cassandra/commit/81c616826ab3c8aa96467771d0e074a874efdd77); 

2) fix for the `WriteTimeoutException` when using a single datacenter, as per [this Git commit](https://github.com/apache/cassandra/commit/acda6fad688e95e0a9a34de28e3b61a775e59736). 

So, it would be great to have Stargate compatible with the latest `k8ssandra-operator` (v1.4.1).

**Comment by jeffreyscarpenter** [comment]
My assumption is that this would require creating a new persistence module `persistence-cassandra-4.1`, and that we'd continue to support the `persistence-cassandra-4.0` module to match the [schedule](https://cassandra.apache.org/_/download.html) published by the Apache Cassandra project. This has implications for a variety of areas like adding the module to CI testing and publishing Docker images.

Since the K8ssandra project has not upgraded to Stargate v2, there's an argument for adding this new module to both the `main` (v2) branch and to `v1` - as much as we'd like to encourage forward motion.

**Comment by tatu-at-datastax** [comment]
Created #2609 before realizing there was this one already. But TL;DNR; at least 2 breaking changes between 4.0 and 4.1 APIs (note: https://fossies.org/diffs/apache-cassandra/4.0.7_vs_4.1.0/ has helpful diff):

* `LocalAwareExecutorService` renamed as `LocalAwareExecutorPlus` -- seems like possibly mechanical change, easy to do
* `SchemaChangeListener` was changed to `interface` (from (abstract?) class); but more importantly, completely changed to be typed, taking typed parameters instead of `String`s. Need to change 2 implementations.

**Comment by tatu-at-datastax** [comment]
I think it needs to be new one since APIs we use are not all compatible between 4.1 and 4.0 so it is not (I think) possible to have one backend that would work with both C*4.0.x and 4.1.x.

But it can probably be bootstrapped by copying 4.0 backend and making modifications from there.

**Comment by mamccorm** [comment]
Any updates on this one? Cassandra 4.1 was first released in December 2022. Does this affect both Stargate v1 (EOL) and also Stargate v2 (maintained)?

**Comment by mamccorm** [comment]
Hi all. Any updates on this one? Looks like Cassandra 4.1 was first released back in December 2022. Does this affect both Stargate v1 (EOL) and also Stargate v2 (maintained)?

**Comment by jeffreyscarpenter** [comment]
Closed by #2711

**Comment by jeffreyscarpenter** [comment]
> Hi all. Any updates on this one? Looks like Cassandra 4.1 was first released back in December 2022. Does this affect both Stargate v1 (EOL) and also Stargate v2 (maintained)?

Hi @mamccorm - we added this persistence module on the v2.1 branch a few months back but apparently did not link the PR to this issue.
