### ISSUE TITLE
Mark REST v1 endpoints as Deprecated

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2339]
Based on discussion #2242, document the REST /v1 endpoints as being deprecated and scheduled for removal in Stargate v3.

Update documentation
- https://github.com/stargate/stargate/blob/main/restapi/README-docsapi.md 

Code warnings
- add startup message to restapi module at WARN level

**Comment by jeffreyscarpenter** [comment]
Assume there are /v1 docs paths such that we should keep, not delete the README-docsapi. Should there also be a very simple base README that at least indicates how to re-enable the v1 paths?

**Comment by tatu-at-datastax** [comment]
I don't think think there are parts of in-coordinator Documents API that we would want to separately enable; it is not divided same way as REST API is.

**Comment by jeffreyscarpenter** [comment]
What I'm looking for is that whatever READMEs we have in that directory are up to date and don't describe functionality that isn't there.

**Comment by tatu-at-datastax** [comment]
Ah. I do need to further add basic `README.md` too, right. And mention the "secret" system property.
