### ISSUE TITLE
Remove dependency on ccm for integration tests

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2348]
Update integration tests to use Docker containers to start Cassandra instead of `ccm`. `ccm` is no longer actively maintained, and it is based on Python 2.7 which is EOL and not available on Ubuntu 20.04/22.4, which causes us to have to do some hacky installation on our CI runners.

IT framework already uses Docker to run Keycloak so this should not be a major lift. The vast majority of ITs require only a single C* node but for the small number of cases that require multiple nodes we can come up with a workaround.  Ideally this should be done on `v1` branch first and merged to `main`.

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter I think the plan is to keep on using `ccm` for Stargate V1, but drop it from Stargate V2?

**Comment by jeffreyscarpenter** [comment]
Thanks for the reminder. The original premise of this issue was the belief that ccm requires Python 2, which I later learned was incorrect. I was able to fix our CI workflow to install ccm on Python 3 in #2378 as part of updating to newer Ubuntu runners. 

Moving coordinator integration tests to be container-based test would add complexity to the testing process - requiring the coordinator image to be built. Therefore I think the right thing to do is to close this as won't fix for now. We can re-open later if the situation changes.

**Comment by tatu-at-datastax** [comment]
Ah yes, Coordinator tests are still relevant. Makes sense.
