### ISSUE TITLE
Update DSE to 6.8.31

### ISSUE THREAD

**Issue by tiagomlalves** [stargate/stargate#2356]
A new version of DSE has been released and should be used.

See release notes for issues resolved: https://github.com/datastax/release-notes/blob/master/DSE_6.8_Release_Notes.md#release-notes-for-6831

**Comment by tatu-at-datastax** [comment]
Fixed via #2370, will need a new build, handled under #2390.

**Comment by tatu-at-datastax** [comment]
DSE 6.8.31 included in:

* Stargate v1.0.72 (released)
* Stargate v2.0.7 (to be released today)
