### ISSUE TITLE
Add REST API integration tests that verify sequence of Bridge calls executed for core REST operations

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2358]
(note: offshoot of #2351)

Currently we do not have (integration) tests that verify sequences of bridge calls taken for various REST API operations. In particular, whether various authorization calls are made (or not) is not validated. Because of this, changes like #2351 are potentially risky -- and perhaps as importantly, we do not know what the current behavior actually is.

We should add such tests at least for a core set of operations (basic CRUD row access).

**Comment by ivansenic** [comment]
Depends on https://github.com/stargate/stargate/issues/2376
