### ISSUE TITLE
Include Stargate v2 APIs in release artifacts

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2380]
Executables for the Stargate v2 APIs are not included in the release artifacts. The `stargate-jars.zip` includes jar files for the coordinator and the `starctl` script, but not the APIs. 

This makes it difficult for those who wish to deploy Stargate v2 without using Docker containers.

**Comment by jeffreyscarpenter** [comment]
Ideally, the release artifacts should have a separate zip file for each API which we'd include alongside the `stargate-jars.zip` (which could be renamed to `stargate-coordinator.zip` to be more descriptive).

The zip file for each API would have the uber-jar plus a convenience script for starting the API. The convenience script would be a useful place to simplify the configuration of quarkus options on each API, and as a place to check that `JAVA_HOME` is correctly set to point to JDK 17 or higher.

**Comment by ivansenic** [comment]
My brain keeps fighting the startup script development. The fat jar starts with:

`java - jar rest-api.jar`

There are so many options there, how would we select which ones to bring in the startup script. Better solution is to provide a documentation with the jar that explains how to start and where to look for additional options. We do maintain `CONFIGURATION.md` with our own config params, we should try to create somehow the instructions that point to this and maybe additional important Quarkus guides as well.
