### ISSUE TITLE
Create an http-utility module

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#239]
As was discussed in https://github.com/stargate/stargate/pull/235/files#r502590739 it would be good if we created a module to consolidate common dependencies and code used by our http modules.

**Comment by ivansenic** [comment]
include `HttpMetricsTagProvider` as agreed in the https://github.com/stargate/stargate/pull/836#discussion_r613440525

**Comment by tatu-at-datastax** [comment]
Obsolete due to work for Stargate V2.
