### ISSUE TITLE
Fix flaky StargateBridgeInterceptorDeadlineTest

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2433]
Investigate why `io.stargate.sgv2.api.common.grpc.StargateBridgeInterceptorDeadlineTest` is failing in CI workflows, determine whether the issue is with the test or the implementation and fix accordingly. 
(Test was disabled in #2432)

**Comment by tatu-at-datastax** [comment]
FWTW this test "fails to fail" locally, which would suggest timing issue of some kind. But increasing timeout does not appear to help with CI which suggests something else.
