### ISSUE TITLE
Fix changelog generation

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2435]
It's impossible to keep the changelog updated.. Merges between `v1` and `main` are impossible to handle. We need to make a working solution.

Here is the small idea on how this can be done:

1. Main thing, keep change log for the versions separated
   * `CHANGELOG_V1.md` exists in the `v1` and `main` branch (merged)
   * `CHANGELOG_V2.md`exists only in `main` branch
2. Update the generation so that we can only include tags with the version prefix, thus for v1 we get only v1 changes. 
3. Ensure V1 changelog is changes only in `v1` branch. Ensure V2 change log is changed only in `main`

**Comment by jeffreyscarpenter** [comment]
fixed in #2443
