### ISSUE TITLE
Error in REST API on schema change

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2438]
Automated CI tests "Stargate Postman Collections" that were recently created for Postman collections are failing for the REST collection. This collection has a section where there is a request to rename a column followed immediately by a request to revert back to the original name.

This is the pertinent output from the Postman run:

```
↳ Change the column firstname to first
  PUT localhost:8082/v2/schemas/keyspaces/users_keyspace/tables/users/columns/firstname  
  200 OK ★ 153ms time ★ 474B↑ 101B↓ size ★ 10↑ 2↓ headers ★ 0 cookies
  ┌ ↑ raw ★ 60B
  │ {
  │       "name": "first",
  │       "typeDefinition": "varchar"
  │ }
  └ 
  ┌ ↓ application/json ★ text ★ json ★ utf8 ★ 16B
  │ {"name":"first"}
  └
  prepare   wait    dns-lookup   tcp-handshake   transfer-start   download   process   total 
  1ms       349µs   (cache)      (cache)         150ms            1ms        94µs      154ms 

  ✓  Status code is 200
  ✓  Verify column name

↳ Change the column first back to firstname
  PUT localhost:8082/v2/schemas/keyspaces/users_keyspace/tables/users/columns/first  
  400 Bad Request ★ 19ms time ★ 474B↑ 203B↓ size ★ 10↑ 2↓ headers ★ 0 cookies
  ┌ ↑ raw ★ 64B
  │ {
  │       "name": "firstname",
  │       "typeDefinition": "varchar"
  │ }
  └ 
  ┌ ↓ application/json ★ text ★ json ★ utf8 ★ 108B
  │ {"description":"Column 'first' not found in table 'use
  │ rs'","code":400,"grpcStatus":null,"internalTxId":null}
  └
  prepare   wait    dns-lookup   tcp-handshake   transfer-start   download   process   total 
  1ms       367µs   (cache)      (cache)         16ms             1ms        59µs      20ms  

  1. Status code is 200
  2. Verify column name
 ```

Run logs available under
https://github.com/stargate/stargate/actions/workflows/postman-docker.yaml

This may be a race condition, as this is not observed when the test is run on a local machine. However, even when a 1s delay between requests was added (`--delay-request 1000` option on `postman` command), the error still occurs - see run # 28 initiated from the `jeff/add-postman-delay` branch.

**Comment by ivansenic** [comment]
Great catch @jeffreyscarpenter, definitely not a race condition as the requests are not executed in parallel. I am pretty sure this is optimistic query issue. The first query does the schema change, but in the local state we still have the old schema state. The second query fails immediately on the cached schema state.

My guess is that schema change queries must not be done using the optimistic approach. Not sure if @tatu-at-datastax overlooked this.

**Comment by tatu-at-datastax** [comment]
I did not overlook it per se (in the sense I was unaware of optimistic schema lookup being used), but I did expect things to work with optimistic schema caching. The reason it is used had more to do with the way refactoring was done, however, and I agree that there is no need to use it, and that it is probably safer not to use it.

So I should go back and change schema endpoints to avoid using optimistic schema lookup.

**Comment by tatu-at-datastax** [comment]
Ok. So findings so far:

1. It is easy enough to reproduce the issue (WIP PR has failing case)
2. Changing to async get table method does not appear to fix the problem. :-( (I can check in code to show that)
3. I may be wrong but I think we may be using cached schema data for all kinds of access (but code in `SchemaManager` is not really easy to follow through so I may be wrong) so maybe failure of (2) is because it doesn't actually force reloading of schema info

**Comment by ivansenic** [comment]
@tatu-at-datastax What is the problem to always fetch the keyspace with the schema validation when executing schema update queries. That's exactly what we did before the optimistic queries?

**Comment by tatu-at-datastax** [comment]
> @tatu-at-datastax What is the problem to always fetch the keyspace with the schema validation when executing schema update queries. That's exactly what we did before the optimistic queries?

Good point; assuming nothing has changed that should still work? I am just surprised that changed code in #2442 does not appear to see changes either -- seems more likely I have a bug in my code there, I just don't know what.

**Comment by tatu-at-datastax** [comment]
Ok. Yes, turns out I had a small mistake in my async call sequence so schema-access-with-hash-check is fine, works as expected.
