### ISSUE TITLE
Improve experience of running integration tests against specific persistence

### ISSUE THREAD

**Issue by pcmanus** [stargate/stargate#244]
Afaict, to run an integration test from Intellij against a particular persistence implementation, you have to edit the configuration and use `-Dccm.version=<version>`.

First, it's a bit weird that the ccm version defines which persistence extension we use (what if someone want to work on an alternative C* 3.11 persistence extension? How would this be picked over the existing one?).

But also, it would be nice if we could make the experience the same than with `PersitenceTest`, where Intellij is able to detect the versions against which to run, without a need to add custom configurations.

**Comment by tatu-at-datastax** [comment]
Will close this issue since there are plans to refactor Persistence/Service separation as part Stargate V2 re-architecting, and that should improve handling separately.
