### ISSUE TITLE
Avoid using profiles in REST integration tests

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2440]
There are two integration tests in REST that test the same thing based on the properties:

* RestApiV2QCqlDisabledIT
* RestApiV2QCqlIT

The second one specifies a profile that sets `stargate.rest.cql.disabled=false`.

However, although this works on the integration tests, it fails when we are using the integration tests with the running app. Simply, you can not switch the properties of the running app. IN that sense, the integration tests, which are effectively end-to-end tests should not specify profiles.

I am not sure what's the best way to solve this. Imo the `RestApiV2QCqlDisabledIT` could be classical `@QuarkusTest` with concrete profile and check that method is not existing. For the other, we could enable by default in the test resources that the option is `false` and then have some kind of a protection in the situation when we run against the running app. Not sure though, maybe a small discussion on this should be done.

**Comment by tatu-at-datastax** [comment]
Ok. Yes, that makes sense. Just need to discuss the best way to refactor things to just verify 2 aspects (default being not to include; ability to include).
