### ISSUE TITLE
Space removed from HTML document (even in <pre>)

### ISSUE THREAD

**Issue by synedra** [stargate/stargate#2444]
I am posting a README HTML which includes <pre> sections.  The document database flattens and removes all newlines and whitespace, so it is unusable.  I will do pre- and post- processing to make this work but Stargate should not edit the string in this way.

Database: https://b69beb6b-2fc5-4701-915f-251d5a367d1d-us-east1.apps.astra.datastax.com

Original post includes:
<pre lang="sql"><code>USE nosql1;

CREATE TABLE IF NOT EXISTS accounts_by_user (
  user_id         UUID,
  account_id      UUID,
  account_type    TEXT,
  account_balance DECIMAL,
  user_name       TEXT      STATIC,
  user_email      TEXT      STATIC,
  PRIMARY KEY ( (user_id), account_id)
)   WITH CLUSTERING ORDER BY (account_id ASC);
</code></pre>

file in db api has:

pre lang=\"sql\"><code>USE nosql1;CREATE TABLE IF NOT EXISTS accounts_by_user (  user_id         UUID,  account_id      UUID,  account_type    TEXT,  account_balance DECIMAL,  user_name       TEXT      STATIC,  user_email      TEXT      STATIC,  PRIMARY KEY ( (user_id), account_id))   WITH CLUSTERING ORDER BY (account_id ASC);</code></pre>

**Comment by tatu-at-datastax** [comment]
Ok so which API is this for? And what is the actual request being sent?
(in earlier discussions Documents API was mentioned but you do not create tables directly for that API)

**Comment by tatu-at-datastax** [comment]
No update from submitter, closing.
