### ISSUE TITLE
How does CQL respond when there is an error on gRPC interaction?

### ISSUE THREAD

**Issue by caniko** [stargate/stargate#2452]
I am trying to catch errors returned by CQL when interacting through gRPC, but I don't know what kind of response to expect.

Similar to:
https://github.com/stargate/stargate-grpc-rust-client/issues/21

**Comment by ivansenic** [comment]
There is a best effort to translate CQL erros to the gRPC status codes. Of course this can not be mapped one to one. Is there any concrete problem with the ways gRPC errors are reported?

**Comment by caniko** [comment]
No, but I am, currently, specifically interested in errors from `INSERT INTO`.
