### ISSUE TITLE
Optimize CI workflows for coordinator changes

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2456]
Once #2455 is closed, we should be able to make the following optimizations to our CI workflows:

- optimize the CI workflow for coordinator modules to only run if the commit contains changes to a coordinator module - this will speed up "API only" commits since the long running coordinator tests won't be needed
- optimize the CI workflow for APIs to use coordinator docker images that are based on the last commit affecting coordinator code - this will speed up API CI runs and generate fewer docker images that the workflow caches as GitHub artifacts.

**Comment by ivansenic** [comment]
Done in https://github.com/stargate/stargate/pull/2484 and https://github.com/stargate/stargate/pull/2378
