### ISSUE TITLE
Add response pagingState to QueryExpectation 

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/stargate#2461]
Add pagingState in ValidatingStargateBridge.QueryExpectation, to perform unit test where paging state needs to be returned.

**Comment by ivansenic** [comment]
I guess this is already implemented, and it's automatically handled. For example, having:

```
    withQuery(query.getCql())
        .withPageSize(pageSize)
        .withColumnSpec(columnSpec)
        .returning(
            ImmutableList.of(
                row("1", "x", 1.0d),
                row("1", "y", 2.0d),
                row("2", "x", 3.0d),
                row("3", "x", 1.0d),
                row("4", "y", 2.0d),
                row("4", "x", 3.0d),
                row("5", "x", 3.0d),
                row("5", "y", 3.0d)));
```

and giving page size which is smaller than those 8 rows, will automatically handle page state. 

Thus, if you specify `pageSize=2`, you will get result that contains first 2 rows and a paging state.. One you execute the same query again by providing the received paging state in the `QueryParameters`, you will get rows 3 & 4. And so on.

Automated handling is done in the `ValidatingPaginator` class.
