### ISSUE TITLE
Use concurrency to cancel workflows on pull request updates

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2493]
Using the [GitHub concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) we can cancel the existing workflows for the same PR once that PR is updated.. Since you update a PR with a new commit, there is no need to have the old one running to the end. For us this can mean significant savings in CI minutes used.

**Comment by ivansenic** [comment]
@jeffreyscarpenter @tatu-at-datastax Your opinion?

**Comment by jeffreyscarpenter** [comment]
Seems like a good idea, especially for longer running coordinator tests

**Comment by tatu-at-datastax** [comment]
Agreed, +1.

**Comment by ivansenic** [comment]
Can any of you approve the PR.

**Comment by ivansenic** [comment]
Done in #2494.
