### ISSUE TITLE
Provide a way to get notified about closed user connection when shutting down a node

### ISSUE THREAD

**Issue by jtgrabowski** [stargate/stargate#2525]
`QueryInterceptor` uses `EventListener` to inform Stargate about cluster topology changes. Among other callbacks, `QueryIntercepor` implemented in CNDB, invokes `onLeaveCluster()` to initiate graceful connection shutdown between drivers and CNDB node that is leaving the cluster. The shutdown is based on sending `REMOVED_NODE` topology event to driver, which nudges driver to drain the connections and eventually close them.
 
It would be good to have a way to notify CNDB once all connections are closed in this case.

This comes from the fact that CNDB delays node shutdown so that all pending connections may be gracefully closed by the driver (and all queries finish successfully). This fixed delay is sub-optimal, we could shutdown the node immediately after the last connection is closed.

**Comment by jeffreyscarpenter** [comment]
@jtgrabowski This issue as described doesn't seem to apply to open source Stargate. Can you re-create as an issue on riptano/cndb?

**Comment by jtgrabowski** [comment]
Sure. https://github.com/riptano/cndb/issues/6734
