### ISSUE TITLE
DSE docker image fails with no persistence backend found error

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2605]
When testing with a locally built copy of the DSE docker image, @tatu-at-datastax reported seeing this error message:

```
[SEVERE] Unexpected error: No persistence backend found for dse 6.8
java.lang.IllegalArgumentException: No persistence backend found for dse 6.8
```

**Comment by tatu-at-datastax** [comment]
Quick clarification: I was not (trying to at least) testing with locally built docker image. But I think this failure would likely also come up if that was what I did.
