### ISSUE TITLE
Maven `install package` does not work

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2636]
Currently the `./mvnw install package` does not work, due to the issue with the `microbench` project. The project has no classes in the `src/main` and thus the build fails.

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.2.0:jar (default-jar) on project microbench: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :microbench
Error: Process completed with exit code 1.
```

Seems that executing `install` or `package` independently works.

**Comment by ivansenic** [comment]
@tatu-at-datastax Any idea here how to solve? Tried multiple solutions, but it does not work.. The only idea I have is to have additional profile and exclude this module by default..

**Comment by jeffreyscarpenter** [comment]
Maybe consider not making this its own module. If the purpose of this code for testing, could be made part of `testing-services` or `testing` module? Or perhaps part of `core`?

**Comment by tatu-at-datastax** [comment]
Ok so plugin update has no effect... but I can make build work with "negative inclusion" like:

    ./mvnw -DskipTests -pl '!microbench' clean install package

which I found via

https://blog.jdriven.com/2022/11/mastering-maven-exclude-modules-from-build/

so this is one option to resolve the problem I think.

**Comment by tatu-at-datastax** [comment]
Of all options, maybe moving contents under `testing` makes most sense in the end?

**Comment by jeffreyscarpenter** [comment]
> Of all options, maybe moving contents under `testing` makes most sense in the end?

Agree, let's do this.

**Comment by tatu-at-datastax** [comment]
Done, moved under `testing`, along with README instructions.
