### ISSUE TITLE
Add vector CRUD support to REST API, happy path tests

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2653]
Since we added support for the experimental `vector` CQL data type in #2597, we can take advantage of this to add vector support to the REST API. This will also require documentation updates.

**Comment by tatu-at-datastax** [comment]
Updated title to indicate this is specifically about support to allow:

* Create Tables with Vector column(s)
* Insert, get, update and delete rows with Vector-valued columns
