### ISSUE TITLE
Add vector support to gRPC API 

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2654]
Since we added support for the experimental `vector` CQL data type in #2597, we can take advantage of this to add vector support to the gRPC API. This will also require documentation updates.

**Comment by tatu-at-datastax** [comment]
Note: PR #2678 contains what can likely be repurposed as implementation (Bridge gRPC is very similar to public gRPC API).

**Comment by tatu-at-datastax** [comment]
Suggested steps here:

1. Use changes that add `VectorCodec` implementation (and registration through `ValueCodecs`) from #2678 into `bridge` module as the base to change `grpc` module (i.e. make the same changes, just in different module)
2. Similarly use #2678 test changes (class `ValueCodecTest`) as the base for added unit test methods.
3. Skip `sgv2-quarkus-common` changes (that code is not duplicated)
4. Once `grpc` module has been modified, tests added and pass locally (these are unit tests so can be run with `./mvnw clean test`), create PR
5. CI hopefully passes (if not, need to figure out why, but if tests passed locally they should pass in CI
6. Get code review; if changes requested resolve these (either make change requested, or discuss on alternative to change)
7. Once one team member approves, merge!

**Comment by Hazel-Datastax** [comment]
#2722
