### ISSUE TITLE
REST Timestamp with additional fraction not accepted

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate#2674]
In the In-coordiator (DropWizard based) REST API, the timestamp of below format is accepted and the same fails in the Quarkus based REST API
```timestamp
2023-07-13T14:02:06.018850Z
```
**Steps to reproduce:**
1. Create table with a timestamp column

`/v2/schemas/keyspaces/testks1/tables`

```json
{
    "name": "employee1",
    "ifNotExists": false,
    "columnDefinitions": [
        {
            "name": "id",
            "typeDefinition": "int"
        },
        {
            "name": "name",
            "typeDefinition": "text"
        },
        {
            "name": "createdAt",
            "typeDefinition": "timestamp"
        }
    ],
    "primaryKey": {
        "partitionKey": [
            "id"
        ]
    },
    "tableOptions": {
        "defaultTimeToLive": 0
    }
}
```

2. Insert a record

`/v2/keyspaces/testks1/employee1`

```json
{
    "id": 123,
    "name": "emp2",
    "createdAt": "2023-07-13T14:02:06.018850Z"
}
```

In DropWizard REST API, it is working without any error and while getting back the row, we could see the last three 3 digits got truncated and returned as below

`/v2/keyspaces/testks1/employee1/123`

```json
{
    "count": 1,
    "data": [
        {
            "name": "emp2",
            "createdAt": "2023-07-13T14:02:06.018Z",
            "id": 123
        }
    ]
}
```
In Quarkus based REST API, the request to insert fails with below error
```json
{
    "description": "Invalid path for row to create, problem: Failed to deserialize field 'employee1.createdAt', problem: Text '2023-07-13T14:02:06.018850Z' could not be parsed, unparsed text found at index 23",
    "code": 400,
    "grpcStatus": null,
    "internalTxId": null
}
```

**Comment by tatu-at-datastax** [comment]
I suspect this is related to fix for #2223 (via PR #2241): probably need to figure out DateTimeFormat that allows more fraction digits.
