### ISSUE TITLE
Table already exists 500 instead of 409

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate#2679]
In the REST API, when we create a table with `ifNotExists` flag set to `false` and if the table already exists, the API returns below response with 500 return code instead of a 409

API
```
/v2/schemas/keyspaces/{KeyspaceName}/tables 
```

Request
```json
{
  "name": "testprod1",
  "primaryKey": {
    "partitionKey": [
      "id"
    ],
    "clusteringKey": []
  },
  "columnDefinitions": [
    {
      "name": "id",
      "typeDefinition": "text"
    },
    {
      "name": "name",
      "typeDefinition": "text"
    }
  ],
  "ifNotExists": false,
  "tableOptions": {
    "defaultTimeToLive": 0,
    "clusteringExpression": [
      {
        "column": "string"
      }
    ]
  }
}
```

Response

```json
{
    "description": "Unhandled gRPC failure (Status.Code.ALREADY_EXISTS->500): ALREADY_EXISTS: Cannot add already existing table \"testprod1\" to keyspace \"testks1\"",
    "code": 500,
    "grpcStatus": "ALREADY_EXISTS",
    "internalTxId": null
}
```

**Comment by tatu-at-datastax** [comment]
Sounds like wrong failure code, yes.

@kathirsvn Which persistence backend was this with? C-4.0?

**Comment by kathirsvn** [comment]
I tested in Astra, I guess it should be the same behavior for all backends.

**Comment by tatu-at-datastax** [comment]
@kathirsvn Ok. I hope so as then we could add an IT here in Stargate repo.

**Comment by tatu-at-datastax** [comment]
@kathirsvn Yes, I am able to reproduce easily; looks like Bridge gRPC failure not properly mapped to 409. Probably affects other resources too.
