### ISSUE TITLE
GraphQL: fix handling of DATE type

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#268]
`CustomScalar.DATE` uses the following to parse GraphQL values:
```java
o -> java.sql.Date.valueOf(o.toString())
```

This is not going to work. That value is later passed to `QueryBuilder.literal()`, which uses the default Java driver mappings. DATE maps to `java.time.LocalDate`, not `java.sql.Date`.

**Comment by jorgebay** [comment]
I'll do it as part of scalar revisit #272 and validation #261
