### ISSUE TITLE
Consider simpler alternative to Apollo library for GraphQL ITs

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#270]
Adding new GraphQL integration tests involves a lot of ceremony:
* update the relevant `schema.json`. The simplest way to do that is to start a standalone Stargate instance and backend, create the schema manually, and run an introspection query.
* create new `*.graphql` files to add queries.
* run the build to generate the Java code from those files.
* the Apollo query API is convoluted: execute the query to get an "observable", create a future, enqueue the future on the observable, wait for the future to complete, then cancel the observable.

(see also comments in `GraphQlTest`)

I wouldn't mind writing my queries directly into Java strings (as it's done in unit tests such as `QueryFetcherTest`). Then we should be able to use any HTTP library to wrap that into a REST query. I'm less sure about inspecting the results, but maybe we can find an easy way to parse the response into maps of maps.

**Comment by dougwettlaufer** [comment]
Agreed, it's not ideal but I went with the Apollo client for a few reasons

1. It seems to be the de facto client for graphql in java
2. Wanted to provide examples of queries and how to work with graphqlapi in a more realistic manner
3. Graphql over plain http is kind of ugly, it looks like json but its not plus you have to figure out how to serialize results into objects for assertions
4. Similar to #2 wanted to also validate that our graphql api actually works with a real client.

Not against making things easier but just some thoughts.

**Comment by olim7t** [comment]
Thanks for the explanations, makes sense.

Maybe we can have one test with Apollo, and the rest with a more lightweight alternative.

**Comment by olim7t** [comment]
I used the "lightweight" approach in `GraphqlJWTAuthTest`: GraphQL queries are passed as plain strings, and the test uses `OkHttpClient` to wrap them into a REST request. This can be used as a template for future tests.
