### ISSUE TITLE
Delay event dispatch from release workflows until assets available in maven

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2721]
The release workflows for v2 and v2.1 dispatch events to other repositories to help automate updating dependencies. There are corresponding workflows in downstream repositories to handle these events and create PRs to update the version. However these downstream workflows frequently fail because Stargate artifacts aren't yet available in Maven central. Lately it has been taking as much as 15 minutes for the jars to show up. 

We should add a check to the Stargate release workflows to wait to dispatch events until the jars for the release are available. It should check once every minute or two. We can set some kind of reasonable limit on max wait time like 20 or 30 minutes.

**Comment by tatu-at-datastax** [comment]
I think this was resolved another way, by making receiving task try update until dependency available.

@jeffreyscarpenter can this be closed?

**Comment by jeffreyscarpenter** [comment]
Yes that makes sense
