### ISSUE TITLE
Log Quarkus API Request Body for debugging

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate#2730]
The reactive resteasy Quarkus plugin that we use for building the REST API doesn't have a way to log the payload received in a request and this makes debugging hard at times.

**Comment by tatu-at-datastax** [comment]
We should do this so it is changeable for either smaller scopes (for specific DB/tenant, or per-request) or dynamically enabled (enable for limited amount of time) so as not have to turn it on for all requests all the time, requiring restart.
