### ISSUE TITLE
Add support for CQL analyzers

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/stargate#2763]
CQL analyzers are now available in `datastax/cassandra` fork and Astra Vector DB ([docs](https://docs.datastax.com/en/astra-serverless/docs/vector-search/using-analyzers.html)).

Let's add support to the `persistence-dse-next` module including tests.

**Comment by jeffreyscarpenter** [comment]
This will require updating the hash we point to from `datastax/cassandra`.

**Comment by tatu-at-datastax** [comment]
Is this for `dse-next` persistence backend?

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter #2771 will update `dse-db-all` to latest build as of today so that part might be taken care of.

Would the tests here mean CQL tests (for Coordinator), similar to basic Vector tests? And optionally I guess for gRPC too?
