### ISSUE TITLE
add our own logic expression classes

### ISSUE THREAD

**Issue by Yuqi-Du** [stargate/stargate#2812]
Jbool library support logic operations, but will use hashcomparator to sort all child expression.
which leads to JSON API unit tests fail (ValidatingStargateBridge)

**Comment by tatu-at-datastax** [comment]
Could you elaborate a bit more on what is happening (why do we have test failures), and about suggested solution? (replace `Jbool_expressions` with straight-forward custom implementation or... ?)

**Comment by Yuqi-Du** [comment]
Thanks, Tatu, I have attached explanations here  https://github.com/stargate/stargate/pull/2815
