### ISSUE TITLE
Document API unit tests are not run by CI because they still use JUnit 4 features

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#283]
Powermock/Mockito versions are ones that are compatible with JUnit 4, however the runner for CI is now JUnit 5. So the unit tests can be run locally, but do not get picked up and run by CI.

**Comment by EricBorczuk** [comment]
Followup: Is there even a version of Powermock that is compatible with JUnit 5?

**Comment by dougwettlaufer** [comment]
Looks like you can use a JUnit 4 runner?
https://github.com/powermock/powermock/issues/929

**Comment by dougwettlaufer** [comment]
@dimas-b didn't you fix this?

**Comment by dimas-b** [comment]
This is fixed by #527
