### ISSUE TITLE
GraphQL mutations with @atomic directive and TTL are not persisted

### ISSUE THREAD

**Issue by marksurnin** [stargate/stargate#2875]
Hi Stargate team,

We've encountered a potential bug in Stargate v2. Atomic mutations (logged batches) with any number of mutations that use TTL are not persisted. Moreover, Stargate responds with `"applied": true` for those mutations, which is misleading. I've reproduced this in the v2 images `stargateio/coordinator-4_0:v2` and `stargateio/graphqlapi:v2`, as well as on the v2.1 branch.

Request (using the standard data_endpoint_auth keyspace):
```
mutation insert_atomic_ttl @atomic {
  m1: inserttoken(
    value: {
      auth_token: "12735332-b914-11ee-a506-0242ac120002"
      username: "2a"
    }
    options:{ttl:86400}
  ) {
    applied
  }
  m2: inserttoken(
    value: {
      auth_token: "15cdf1e0-b914-11ee-a506-0242ac120002"
      username: "2b"
    }
    options:{ttl:86400}
  ) {
    applied
  }
}
```

Response
```
{
  "data": {
    "m1": {
      "applied": true
    },
    "m2": {
      "applied": true
    }
  }
}
```

Subsequently querying data_endpoint_auth.token table shows that no rows have been inserted. Note that rows are persisted correctly as long as I use _either_ `@atomic` directive or `ttl` in the mutations.

I haven't found the root cause of the failed mutation but it's concerning that `applied: true` and it's not persisted. This used to work in v1. Do you know what could be causing this? Thanks!

**Comment by marksurnin** [comment]
Some troubleshooting findings:
- I'm aware of special handling of `@atomic` mutations in [MutationFetcher.java](https://github.com/stargate/stargate/blob/9193a19a888ae602a2cbbe66511c0db203038982/apis/sgv2-graphqlapi/src/main/java/io/stargate/sgv2/graphql/schema/cqlfirst/dml/fetchers/MutationFetcher.java#L59C1-L63C6). However, this kicks in if the number of selections (i.e. mutations is > 1) but I've reproduced this behavior even in a single mutation with `@atomic` and TTL.
- I've debugged Cassandra [BatchMessage](https://sourcegraph.com/github.com/apache/cassandra@2a4cd36475de3eb47207cd88d2d472b876c6816d/-/blob/src/java/org/apache/cassandra/transport/messages/BatchMessage.java?L232) code too and I see the ttl value present as an attribute on the statement as seen in the screenshot. As a side note, this method returns `EMPTY_RESULT` regardless of whether I pass TTL or not (which also at the moment determines whether the mutation has actually been persisted).
![Screenshot 2024-01-22 at 3 11 49 PM](https://github.com/stargate/stargate/assets/5126685/923b02ba-6ddb-4ca6-bf23-2ec09d1c3ff7)

**Comment by marksurnin** [comment]
Further investigation showed that in v2 all mutations with the `@atomic` directive insert rows with timestamp `1970-01-01T00:00:00Z` if not otherwise specified in the query. TTL is computed relative to the write timestamp, so passing `options:{ttl:86400}` would result in a TTL timestamp of 1970-01-02.

Cassandra interprets such rows as having already expired (since they supposedly TTL'ed out back in 1970) and thus omits them from the results. I verified this in the commitlog and sstables using `sstabledump`. Moreover, this row would eventually expire, likely after a major compaction. Please see [mutations.txt](https://github.com/stargate/stargate/files/14114688/mutations.txt) and [sstabledump.txt](https://github.com/stargate/stargate/files/14114687/sstabledump.txt) attached.

```
"liveness_info" : { "tstamp" : "1970-01-01T00:00:00Z", "ttl" : 86400, "expires_at" : "1970-01-02T00:00:00Z", "expired" : true },
"cells" : [
  { "name" : "username", "value" : "2b" }
]
```

***

**Root cause details**
1.  [query.proto](https://github.com/stargate/stargate/blob/0326abb5a7c9fe22e1257d2a0f074b91562da0d7/coordinator/bridge-proto/proto/query.proto#L576-L585) defines `timestamp` and `now_in_seconds` as `google.protobuf.Int64Value timestamp = 4;`. If this value is null invoking the generated `com.google.protobuf.Int64Value getTimestamp()` method returns 0. This is because it's serialized to 0 by default if it is unset.
2. In [StargateGraphqlContext.java#L145-L147](https://github.com/stargate/stargate/blob/0326abb5a7c9fe22e1257d2a0f074b91562da0d7/apis/sgv2-graphqlapi/src/main/java/io/stargate/sgv2/graphql/web/resources/StargateGraphqlContext.java#L145-L147) the `toBatchParameters` method sets `timestamp` and `nowInSeconds`:
```
.setTimestamp(queryParameters.getTimestamp())
.setNowInSeconds(queryParameters.getNowInSeconds())
```
Inspecting these with a debugger shows that at runtime the `timestamp` field is null ([screenshot](https://github.com/stargate/stargate/assets/5126685/25d1c059-2811-492a-8358-7b453d62ffdd)) but invoking `getTimestamp` returns 0 as mentioned in step 1 ([screenshot](https://github.com/stargate/stargate/assets/5126685/2567617d-da2d-4cdd-89c5-e380899c999e)).

3. At the coordinator bridge level these 0 values are passed to the actual query in [BatchHandler.java](https://github.com/stargate/stargate/blob/0326abb5a7c9fe22e1257d2a0f074b91562da0d7/coordinator/bridge/src/main/java/io/stargate/bridge/service/BatchHandler.java#L153-L159). This explains the write timestamp being `1970-01-01T00:00:00Z`.
```
if (parameters.hasTimestamp()) {
  builder.defaultTimestamp(parameters.getTimestamp().getValue());
}

if (parameters.hasNowInSeconds()) {
  builder.nowInSeconds(parameters.getNowInSeconds().getValue());
}
```
***

This can be fixed by changing [StargateGraphQLContext's toBatchParameters](https://github.com/stargate/stargate/blob/0326abb5a7c9fe22e1257d2a0f074b91562da0d7/apis/sgv2-graphqlapi/src/main/java/io/stargate/sgv2/graphql/web/resources/StargateGraphqlContext.java#L141-L151) method to set `timestamp` and `nowInSeconds` only if they are non-null. This takes advantage of the generated `hasTimestamp` method that makes batch parameters' `timestamp` field behave similar to an Optional.
```
private BatchParameters toBatchParameters(QueryParameters queryParameters) {
  BatchParameters.Builder builder =
    BatchParameters.newBuilder()
      .setConsistency(queryParameters.getConsistency())
      // omitted a few lines
      .setSkipMetadata(queryParameters.getSkipMetadata());
  
  if (queryParameters.hasTimestamp()) {
    builder.setTimestamp(queryParameters.getTimestamp());
  }
  if (queryParameters.hasNowInSeconds()) {
    builder.setNowInSeconds(queryParameters.getNowInSeconds());
  }
  return builder.build();
}
```

**Comment by jeffreyscarpenter** [comment]
@kathirsvn can you review/comment?

**Comment by kathirsvn** [comment]
Sorry for the delay, I was out on a vacation.
This analysis for the bug sounds reasonable to me. Great find @marksurnin. It seems that the introduction of proto definitions (for the gRPC bridge) in the v2 code base introduced this bug.
