### ISSUE TITLE
Clarity around Stargate v1 and EOL

### ISSUE THREAD

**Issue by mamccorm** [stargate/stargate#2898]
The documentation makes it clear that Stargate v1 is EOL, in particular, heres a snippet:

> We anticipate supporting a major version number release N for one year after the subsequent major version number release (N+1), or until the major version number release (N+2), whichever comes first. For example, v1 will be supported until when Stargate v3 is released, but no later than October 2023 

> "but no later than October 2023"

This lined up with the Git releases, as there had been no v1 updates for quite some time. However, ~2 weeks ago, there seemed to be a number of fixes rolled back into v1, and a release was cut. However the docs still make it clear that Stargate v1 is EOL.

Do you expect to take Stargate v1 out of EOL status, or was this just a once-off back-release? And if the former, will the support policy be amended?

Many thanks

**Comment by xnox** [comment]
i am curious if it is a shared user.

**Comment by mamccorm** [comment]
There were multiple v1 releases mid-year. Any changes on v1 EOL status?

**Comment by jeffreyscarpenter** [comment]
> Any changes on v1 EOL status?
No, we have not made changes here.
