### ISSUE TITLE
Scylla support

### ISSUE THREAD

**Issue by Hammad1029** [stargate/stargate#2916]
Can anyone confirm if the data gateway (more specifically the rest and docs API) work with ScyllaDB? Scylla is a dropin replacement for Cassandra 3.X so I'm assuming it does but I found reports online saying otherwise.

**Comment by tatu-at-datastax** [comment]
Stargate has not been tested against non-Cassandra databases, nor is it designed to work with any, so you would need to test this yourself (against C-3.11 backend).
