### ISSUE TITLE
Expose REST API for config-store

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#301]
Once the https://github.com/stargate/stargate/issues/300 is done, we should expose a REST API that will be the main integration point for clients. 
The REST API can be used using simple curl, but we may decide to build a GUI based on it in the future.
The rest-api should reside in the new module, i.e: `config-store-restapi`

**Comment by tatu-at-datastax** [comment]
I don't think there are plans to use config-store at this point: due to Stargate V2, move to Quarkus, configuration aspects will be re-evaluated. Closing the issue as obsolete.
