### ISSUE TITLE
Config-Store API supports overriding settings

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#302]
We need to decide on the hierarchy and priority of configuration. 
We can use a similar pattern to https://docs.spring.io/spring-boot/docs/1.0.1.RELEASE/reference/html/boot-features-external-config.html.
The setting from the config store may have the lowest priority. It can be overridden at lower levels (i.e., YAML file, Java System properties, Command line arguments, etc.). We need to decide how many levels of overriding do we want to support.
There is one caveat here because once we support overrides, the GUI/REST will not reflect the actual value loaded by the extension (if it provides its own override). We would need to educate our users about it.

It has one drawback: if the setting is provided at the lowest level (i.e., system override), we cannot change it at the runtime.
We could solve it by having a "get if not present in config-store" semantic. If the setting is not set in the config-store, then take the lowest level setting. If it is set in the config-store, take the config-store setting ignoring the system override. 

Both approaches have different semantics, and we need to decide which one do we want to support.

**Comment by tomekl007** [comment]
1. I think that we can achieve both goals by inverting priorities.
All settings from the config-store will have the highest priority. In the current design, it is the `stargate-config.yaml` mounted by the k8s. 
The lower priority will have settings that are set using `System.setProperty`. If they are set, and the setting is not present in the `stargate-config.yaml` they will be taken into account - that will be a current situation.
If someone wants to override those at runtime, it will be possible via the `stargate-config.yaml` file.

At some point, we can migrate settings to the `stargate-config.yaml` - that will have a higher priority.
So to sum up:
1. P0 - settings from config store.
2. P1 setting from `System.setProperty`
3. P3 environment variable using `System.getenv`

It seems that the spring cloud does a similar thing for priorities of settings:
https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_context_application_context_services.html

If we decide that this is a correct solution, it will mean that all `System.getProperty` should be migrated to use the config-store instead. For example, in `CassandraPersistenceActivator`:
```
String clusterName = System.getProperty("stargate.cluster_name", "stargate-cassandra");
```
will be replaced with:
```
String clusterName = Optional.ofNullable(configStore.getConfigForModule("stargate").get("cluster_name")).orElse("stargate-cassandra");
```
to have the same read path (through config-store API) for every setting. (It can be done in a separate ticket)

2. We need to decide if this mechanism should support loading the `*.yaml` (or/and `*.properties,` `*.json`) files. They can be present in the `stargate` repository for every extension and can provide additional settings.
This would be a similar mechanism to spring-based application. 
For example, the `extension` can have its own `application.yaml` with properties there should be loaded via our config-store. It means that we would need to add one more override level and the logic for loading various files in the config-store:

1. P0 - settings from config store.
1. P1 - settings from specific extension `application.yaml`.
2. P2 setting from `System.setProperty`
3. P3 environment variable using `System.getenv`

I don't see any existing extension using this pattern, and I am unsure if we want to add this possibility now. (but we have dropwizard `config.yaml` - see the next section)
All java frameworks are supporting this, and it may be a user-friend to provide this ability. Maybe the lack of this mechanism is why we are using System properties extensively in the stargate?

3. Handling of `config.yaml` used by the Dropwizard server.
Currently, every extension that starts the HTTP server has its own `config.yaml` file. To make the config mechanism unified, we may consider loading this file via the `config-store` (in the way that is described in the previous section). Then we would need to build the `io.dropwizard.Configuration.ApplicationConfiguration` based on config-store values and pass it to the
`Server#initialize`. By doing so, we can unify the config mechanism across all direct usages of `config.yaml`.

Please let me know wdyt (CC @dougwettlaufer, @olim7t)

**Comment by dougwettlaufer** [comment]
> 1. Inverting Priorities

I don't think we want to invert priorities, typically you want the command line arg or system prop to win so that you can do more specific overrides. Take for example log level. For the sake of argument let's say we're storing that in the config store and you want to troubleshoot a specific stargate instance. Now you don't want to set all the instances to debug, just the one. If configstore wins then you won't be able to override for the single node and will instead have to update all of them. 

> 2. Supporting config file per extension

Personally I think a single file would be much easier to deal with. Looking at all of the config at once is faster than jumping between multiple files. The only reason we have config.yaml in some of our modules is specifically for dropwizard, the framework rather than the module is looking for a file.


> 3. Handling of config.yaml used by the Dropwizard server.

I like the idea but again I'd suggest a single file. This is a good example of my previous point in that in order to know what service is running on what port you have to jump between multiple files. If they can all use the configstore and it uses a single file then we'd have a one stop shop to know all of our ports.

**Comment by tomekl007** [comment]
1.
Ok, I agree that a solution without inverting priorities gives more flexibility. We still may consider moving system properties to the main config file at some point.
2 & 3.
I've created a new issue to handle that: https://github.com/stargate/stargate/issues/331

**Comment by tomekl007** [comment]
Implemented in: https://github.com/stargate/stargate/pull/305/commits/a481d9596683357f69384a470ca07c7dd9c7f8cc
