### ISSUE TITLE
Config Store - Mechanism for supporting reload of settings at the runtime

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#303]
We need to allow clients of the config-store to see the latest change.
We can implement it using one of these two approaches:
1) "pull" mode: the client will refresh the setting value at regular intervals
2) "push" mode: listener api where clients subscribe to the setting change modification.

If we want 1, we should be ok with a cache. Client’s are interacting with the config-store using the ConfigStore interface so that we can hide the cache implementation there. The refresh interval can be exposed using the config-store API, registering default to for example 1 second.

If we want 2, we need a thread that polls the config for changes, an event API, etc. It's more complicated and maybe not needed for a V_1

**Comment by tomekl007** [comment]
After some more thoughts, I think we may not need to implement any strategy for reloading from the YAML config store.
The `ConfigStoreYaml#getConfigForModule(String)` loads the underlying `stargate-config.yaml` file every time its called. Because of that, the caller will get the fresh version of it every time it's accessed. It's up to the caller to decide when this method should be called. If the `ConfigStoreYaml` client needs to have runtime reload, it should call `getConfigForModule` every time the settings are accessed.

On the other hand, reading the file every time may be problematic from the performance perspective:
```
Map<String, Map<String, Object>> result =
          mapper.readValue(configFilePath.toFile(), yamlConfigType);
```
and we may consider adding a cache atop of it. I've created a simple JMH micro-benchmark comparing loading the file every time this method is called versus caching the file for 30 seconds (exact duration yet to be decided):
```

@Fork(1)
@Warmup(iterations = 5)
@Measurement(iterations = 10)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
public class ConfigStoreYamlBenchmark {
  private static final int NUMBER_OF_ITERATIONS = 100_000;


  @Benchmark
  public void directLoad(Blackhole blackhole) {
	  // given
	  Path path =
			  Paths.get(
					  Objects.requireNonNull(getClass().getClassLoader().getResource("stargate-config.yaml"))
							  .getPath());
	  ConfigStoreYaml configStoreYaml = new ConfigStoreYaml(path);

	  for(int i = 0; i < NUMBER_OF_ITERATIONS; i++) {


		// when
		ConfigWithOverrides configForModule1 = configStoreYaml.getConfigForModule("extension-1");
		ConfigWithOverrides configForModule2 = configStoreYaml.getConfigForModule("extension-2");

		// then
		blackhole.consume(configForModule1);
		blackhole.consume(configForModule2);
	}
  }

	@Benchmark
	public void loadWithCache(Blackhole blackhole){
		// given
		Path path =
				Paths.get(
						Objects.requireNonNull(getClass().getClassLoader().getResource("stargate-config.yaml"))
								.getPath());
		ConfigStoreYaml configStoreYaml = new ConfigStoreYaml(path);

		for(int i = 0; i < NUMBER_OF_ITERATIONS; i++) {

			// when
			ConfigWithOverrides configForModule1 = configStoreYaml.getConfigForModuleWithCache("extension-1");
			ConfigWithOverrides configForModule2 = configStoreYaml.getConfigForModuleWithCache("extension-2");

			// then
			blackhole.consume(configForModule1);
			blackhole.consume(configForModule2);
		}
	}

}
```

The results show that there is a huge difference between both approaches:
```
Benchmark                               Mode  Cnt      Score     Error  Units
ConfigStoreYamlBenchmark.directLoad     avgt   10  10486.425 ± 287.736  ms/op
ConfigStoreYamlBenchmark.loadWithCache  avgt   10     32.270 ±   0.465  ms/op
```

If the callers expect runtime changes, they will need to call the `getConfigForModule` every time any setting is accessed. 
Caching seems to be very important from the performance perspective. 
However, we need to remember and document that It will slow down the propagation of changes from the underlying `stargate-config.yaml`.
Are we ok with that? wdyt (@dougwettlaufer @dimas-b)

**Comment by dimas-b** [comment]
Caching the file SGTM :+1: 

It may still be useful to have a notification API for services that do not request configs periodically, but still want to reload settings when they change. I suppose something simple like a CRC32 on the whole file with periodic background checks should be fine. WDYT?

**Comment by dimas-b** [comment]
A bit tangential: What if we unregisterd and re-registered the config service for each time the file changes? This way dependent modules receive config registered/unregistered notifications from the OSGi framework and restart as appropriate.

**Comment by tomekl007** [comment]
> A bit tangential: What if we unregistered and re-registered the config service for each time the file changes? This way, dependent modules receive config registered/unregistered notifications from the OSGi framework and restart as appropriate.

I think it is a bit too much to restart the whole service when the config-store file changes. It may be quite frequently, and also not every setting change means that we need to restart the whole service. If there are settings that can be changed at runtime, then by definition, they should not require restarting the whole service, isn't it? 

I was also thinking about using the OSGi lifecycle - it is described in the design doc).
However, I think that it's better to decouple the config-store from the OSGi API. It may be feasible, but I think that currently, we may not need it. If it turns out that most settings require restarting the module, maybe we can consider it again, wdyt?

**Comment by tomekl007** [comment]
> Caching the file SGTM 👍
> 
> It may still be useful to have a notification API for services that do not request configs periodically, but still want to reload settings when they change. I suppose something simple like a CRC32 on the whole file with periodic background checks should be fine. WDYT?

Yes, listener API would be nice but I think that we agreed that we don't need it for V_1.
If we will pick a low refresh interval (i.e. 30 seconds) and clients will access every config setting directly through `getConfigForModule` method it should be enough for first use cases, wdyt?

**Comment by dimas-b** [comment]
>  I think that it's better to decouple the config-store from the OSGi API. It may be feasible, but I think that currently, we may not need it. If it turns out that most settings require restarting the module, maybe we can consider it again, wdyt?

Dependent services still have the flexibility to reload config from the new service instance without restarting themselves. OSGi does not mandate dependent service restarts or dependency changes, AFAIK.

**Comment by dimas-b** [comment]
> Yes, listener API would be nice but I think that we agreed that we don't need it for V_1.

This is beyond my knowledge :) @dougwettlaufer WDYT?

**Comment by tomekl007** [comment]
> > Yes, listener API would be nice but I think that we agreed that we don't need it for V_1.
> 
> This is beyond my knowledge :) @dougwettlaufer WDYT?

Please refer to the design doc and discussion about the runtime reload.

**Comment by dimas-b** [comment]
I'm getting a bit confused :) I'd be ok with not supporting config reload in V_1 completely, but if we support config reload in principle (which is what this issue is about) then why not support notifications at the same time? If we do not support change notifications in the config service, then all its clients will have to implement polling (assuming the clients do not have natural event that prompt for config reload). It seems to be that this is going to be a common use case, so it would be worth implementing in the config service itself.

**Comment by dougwettlaufer** [comment]
For v1 we create the barebones version of "pull your config and cache it if you know it's static, read the file every time if you're expecting changes". Then for v2 we can come in and get fancy with the listeners. Right now we don't have anything that _must_ to do runtime config reload.

I'd prefer to get a flexible config store up and running so we can get the kafka producer out the door and then we can come back in and iterate on nice to have features like config change notification and such.

**Comment by dimas-b** [comment]
SGTM... however, if we do not expect config reload in v1 in runtime, then perhaps we do not need the cache :thinking:

**Comment by tomekl007** [comment]
I agree that cache is not needed from the perspective of runtime reload. I will create a different ticket and implement it separately. 
We can leave this task for V_2

**Comment by tatu-at-datastax** [comment]
I don't think this would work (or necessarily be beneficial) for Stargate V2; but if so would be designed as part of that process. Closing this issue as related to SGv1 architecture which will be in maintenance mode.
