### ISSUE TITLE
Merge Dropwizard `config.yaml` files into one stargate config

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#331]
Currently, every extension that starts the HTTP server has its own `config.yaml` file. To make the config mechanism unified, we may consider loading this file via the config-store. Then we would need to build the io.dropwizard.Configuration.ApplicationConfiguration based on config-store values and pass it to the
Server#initialize. By doing so, we can unify the config mechanism across all direct usages of `config.yaml`

After some discussion:
https://github.com/stargate/stargate/issues/302#issuecomment-716978037
It seems that we should merge all `config.yaml` into one `stargate-config.yaml` that is loaded using `config-store-yaml`.
So for example the content of `config.yaml` in the `auth-api` module will be moved to the main `stargate-config.yaml` under a dedicated section (for example `auth-api`) and loaded using the same mechanism.

**Comment by tatu-at-datastax** [comment]
Due to Stargate V2 refactoring, move to Quarkus, this issue is obsolete. We will need to design configuration Quarkus use in mind.
