### ISSUE TITLE
Migrate direct usages of `System.getProperty()` to config store API.

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#332]
Currently, we are using `System.getProperty` directly in multiple places. They should be migrated to use the config-store API instead. For example, in CassandraPersistenceActivator:
```
String clusterName = System.getProperty("stargate.cluster_name", "stargate-cassandra");
```
it should be replaced with:
```
String clusterName = Optional.ofNullable(configStore.getConfigForModule("stargate").get("cluster_name")).orElse("stargate-cassandra");
```
to have the same read path (through config-store API) for every setting.

**Comment by dougwettlaufer** [comment]
Are we replacing all of them or are we keeping things like `System.getProperty("os.arch")`?

**Comment by tomekl007** [comment]
> Are we replacing all of them, or are we keeping things like `System.getProperty("os.arch")`?

It is yet to be decided but replacing static initializers that are using properties maybe not feasible.

**Comment by tatu-at-datastax** [comment]
We may want to move away from direct System.getProperty() usage (... although it is rather prevalent by now). But not by using config-store API, rather use Quarkus facilities.
