### ISSUE TITLE
Parallelize integration tests for each backend

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#334]
Integrations tests (in the `testing` module) do not appear to be CPU intensive, but they take a long time to run (35-40 min for each backend type).

We could try running them in parallel even given a specific backend.

One way to do this is to start two (or more) jobs in the GCB build for each backend and run a portion of the tests there. Since each job is running inside a docker container, port conflicts should not be a problem.

We could implement `org.junit.jupiter.api.extension.ExecutionCondition` in our `ExternalStorage` extension to suppress some of the tests and allow others to run. Using something like `CRC32 mod N` on the test class name should allow selecting tests into one of the containers automatically.

**Comment by dougwettlaufer** [comment]
@dimas-b is our current test execution setup what you had in mind for this issue?

**Comment by dimas-b** [comment]
Actually, I meant to try and run two (or more) test jobs for _each_ backend (C* 3.11, 4.0, DSE) to as to reduce test time even more.
