### ISSUE TITLE
Stargate for SQL Doccumentation

### ISSUE THREAD

**Issue by rvald26** [stargate/stargate#380]
Hi Team,

The documentation mentions support for SQL (example below) several times. However, I could not find any documentation for this. Only for CQL but no information about SQL. Could you please point me in the right direction?

![image](https://user-images.githubusercontent.com/37116247/98285920-3839a700-1f71-11eb-81af-fcf597d2418d.png)

Example:
https://stargate.io/2020/09/14/init-stargate.html

Thank you and best regards,

**Comment by dougwettlaufer** [comment]
Hi @rvald26,

SQL is still in active development and lives here https://github.com/stargate/stargate/tree/feature-sql. 

I'm sure @dimas-b would be happy to help you out if you have any specific questions.

**Comment by rvald26** [comment]
Thank you for the quick response @dougwettlaufer . We are planning to develop some solutions on top of this in the future. Is there an expected release date? Also, are you accepting contributors?

**Comment by rvald26** [comment]
Nevermind I just saw your community page. We'll signup. Thank you

https://stargate.io/community

**Comment by dougwettlaufer** [comment]
Yes, we're always interested in contributors @rvald26. You can also come chat with us in our [Discord server](https://discord.gg/GravUqY) if you're interested.

**Comment by dimas-b** [comment]
@rvald26 : yes, we're very interested in feedback (and contributions) regarding SQL. So if you have any particular use cases to discuss we're open to it. The `feature-sql` branch is usable in an "experimental" setting, but not ready for production at this time. It's got README files that are hopefully helpful as a getting started guide.

**Comment by tatu-at-datastax** [comment]
At this point SQL backend is not supported so adding documentation does not make sense. If and when there are concrete plans, documentation would definitely be part of dev/release process; would re-file this issue.
Until then closing to clean up our backlog.
