### ISSUE TITLE
Migrate all existing activators to use the `BaseActivator`

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#381]
In the https://github.com/stargate/stargate/pull/370
we implemented a generic mechanism for managing the activator's lifecycle.
I migrated 3:`ConfigStoreActivator`, `GraphQlActivator` and `HealhCheckActivator`
as a point of reference.
As part of this issue, we should migrate all other existing activators.
It should be done separately because all other activators have no unit or integration tests, so migrating them will require a substantial amount of manual testing.

**Comment by mpenick** [comment]
Thanks for doing this @tomekl007

**Comment by tomekl007** [comment]
fixed by: https://github.com/stargate/stargate/pull/436
follow up ticket: https://github.com/stargate/stargate/issues/443
