### ISSUE TITLE
Allow for restarting target service in the OSGi without need to restart the whole stargate.

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#382]
In the `BaseActivator` (and all other existing activators) we are registering the target service only at the start of the stargate lifecycle.
We can implement the hot-reload that will allow us to stop and restart service during the OSGi lifecycle.
It can also allow us to start the service later (not at the stargate startup).
For more information see this discussion: https://github.com/stargate/stargate/pull/370#discussion_r517471939

**Comment by tatu-at-datastax** [comment]
Since we will be extracting services out of Coordinator nodes (and OSGi....), this is no longer something we plan on doing.
