### ISSUE TITLE
GraphQL: Use local quorum as default consistency level

### ISSUE THREAD

**Issue by jorgebay** [stargate/stargate#388]
When unset, we are using the driver default: `ONE`.

We should use `LOCAL_QUORUM` instead.

**Comment by josh-mckenzie** [comment]
Given the risk of data loss in a multi-DC env w/LOCAL_QUORUM, is there a way for us to surface in the API / docs / msg on write / ? for users that are LQ vs. Q vs. EQ in a multi-DC env?

Thinking along lines of "how to educate users through the product API".

**Comment by jorgebay** [comment]
> is there a way for us to surface in the API / docs / msg on write

hm... We can add API documentation to the consistency level on GraphQL, REST or doc sides, but besides thatI can't think of something else.
