### ISSUE TITLE
Add support for nullish operations

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#393]
Such as: `$exists: false, $eq: null`

Most probably these will be "limited support" operations when SAI is not in the schema - not sure if SAI being present would actually help here!

**Comment by polandll** [comment]
Ah, that's why `$eq: null` didn't work when I tried it last night - it's not implemented. :-)

**Comment by msmygit** [comment]
Using `GET` with `{"foo.bar":{"$in":[null]}}` helped achieve this!

**Comment by EricBorczuk** [comment]
Yep that's a valid workaround! I will update this issue to remove the need for adding $in support as it already exists.

Still, would be way more ergonomic to allow exists/eq, more intuitive imo (and fewer characters!)

**Comment by ivansenic** [comment]
@EricBorczuk I ll take this as agreed.

**Comment by ivansenic** [comment]
For now all the work on this issue is suspended. We will not take any further actions. Please use the `$in` alternative, but be aware that if this is the only condition it can result in the full table scan.

**Comment by jeffreyscarpenter** [comment]
not planned
