### ISSUE TITLE
Add support for setting the TTL for a column value on POST in REST API implementation

### ISSUE THREAD

**Issue by jnorrid** [stargate/stargate#394]
With CQL, we have the option to perform an INSERT to populate data into a table and subsequently, we can issue an UPDATE query to modify the TTL of one of the values for a specific column to enable auto-expiry within the database. This is useful for things like session, API or user tokens in user stores. It can also be valuable for timer values and other things. The CQL implementation is two steps (INSERT followed by an UPDATE). RESTful implementation might follow a similar pattern where data is POSTed and then a PUT could be issued to modify the TTL value for data in a column within a specific row.

**Comment by dougwettlaufer** [comment]
Hi @jnorrid, thanks for the feature request. 

I have really used TTLs so just trying to gauge wider interest. What would you say is the popularity of this feature? Is this something widely used or something that most people just handle in application code? Could the same functionality be accomplished from the user side with the existing table level TTL or are there enough specific use cases to warrant a column TTL?

Also, something that we need to consider when implementing is can this be applied in a generic manner? One of our goals is to avoid exposing "Cassandra-isms" in the APIs (admittedly v1 of the restapi didn't do a great job of this). The purpose of this being to allow people to get up and running with Stargate REST or Graphql without needing to know CQL.

cc: @ denisekgosnell

**Comment by jnorrid** [comment]
Hi Doug - control of TTL for rows and columns has been a feature of almost
every modern database for close to a decade now. Mongo, Cassandra, Influx
and even the Oracle RDBMS all have varying levels of support for it. It is
used heavily in fintech, telco and in the user stores for many popular
digital services (among many other use cases).

Not sure if it can be applied in a generic way - might need a bit of
exploration on that. I know Oracle, for example, only supports setting the
TTL for an entire row. Mongo provides support for row and column level TTL
settings to enable different levels of versatility. Nearly all of the NoSQL
implementations I have seen implement their TTL functionality as part of
UPDATE or UPSERT operations as opposed to being able to do this at INSERT
time. Cassandra has support for either overriding the default TTL for an
entire table within a keyspace (which is not what I am suggesting we
implement here), or allowing an UPDATE to modify the TTL setting for a
single column within a single row or set of rows based on query semantics.
This is all about letting the underlying database engine manage auto-expiry
of data selectively.

If this functionality were delegated to application code, that represents a
fairly heavy lift for the application developer as they will then have to
implement date/timestamp checking code (and timers) within their
application or services. Most developers prefer to have the database manage
data expiry for them as it also has the side benefit of being more accurate
given that the timers for TTL are in-band of the database engine where the
data is stored and will start as soon as the UPDATE USING TTL <n> gets
applied. If you have an application that is more time-sensitive, and you
implement this capability in application or service code, you will most
likely run into time drift based on the latency between the application or
service code and the underlying database engine.

Hope this helps.

Sincerely,


Joshua A. Norrid
................................................
Mobile: 214-505-9383
E-Mail: joshua.norrid@gmail.com

**Comment by jeffreyscarpenter** [comment]
won't do
