### ISSUE TITLE
Swagger annotated methods should have unique names

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#403]
Due to how the Swagger library generates the swagger.yaml the method names are used as operationIds. Currently if you plug the generated yaml into a validator then you'll be met with errors like

```
Semantic error at paths./v2/schemas/keyspaces/{keyspaceName}/tables/{tableName}.get.operationId
Operations must have unique operationIds.
Jump to line 2203
```

The reason for this error being due to

```
operationId is always globally unique per swagger 2.0 specification. The id MUST be unique among all operations described in the API.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject
Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.
```

To avoid this issue we need to go through the restapi and authapi to make sure that method names are unique across versions. One way we can go about this would be with a suffix like `getOneTable()` for v1 and `getOneTableV2()` for v2. Since operationIds are not visible in the UI (aside from anchors in the URL) it not super critical what they look like but it would be nice to have them makes sense from a code maintainability standpoint.

**Comment by olim7t** [comment]
It looks like Swagger already has logic to add a counter if there are duplicates: https://github.com/swagger-api/swagger-core/blob/v1.6.2/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L1210-L1222

For some reason we don't hit that code, maybe it's a configuration issue.

**Comment by polandll** [comment]
How about `getOneTableV1()` and `getOneTable()` instead? Although @olim7t comment may make it moot.

**Comment by olim7t** [comment]
I couldn't figure this out. I'm going to switch to higher priority tickets, leaving my findings here in case anyone else wants to take a look.

This is how we configure Swagger in `restapi/**/Server.java`:

```java
BeanConfig beanConfig = new BeanConfig();
beanConfig.setSchemes(new String[] {"http"});
beanConfig.setBasePath("/");
ScannerFactory.setScanner(new DefaultJaxrsScanner());
```

The [Swagger docs](https://github.com/swagger-api/swagger-core/wiki/Swagger-Core-Jersey-2.X-Project-Setup-1.5#using-the-application-class) mention `BeanConfig`, but you're supposed to call `beanConfig.setScan()` at the end. There's no mention of `ScannerFactory`.

It looks like they're two different ways to configure Swagger: if I comment the first 3 lines, everything still works as expected. The scan is actually triggered the first time `ApiListingResource` (the thing that builds `swagger.json`) is invoked. The `Reader` class I mentioned above is never invoked. Apparently the thing that's used instead does not deduplicate ids.

If I replace the last line by `beanConfig.setScan()`, the scan is triggered when the bundle starts. The `Reader` class is invoked, but it gets its input from `BeanConfig.classes()`, which for some reason does not detect any annotated resources. It might be a classloader issue, although I've not dug deep enough into the `reflections` library used by Swagger to be sure.

**Comment by tatu-at-datastax** [comment]
@olim7t Is this something we still consider valuable/necessary? When services are split, no longer part of a single Swagger API/Open API, name collisions should not occur across services?
Will close unless there's reason to keep open.

**Comment by ivansenic** [comment]
Pretty sure this is even solved in the newer versions of Swagger.. Could be relevant for the V1 maintenance maybe..

**Comment by tatu-at-datastax** [comment]
@ivansenic Makes sense. Will close for now: I don't think we are going to spend much time with V1 for general clean up; may be re-opened/re-filed if it is an actual issue that needs working but our backlog is so big we need to clean up unnecessary things.
