### ISSUE TITLE
Restapi only uses last clustering expression in list

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#406]
There's a problem with io.stargate.web.resources.Converters#getTableOptions where it only uses the last clustering expression in the list. So if there's only one then it fine but if there's more than one it breaks with 

```
org.apache.cassandra.stargate.exceptions.InvalidRequestException: Clustering key columns must exactly match columns in CLUSTERING ORDER BY directive
```

**Comment by eribeiro** [comment]
Is this still an issue? I didn't find the aforementioned method in the Converters class. Excuse me in advance if I missed something. :)

**Comment by eribeiro** [comment]
@dougwettlaufer Hi, sincere question: is this still an issue?

**Comment by dougwettlaufer** [comment]
Verified this is no longer an issue
