### ISSUE TITLE
Docs API not listed in build

### ISSUE THREAD

**Issue by githubjohnk3** [stargate/stargate#420]
![0DC90552-BF58-43BE-A24D-4794D85858FE](https://user-images.githubusercontent.com/21664341/99459272-d4fa2e00-28fb-11eb-819d-5b0de1ab1e49.jpg)

**Comment by EricBorczuk** [comment]
The Docs API is a part of `restapi` and is served alongside it (same port, different endpoints) - so they are listed as one entity in the build!

**Comment by dougwettlaufer** [comment]
Hi @githubjohnk3, thanks for reaching out. So the thing about docs api is that it's not a module but instead it lives inside of the restapi.

**Comment by dougwettlaufer** [comment]
Guess I wasn't fast enough @EricBorczuk  :)
