### ISSUE TITLE
Create utility web module

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#439]
This would be a plain JAR that factors elements common to all web modules:

* DropWizard dependencies
* the "no admin" server factory that's currently duplicated in a few modules: `GraphqlApiServerFactory`, `AuthApiServerFactory`, `RestApiServerFactory` (see [#429](https://github.com/stargate/stargate/pull/429#discussion_r530723538))
* create a utility to unify the creation of the Response with the `Error` entity so that status codes match in both, and thus fix all the places where `Error` is created without a status code.

**Comment by jeffreyscarpenter** [comment]
This is rendered moot by v2 architecture.
