### ISSUE TITLE
Stargate nodes have inconsistent view of their peers #github

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#45]
Stargate nodes that are using another stargate node as cluster seed don't have all the topology information from other Stargate nodes, which limits the number of nodes that will be used as coordinator, unless the right stargate node is used as contact point:
[file id="5e6a0524-2395-4315-b07e-1429f520af1d"]

**Comment by tatu-at-datastax** [comment]
Closing since a lot has changed since this was filed; may be refiled if there are remaining issues.
