### ISSUE TITLE
Load selected settings from a cassandra.yaml

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#48]
There are a number of C* features that do not work due to a mismatch in settings between Stargate and the backend. Several of these have been encountered when executing the cassandra-dtest suite via Stargate:

authentication (and an error should be thrown if C2 is started with--enable-authbut cassandra.yaml doesn't agree)

internode SSL

user-defined functions

partitioner

unlogged_batch_across_partitions_warn_threshold

more?

Not only will this config loading allow us to run more existing C* tests, it will also unblock OSS users who want to use Stargate with clusters that have some non-default settings.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1197965991209714/1198179293781399) by [Unito](https://www.unito.io/learn-more)

**Comment by jeromatron** [comment]
Is there any progress on this?  The ability to passthrough both client to node encryption and internode encryption is an important step for those wanting to use this in their production environments.

**Comment by dimas-b** [comment]
@jeromatron : #602 was merged. It allows using `cassandra.yaml` to as an "experimental" feature. As this point it should worth with OSS C*, but not with DSE.

Is inter-node SSL the main use case for cassandra.yaml settings at this point? If so, it might be worth filing a dedicated issue for that. It should be possible to support the required settings through our `ConfigStore`

**Comment by dimas-b** [comment]
I've created a dedicated issue for inter-node SSL: #642

**Comment by tatu-at-datastax** [comment]
Should probably be re-evaluated and limited to cover specific settings instead of "there are many potentially useful settings to pass through". Leaving open for now.

**Comment by tatu-at-datastax** [comment]
As per above, need to file more specific tasks, not general "load things".
