### ISSUE TITLE
Use 3-node cluster as test backend

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#51]
We need add integration tests against multiple C* and DSE nodes.

There are issues that are only likely to appear in a multi-node cluster: consistency; schema mismatches; ...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1197965991209714/1198119043605192) by [Unito](https://www.unito.io/learn-more)

**Comment by jeffreyscarpenter** [comment]
the integration test framework supports the capability to run multi-node clusters, and we have tests against multiple backends that now address these concerns.

**Comment by ivansenic** [comment]
@jeffreyscarpenter Are you sure that multiple nodes are actually started during tests? I saw that somewhere there is like number of nodes `1`, yea look here: https://github.com/stargate/stargate/blob/13ab4e1ddfb3a6b306cfde8e3d5bdcd42a8ee225/testing/pom.xml#L366
