### ISSUE TITLE
Unify date/time handling in GraphQL API and REST

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#532]
Stargate appears to have different parsing logic for date/time/timestamp in GraphQL and REST (GraphQL being more lenient).

Would it be possible to unify date/time parsing across all APIs that take input data as strings?

Background: https://discord.com/channels/745831180213158001/766324539063533569/787935337795551252 (and previous)

**Comment by olim7t** [comment]
The GraphQL code was adapted from the Java driver's `TimestampCodec`, which is itself derived from Cassandra's `TimestampSerializer`. It supports a number of different date-time patterns.

It would indeed be a good idea to factor that code and reuse it throughout the web APIs (the Document APIs is another potential candidate). We could either place that in the `core` module, or introduce a new one.
