### ISSUE TITLE
Reduce complexity of DocumentService.searchRows

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#537]
`DocumentService.searchRows` is flagged by Codacity as a very long method. In fact the method's body contains complex logic. It could be worth refactoring it to reduce complexity.

Side note: This issue came up in #531, which re-enables some Docs API unit tests. Still, the `searchRows` method is mocked by those tests, so in effect this method itself is not unit tested.

**Comment by ivansenic** [comment]
I think this ca be closed after #1136, the method is removed there.

**Comment by dimas-b** [comment]
Agreed. Closing :+1:
