### ISSUE TITLE
NPE is thrown if tableOptions are not specified in v1 create table

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#545]
Request is causing a 500 due to an NPE

```
curl -L -X POST 'http://localhost:8082/v1/keyspaces/ks1/tables' \
-H 'X-Cassandra-Token: TOKEN' \
-H 'Content-Type: application/json' \
--data-raw '{
    "name": "cyclist_name",
    "columnDefinitions": [
        {
            "name": "id",
            "typeDefinition": "uuid"
        },
        {
            "name": "lastname",
            "typeDefinition": "text"
        },
        {
            "name": "firstname",
            "typeDefinition": "text"
        }
    ],
    "primaryKey": {
        "partitionKey": [
            "id"
        ]
    }
}'
```

**Comment by eribeiro** [comment]
@dougwettlaufer I have submitted a candidate PR to solve this issue. On my manual tests I have been able to reproduce the error on v2 of the RestAPI too. It looks like the deserialisation from JSON to Java object is setting TableAdd's tableOptions to null. Another possible solution would be to check if `tableOptions` is different from null before setting it here: https://github.com/stargate/stargate/blob/e35ddb37feb0a656aa6491f26bd5cdad147f6626/restapi/src/main/java/io/stargate/web/models/TableAdd.java#L79-L81
