### ISSUE TITLE
Multiple cluster support

### ISSUE THREAD

**Issue by mthahir** [stargate/stargate#549]
It would be nice to have support for multiple cluster from a Stargate instance.

**Comment by dimas-b** [comment]
@mthahir : could you please provide some more details about the use cases you have in mind?

**Comment by mthahir** [comment]
This is what we discussed on Discord.  The ability to connect to multiple clusters from a Stargate so that they can use UNION/JOIN/INTERSECTION etc. Basically use Stargate as a federation layer.

**Comment by dimas-b** [comment]
How do you envision Stargate deployment for federated use cases? Is it meant to address on-prem users' needs (mostly)?

**Comment by dougwettlaufer** [comment]
But do you have an example use case in mind? Would this be a single role accessing multiple clusters? Would it be a gateway for multiple users to access multiple cluster or would they be associated with a single cluster?
