### ISSUE TITLE
Fix non-deterministic `BatchStatementTest` 

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#561]
I observe a non-deterministic behavior of the `BatchStatementTest`. This happens on multiple unrelated branches, for example:
https://console.cloud.google.com/cloud-build/builds/0c3d1162-b505-4316-b5be-e6cdf5847363?project=stargateio

```
Step #7 - "dse-6.8": [INFO] 
Step #7 - "dse-6.8": [INFO] Results:
Step #7 - "dse-6.8": [INFO] 
Step #7 - "dse-6.8": [ERROR] Errors: 
Step #7 - "dse-6.8": [ERROR]   BatchStatementTest.casTest:218 ? WriteTimeout Cassandra timeout during CAS wri...
Step #7 - "dse-6.8": [INFO] 
Step #7 - "dse-6.8": [ERROR] Tests run: 559, Failures: 0, Errors: 1, Skipped: 3
```

We should fix this test and make it more deterministic.

**Comment by jeffreyscarpenter** [comment]
can't repro
