### ISSUE TITLE
Feature Request - Support for Parquet files

### ISSUE THREAD

**Issue by osaeed-ds** [stargate/stargate#567]
Some enterprises would like to reduce their reliance on Hadoop by maintaining Parquet files, placing them in an object store, and then access the Parquet files through a common API interface for lightweight querying.  Stargate could serve as that API gateway.

The requested feature enhancement is to add Parquet as a supported query target into Stargate so that users can issue simple queries against the Parquet files (either being handled via Spark or some other mechanism)

**Comment by dougwettlaufer** [comment]
Would this be over CQL, GraphQL, and REST or just Spark with CQL?

I'm not very familiar with Parquet so please bare with me but would this be similar to [Apache Drill](https://drill.apache.org/)?

**Comment by osaeed-ds** [comment]
Yes, this would be similar to Apache Drill.  The Parquet files would live on an object store, eg S3 bucket.  Drill allows access to Parquet, so it could be running select queries on Parquet via Drill or Spark.

**Comment by prabhatjha** [comment]
@osaeed-ds  Nice idea. I have not used `Drill`. Does drill require temporarily downloading parquet files to local storage?
