### ISSUE TITLE
Support JSON logging output format for simpler log management

### ISSUE THREAD

**Issue by michael-baraboo-datastax** [stargate/stargate#575]
It would be convenient to have stargate log output in a native json format so logging stacks like ELK can ingest the data into queryable documents without writing custom parsing logic.

**Comment by olim7t** [comment]
Stargate uses SLF4J / logback, so in theory it should be possible to achieve this with configuration and a few additional JARs in the classpath (see [this](https://terrycho.home.blog/2019/03/05/structured-logging-slf4j-json/) for example).

However I can't find a way to add those JARs to an existing Stargate installation in a way that would make them visible to each OSGi bundle. I've tried adding them to the classpath of `stargate-starter` and declaring them as [system packages](https://spring.io/blog/2009/01/19/exposing-the-boot-classpath-in-osgi/), to no avail.

It would be nice if Stargate had some sort of "parent" lib directory for cases like this. We could also place the SLF4J and logback JARs there, to avoid including them in each and every bundle.
