### ISSUE TITLE
Add "CREATE TYPE" to REST API for creating UDTs

### ISSUE THREAD

**Issue by polandll** [stargate/stargate#579]
Currently, UDTs must be created in CQL, then can be queried in REST.

**Comment by eribeiro** [comment]
Copying and pasting @clun's description.

> To amend the schema definition with REST API, it would be required to create a UserDefinedType resource
> With the following URL:
> `/v2/schemas/keyspaces/{keyspaceName}/udts`
> With the following operations (update is not allowed on a UDT)
```
- getAllUdts()
- getOneUdt(String udtName)
- createUdt(UdtAdd u)
- deleteUdt(String udtName)
```

**Comment by clun** [comment]
Update for @dougwettlaufer it would be more relevant to use `types`in the resources URL and method names.

**Comment by dougwettlaufer** [comment]
Yeah, @clun and I were chatting about this and I suggest `/types` as its a little more generic and hopefully for those with less familiarity with Cassandra it's easier to easier to understand then `/udts`

**Comment by eribeiro** [comment]
I have just opened a PR to support UDT operations via REST. Following the discussion here I updated the endpoint to be /types. The PR is an early cut, so there will be some round of reviews, more test cases, design changes, bug fixes, etc. 

As of now, it's working as below:

`GET /v2/schemas/keyspaces/{keyspaceName}/types`  - get all UDTs
`GET /v2/schemas/keyspaces/{keyspaceName}/types/{typeName}` - get a given UDT
`POST /v2/schemas/keyspaces/{keyspaceName}/types/{typeName}` + JSON - creates an UDT
`DELETE /v2/schemas/keyspaces/{keyspaceName}/types/{typeName}` - delete an UDT

The info shown for each UDT when GETting is crappy, so I need more guidance on what to present in the JSON returned, besides other design opinions.

**Comment by polandll** [comment]
Any movement on this issue? I'm interested.

**Comment by dougwettlaufer** [comment]
@polandll there's a PR up here https://github.com/stargate/stargate/pull/799
