### ISSUE TITLE
Allow Multi Doc Insert for Create Collection

### ISSUE THREAD

**Issue by ds-steven-matison** [stargate/stargate#586]
I ran into a situation where I have a json array of 159 json documents and have to split and iterate each for Create Collection call.

It would be super awesome to be able to fire the json array (comma return separated) at the api and bulk create the documents. This is a small sample so would not expect to insert 10,000-50,000+ etc   but in a large streaming case i could see some big number user cases too if the actual json payload is a huge document.

Sample payload:

`{"type":"Event","name":"bill","login":"bill","avatar_url":"","email":"bill@bill.com"}`

Expected payload:

`{"type":"Event","name":"bill","login":"bill","avatar_url":"","email":"bill@bill.com"},
{"type":"Event","name":"sam","login":"sam","avatar_url":"","email":"sam@sam.com"},
{"type":"Event","name":"tom","login":"tom","avatar_url":"","email":"tom@tom.com"}`

**Comment by dougwettlaufer** [comment]
Pulling in @EricBorczuk's comment from the duplicate issue

> Upon supplying many documents to a special endpoint, we should be able to bulk-write to Cassandra
>
> Currently, one can only hit a "single write" endpoint and that makes things inexcusably slow for 100's of thousands of documents.
