### ISSUE TITLE
stargate support aws dynamodb http api 

### ISSUE THREAD

**Issue by mikulely** [stargate/stargate#597]
Cassandra with dynamodb api[1] support would be a killer feature. but
dynamo-cassandra-proxy[2] isn't been updated for 16
months. It seems that stargate can be a successor of dynamo-cassandra-proxy?

stargate with dynamodb api compatible should a good fit for slef-hosted dynamodb
service. Is there any plan to support dynamodb HTTP api?

1.  https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/Welcome.html
1. https://github.com/datastax/dynamo-cassandra-proxy

**Comment by pmcfadin** [comment]
I'm going to +1 this!

**Comment by dougwettlaufer** [comment]
Hi @mikulely thanks for bringing this up! It's definitely something we would like to get on our roadmap. Is this something you'd be interested in attempting? We'd love to collaborate on it.

**Comment by mikulely** [comment]
> Hi @mikulely thanks for bringing this up! It's definitely something we would like to get on our roadmap. Is this something you'd be interested in attempting? We'd love to collaborate on it.

Hi @dougwettlaufer  Cassandra with dynamodb API compatibility would make the adoption of AWS dynamodb users to Cassandra codebase much easier.

It seems that ScyllaDB had supported the dynamodb api (
https://www.scylladb.com/alternator/ ). It would be nice to comparison
Cassandra and ScyllaDB with AWS dynamodb api.

**Comment by hari2192** [comment]
+100

Any idea when this is coming through ?
