### ISSUE TITLE
Rest API: allow specifying client side CL

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#61]
At the time of this ticket the CL is hardcoded as LOCAL_QUORUM for the REST service.

Some use cases need a higher CL than LOCAL_QUORUM (LOCAL_SERIAL and SERIAL come to mind as common ones when paired with LWT). More advanced users maybe fine with LOCAL_ONE.

I suggest a default CL in the server config and a per request override option. The names don't have to be the existing CLs this is a good opportunity to have something like Dynamo or CosmosDB style consistency levels using the CosmosDB example herehttps://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels

STRONG == LOCAL_SERIAL

CONSISTENT == LOCAL_QUORUM

EVENTUAL == LOCAL_ONE

**Comment by jeromatron** [comment]
When it comes to working with Cassandra, how would different guarantees work then?  For instance LWT - is that just implicit in the call like "if exists" or "if val=3"?  I'm just wondering if these sorts of things are considered across all APIs.  I see it's listed specifically in the graphql doc, but didn't know if lwt (for example) works in the REST and the document APIs similarly.  https://docs.astra.datastax.com/docs/using-the-astra-graphql-api#generated-mutation-types

**Comment by dougwettlaufer** [comment]
LWTs are not currently supported in the restapi nor docsapi but please correct me if I'm wrong @EricBorczuk.

**Comment by clun** [comment]
Hi,

Regarding configuring Stargate when you build it you could edit the `application.conf` file 

As the consistency level is defined per request could we add an optional Header parameter `CONSISTENCY_LEVEL` (after all this is meta Data). 

> `The purpose of the HTTP APIs is to allow users to work with data and abstract away C*.` 

In my opinion, the Data portion of the API (RowResource) is really close to C* and this one is easy
