### ISSUE TITLE
Ability to set JSON schema on a collection, to be enforced on write

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#613]

**Comment by dougwettlaufer** [comment]
I'm still not sure I understand this one. If you have a defined schema then what's the benefit of using the docsapi over restapi?

**Comment by eribeiro** [comment]
IMHO, If you have a flat JSON then there's really not any aparent advantage of using docsapi over restapi, but you have a deeply nested JSON then it would be best to use the docsapi and still be able to enforce names and types of the JSON fields.

**Comment by dougwettlaufer** [comment]
Ah, yeah that's a good point.

**Comment by ivansenic** [comment]
Implemented in https://github.com/stargate/stargate/pull/994.
