### ISSUE TITLE
add http/2 support to the rest API

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#63]
According to the docs this looks supported out of the box in dropwizard and in the underlying jetty one can configure both http 1.1 and http/2 at the same time, so I'm assuming it's easy enough to do with drop wizard.

Look athttps://www.dropwizard.io/en/latest/manual/configuration.htmlunder HTTP/2 over TLSand HTTP/2 Plain Text.

Ideally we'd just turn on the correct mode depending on if SSL is enabled or not and always turn on HTTP/2 and HTTP 1.1 to accommodate the widest variety of clients.

**Comment by ivansenic** [comment]
Basically this is done in V2, all APIs use http/2 by default now.
