### ISSUE TITLE
Inconsistent authentication error messages in REST API and DOC API

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#630]
We appear to have inconsistent auth error reporting in Doc API vs. REST v1, e.g.:
REST v1:

```
{"description":"Role unauthorized for operation: Invalid clientID or hash provided","code":401}
```

Doc API:

```
You are not permitted to perform this action. Did you authenticate?
```

**Comment by eribeiro** [comment]
Hi @dimas-b, would you mind if I pick up this issue? Looks like a good low hanging fruit to foster more knowlegde about SG codebase. 🙂

**Comment by dougwettlaufer** [comment]
Go for it @eribeiro 👍

**Comment by dimas-b** [comment]
Go ahead and thanks! :+1:
