### ISSUE TITLE
Validate CQL access to storage nodes during readiness check

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#631]
Currently the readiness check validates only that Stargate itself is able to produce rows for the `system.local` virtual table. 

As [discussed](https://github.com/stargate/stargate/pull/626#discussion_r567959146) in #626 this check does not actually fetch any data from storage nodes.

It may be worth enhancing the DataStore check to actually communicate with storage nodes. Granted this will add some extra overhead, but it should not be huge assuming the health check is not too frequent.

**Comment by dougwettlaufer** [comment]
You're thinking something like a health_check table that we can insert a record and then get it back?

**Comment by dimas-b** [comment]
I was hoping to select from a standard table, but have not actually figured that one out yet.
