### ISSUE TITLE
Include schema agreement into the liveness check

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#636]
Stargate nodes act as fat clients from the perspective of storage nodes. This naturally requires Stargate to sync schema on every restart.

In resource-constrained environments there is a probability for schema pull requests to time out.

If Stargate ndoe is not able to sync schema for a prolonged period of time, its usability is greatly affected. Therefore, this issue proposed to include schema agreement in the `/liveness` checks.

If Stargate is not able to sync schema and its local schema version is not changing over time, it should fail [liveness](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) checks so that the infrastructure layer can act on that information and, for example, force restart the SG node.

**Comment by adutra** [comment]
I'm curious, how forcing the Stargate pod to restart after a liveness check failure is supposed to fix the schema sync issue? 

In any case, we've been seeing increased startup times for Stargate in K8ssandra due to this, and we were wondering if the liveness probe couldn't return UP faster, for a better user experience on k8s.

**Comment by adutra** [comment]
See https://github.com/k8ssandra/k8ssandra/issues/654 for reference.

**Comment by dimas-b** [comment]
> how forcing the Stargate pod to restart after a liveness check failure is supposed to fix the schema sync issue?

Stargate (and C* and/or DSE code that it uses) tries synching the schema with a finite retry limit. When it gives up and the schema is still not in agreement, it will never recover unless there's an external schema change. Since we cannot reasonably expect that to happen, the only option is to restart Stargate so as to resume the schema sync process.

We could resume the schema sync by making internal java method calls to C*/DSE code hypothetically, but it proves complicated in practice. Local schema information is stored, so restarting SG seems to be the most robust way to restart schema sync from "scratch".

Suggestion for how to do it differently are welcome :)

**Comment by adutra** [comment]
Thanks for the explanations, I now understand why restarting the pod has a good chance of solving the problem.

However, [as you said already in the K8ssandra issue](https://github.com/k8ssandra/k8ssandra/issues/654#issuecomment-834533549), you could maybe improve things a little by making the schema check return "OK" if it's still trying, and only return FAIL once Stargate gave up completely on schema agreement.
