### ISSUE TITLE
[FEAT] Website: Redirect to Code/Stargazers/Fork menu

### ISSUE THREAD

**Issue by Akshu-on-github** [stargate/stargate#646]
In the watch/stars/fork tabs in the website, shown below for clarity:

![image](https://user-images.githubusercontent.com/61582763/107121621-740a4280-68b9-11eb-9adb-46846ade0f10.png)

I'd suggest adding links to the code, list of stargazers, and/or the fork menu popup for easier access

**Comment by dougwettlaufer** [comment]
Hi @Akshu-on-github thanks for the suggestion and interest in the project. This issue would be a better fit for the [stargate/website](https://github.com/stargate/website/issues). Can you please reopen this issue there?

cc: @drewwitmer

**Comment by Akshu-on-github** [comment]
Ah, sure thing. There wasn't a CONTRIBUTING.md over there, so I wasn't sure if you wanted issues over there
