### ISSUE TITLE
Batch write endpoint for the documents API

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#655]
Upon supplying many documents to a special endpoint, we should be able to bulk-write to Cassandra

Currently, one can only hit a "single write" endpoint and that makes things inexcusably slow for 100's of thousands of documents.

**Comment by edwardoliveira** [comment]
Hi @EricBorczuk and @dougwettlaufer,

Isn't this issue a duplicate of https://github.com/stargate/stargate/issues/586 ?

**Comment by eribeiro** [comment]
Hi @EricBorczuk and @dougwettlaufer,

Isn't this issue a duplicate of #586 ?

**Comment by dougwettlaufer** [comment]
Closing as duplicate
