### ISSUE TITLE
Add a Stargate-aware status command

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#672]
Stargate supports `starctl ... --nodetool status` but other Stargate nodes do not show up in the output of that command because they are not part of the C* ring.

Perhaps we could add a Stargate-aware status command to list SG nodes and storage nodes at the same time to simplify trouble-shooting.

**Comment by dougwettlaufer** [comment]
As in intercepting the nodetool response and appending more info or adding a completely custom status check?

**Comment by dimas-b** [comment]
Might be easier to implement it as a separate command based on raw gossip data. I do not this it has to match `nodetool status` output as long as we clearly mark storage nodes and stargate nodes.

People who need token information can still run the old `nodetool status` command.
