### ISSUE TITLE
Improve collection search performance

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#680]
Investigate ways to improve search performance, as it is extremely slow for larger collections

**Comment by davideicardi** [comment]
I'm new to stargate, sorry for stupid question: Can you explain better this issue?
Which kind of search is slow? What do you mean for "larger collections"?

**Comment by EricBorczuk** [comment]
Hey there @davideicardi - leaving this issue open was my mistake, as there have been multiple improvements since February to improve some of the performance issues we were seeing.

To summarize, the search is this one: [here](https://github.com/stargate/stargate/blob/master/restapi/src/main/java/io/stargate/web/docsapi/resources/DocumentResourceV2.java#L880)

Back in February, there were many inefficient queries that were pulling rows sequentially from C* and hammering disk, making searches over large tables (in the docs API world tables are called "collections", they are 1-1 conceptually) perform really slowly. This was resulting in searches over a table with ~1000000 rows to time out, but that has since been fixed.

I am going to close this issue, thanks for your question and feel free to ask more!
