### ISSUE TITLE
Minimal set of projects needed for REST API

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#691]
I would like to deploy the stargate REST API solution for a C* 3.11 cluster. I'm trying to discover the minimal set of jar files needed. Doing a build as follows gives me a set which seems to work in the limited testing I have done.
<pre><code>
./mvnw package -pl stargate-starter,restapi,persistence-cassandra-3.11,health-checker,auth-table-based-service,rate-limiting-global,auth-api -am
</code></pre>

Two questions:

1. Is this a reasonable thing to do?
1. Is the set of projects defined above the minimal set required?

**Comment by dougwettlaufer** [comment]
> 1. Is this a reasonable thing to do?

Yes, totally reasonable! Part of the reason why we used OSGI.

> 2. Is the set of projects defined above the minimal set required?

Depending on the auth you use yes that should be it. The `-am` flag for maven should grab the necessary dependencies. Another option is to download the zip file (or build all) and just delete the jars you don't want (i.e. graphql, cql, ...).

**Comment by john-gress** [comment]
@dougwettlaufer - thanks again for your help!
