### ISSUE TITLE
Inserting row with data not matching schema returns 500

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#718]
When inserting a row with REST v1 for a table with counters the following error was returned

```
ERROR [2021-02-26 17:11:31,349] io.stargate.web.resources.RequestHandler: Error when executing request
! java.lang.NullPointerException: null
! at io.stargate.web.resources.Converters.colToValue(Converters.java:183)
! at io.stargate.web.resources.RowResource.lambda$addRow$6(RowResource.java:429)
! at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
! at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
! at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
! at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
! at io.stargate.web.resources.RowResource.lambda$addRow$7(RowResource.java:433)
! at io.stargate.web.resources.RequestHandler.handle(RequestHandler.java:36)
! at io.stargate.web.resources.RowResource.addRow(RowResource.java:420)
```

**Comment by dougwettlaufer** [comment]
Need to confirm this is also fixed by https://github.com/stargate/stargate/pull/757

**Comment by eribeiro** [comment]
Ping 🙂

**Comment by dougwettlaufer** [comment]
Looks good. 

Was able to confirm with this table

<img width="1792" alt="Screen Shot 2021-04-19 at 5 12 06 PM" src="https://user-images.githubusercontent.com/45750136/115309891-85ca5a80-a132-11eb-9b94-03c865e9135a.png">


That the following bad requests returned a 400
<img width="1792" alt="Screen Shot 2021-04-19 at 5 12 35 PM" src="https://user-images.githubusercontent.com/45750136/115309940-967ad080-a132-11eb-920d-4c2fcf99ec6b.png">
<img width="1792" alt="Screen Shot 2021-04-19 at 5 12 43 PM" src="https://user-images.githubusercontent.com/45750136/115309948-9975c100-a132-11eb-81a6-ca6d6af5c591.png">

**Comment by eribeiro** [comment]
Awesome! Thanks @dougwettlaufer !!!!
