### ISSUE TITLE
exists only supports the value true

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#720]
I'm using the REST API to retrieve rows from the user table and attempting to use the "$exists":"true" operator, but I'm getting a 500 error code.

<pre><code>
$ curl -s -L -X GET 'http://localhost:8082/v2/keyspaces/users_keyspace/users?where=\{"firstname":\{"$exists":"true"\}\}' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json"
{"description":"Server error: `exists` only supports the value `true`","code":500}
</code></pre>

What is the correct way to use $exists?
When $exists is working is there a way to specify the maximum number of rows to return?

Thanks!

**Comment by EricBorczuk** [comment]
Hello! Try

`'http://localhost:8082/v2/keyspaces/users_keyspace/users?where=\{"firstname":\{"$exists":true\}\}'`

(note the missing double quotes around `true`)

the query parameter `pageSize` should do the trick for limiting the number of rows, e.g.

`'http://localhost:8082/v2/keyspaces/users_keyspace/users?where=\{"firstname":\{"$exists":true\}\}&pageSize=10'`

**Comment by john-gress** [comment]
Hi @EricBorczuk ,

Thanks for your help.

When I try using `true` without the double quotes, I get this:
<pre><code>
$ curl -i -s -L -X GET 'http://localhost:8082/v2/keyspaces/users_keyspace/users?where=\{"firstname":\{"$exists":true\}\}' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json"
HTTP/1.1 400 Bad Request
Date: Mon, 01 Mar 2021 16:08:53 GMT
Content-Type: application/json
Content-Length: 167

{"description":"Bad request: Invalid value provided for 'firstname': Java value true of type 'java.lang.Boolean' is not a valid value for CQL type varchar","code":400}
</code></pre>

**Comment by john-gress** [comment]
Here is a stack trace from the app:
<pre><code>
[01/Mar/2021:18:53:10 +0000] "GET /v2/keyspaces/users_keyspace/users?where={"firstname":{"$exists":true}} HTTP/1.1" 400 167 "-" "curl/7.29.0" 18
INFO  [2021-03-01 18:53:10,731] io.stargate.web.resources.RequestHandler: Bad request
! io.stargate.db.schema.Column$ValidationException: Wanted 'varchar' but got '' at location 'unknown'
! at io.stargate.db.schema.Column$ColumnType.validate(Column.java:170)
! at io.stargate.db.schema.Column.toCQLString(Column.java:86)
! ... 84 common frames omitted
! Causing: java.lang.IllegalArgumentException: Java value true of type 'java.lang.Boolean' is not a valid value for CQL type varchar
! at io.stargate.db.schema.Column.toCQLString(Column.java:90)
! at io.stargate.db.schema.Column.access$000(Column.java:54)
! at io.stargate.db.schema.Column$ColumnType.toCQLString(Column.java:188)
! at io.stargate.db.query.builder.QueryStringBuilder.valueToString(QueryStringBuilder.java:151)
! ... 81 common frames omitted
! Causing: java.lang.IllegalArgumentException: Invalid value provided for 'firstname': Java value true of type 'java.lang.Boolean' is not a valid value for CQL type varchar
! at io.stargate.db.query.builder.QueryStringBuilder.valueToString(QueryStringBuilder.java:154)
! at io.stargate.db.query.builder.QueryStringBuilder.append(QueryStringBuilder.java:142)
! at io.stargate.db.query.builder.QueryStringBuilder.append(QueryStringBuilder.java:104)
! at io.stargate.db.query.builder.BuiltCondition.addToBuilder(BuiltCondition.java:96)
! at io.stargate.db.query.builder.QueryBuilderImpl.lambda$selectQuery$27(QueryBuilderImpl.java:1421)
! at io.stargate.db.query.builder.QueryStringBuilder$ListBuilder.lambda$addAll$0(QueryStringBuilder.java:227)
! at io.stargate.db.query.builder.QueryStringBuilder$ListBuilder.addAllWithIdx(QueryStringBuilder.java:233)
! at io.stargate.db.query.builder.QueryStringBuilder$ListBuilder.addAll(QueryStringBuilder.java:227)
! at io.stargate.db.query.builder.QueryBuilderImpl.selectQuery(QueryBuilderImpl.java:1418)
! at io.stargate.db.query.builder.QueryBuilderImpl.build(QueryBuilderImpl.java:769)
! at io.stargate.db.query.builder.QueryBuilder$QueryBuilder__42.build(QueryBuilder.java:197)
! at io.stargate.web.resources.v2.RowsResource.getRows(RowsResource.java:584)
! at io.stargate.web.resources.v2.RowsResource.lambda$getRowWithWhere$0(RowsResource.java:170)
! at io.stargate.web.resources.RequestHandler.handle(RequestHandler.java:36)
! at io.stargate.web.resources.v2.RowsResource.getRowWithWhere(RowsResource.java:143)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:50)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
! at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:37)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at org.eclipse.jetty.server.Server.handle(Server.java:501)
! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
! at java.lang.Thread.run(Thread.java:748)
</code></pre>

**Comment by eribeiro** [comment]
The `$exists` is used by the DocsAPI, but as REST API is a layer on top of Cassandra, what is the semantics of its use?

I mean, we could say that it would be used as a way to filter out columns whose values are not `null` (ex: `SELECT * FROM table WHERE column IS NOT NULL`), but AFAIK C* doesn't support this kind of operation. 

Looking at the code, here https://github.com/stargate/stargate/blob/ca44dcde84afddd3a54efbc94a592996b2d9092b/restapi/src/main/java/io/stargate/web/service/FilterOp.java#L26 we see that it is mapped to the equality operator, so it will break if the column type is not a boolean (in the example above firstname is text). This works for DocsAPI because the JSON is shredded and checking if a property exists is done via equality.

Does it make sense?

**Comment by dougwettlaufer** [comment]
By "exists" are you looking for rows where`firstname != null` or `firstname != ""`? Is firstname a partition key or clustering key because if it is I don't believe C* will allow a null value for either of those (please correct me if I'm wrong).

**Comment by john-gress** [comment]
@eribeiro, So "$exists" will work if the associated field is a boolean. Got it.

@dougwettlaufer, I was looking for a way to get selective rows from the table. Rows where `firstname != null`.

Thanks for your help.
