### ISSUE TITLE
REST API select * from table

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#727]
I'm looking for a REST API call to retrieve rows from a table where I do not know the value of the primary keys.

In cqlsh, I can do the following:
<pre><code>
SELECT * FROM users_keyspace.users ;
</code></pre>

Is there a way to do something similar through the REST API?

**Comment by dougwettlaufer** [comment]
Yes. In v1 you can leave off the primary key entirely and use `/v1/keyspaces/{keyspaceName}/tables/{tableName}/rows`.

**Comment by john-gress** [comment]
Thanks @dougwettlaufer !
That worked exceptionally well. And I see `&pageSize=20` will give me the first 20 rows.
Is there a way to get the last 20 rows from the table?

**Comment by dougwettlaufer** [comment]
> Is there a way to get the last 20 rows from the table?

No, sorry. If this is a frequent query pattern I believe creating your table with a descending clustering order should do the trick.

**Comment by john-gress** [comment]
That can work. Thanks!
