### ISSUE TITLE
Upgrade graphql-java from 14.2 to 16.2

### ISSUE THREAD

**Issue by tub** [stargate/stargate#736]
### Overview of the Issue
There some performance enhancements in 16.x that may be useful like [using immutable collections](https://github.com/graphql-java/graphql-java/pull/2086).

My main motivation, however, is the enhanced support for [persistent queries](https://github.com/graphql-java/graphql-java/pull/2013) which is something I'm experimenting with to provide some performance enhancements (only having to pass the sha256 of the query instead of the whole query) and possibly some security improvements (being able to supply an allow-list of graphql queries via the sha256 in some restricted environments).

I have a local branch working, but will perform some more testing & benchmarking before I put it up for review.

The full [changelog for graphql-java can be found here](https://github.com/graphql-java/graphql-java/releases).

**Comment by dougwettlaufer** [comment]
Hi @tub, aren't we currently on 16.1?
https://github.com/stargate/stargate/blob/master/graphqlapi/pom.xml#L44-L48

**Comment by tub** [comment]
> Hi @tub, aren't we currently on 16.1?
> https://github.com/stargate/stargate/blob/master/graphqlapi/pom.xml#L44-L48

urgh, don't tell me I just did all that because I forgot to pull master :doh:
