### ISSUE TITLE
Add additional system properties to support other keyspace settings for tablebased token keyspace

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#739]
Need to add two new system properties so that the table based token keyspace can be created with replication strategies other than simple. One property will be a list of DC names while the other will be RF. From these we can then build a NetworkTopologyStrategy if desired.

**Comment by dougwettlaufer** [comment]
SimpleStrategy is the ideal default for someone that's getting started with Stargate. Although I do agree that it's not the ideal setting for a production use case which is why we have https://github.com/stargate/stargate/issues/801 to log warnings about such settings to help avoid potential issues.

**Comment by jsanda** [comment]
In k8ssandra, we want to have the operator configure the replication since it knows the desired cluster topology before deploying Stargate. Is it possible to tell Stargate to altogether skip creating the auth keyspace?

**Comment by adutra** [comment]
> In k8ssandra, we want to have the operator configure the replication since it knows the desired cluster topology before deploying Stargate. Is it possible to tell Stargate to altogether skip creating the auth keyspace?

The keyspace is already being created with `IF NOT EXISTS` so I guess that's already the current Stargate behavior.

**Comment by dougwettlaufer** [comment]
> Is it possible to tell Stargate to altogether skip creating the auth keyspace?

Yep, just set `-Dstargate.auth_tablebased_init=false`
