### ISSUE TITLE
Add a way to insert multiple objects at once

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#743]
Currently the only way to add multiple objects in one network call is to have separate mutations:

```graphql
mutation insert2Books {
  moby: insertbook(value: {title:"Moby Dick", author:"Herman Melville"}) {
    value {
      title
    }
  }
  catch22: insertbook(value: {title:"Catch-22", author:"Joseph Heller"}) {
    value {
      title
    }
  }
}
```

This doesn't scale well to N > 2: it's verbose and repetitive, aliasing each mutation and parsing the results is cumbersome, etc.

It would be more convenient to have an insert alternative that takes a list of inputs, and returns a list. If any of the inserts fails, then the corresponding entry in the result list will be `null`, and the response will also include an error.

**Comment by olim7t** [comment]
As usual we'll have to be careful with naming: `insertbooks` would be the best choice, but it can clash if there are both `book` and `books` tables. It's easier to stick to a prefix, so maybe `bulkinsertbook`.

**Comment by tomekl007** [comment]
@olim7t to be clear, we want to support both solutions, right?

**Comment by olim7t** [comment]
Actually this ticket is for the CQL-first API (although it would make sense to also support something like this for GraphQL-first, I'll create a follow-up ticket).

> Do we want to execute all those in a single batch query?

Not by default, but we could support it if the mutation is annotated with `@atomic`.

**Comment by tomekl007** [comment]
Ok, I will push my progress for graphql-first on the separate branch and work on the cql-first now (I can get back to `graphql-first`) later. 
I think that we should have separate GitHub labels for both APIs, wdyt?
