### ISSUE TITLE
Generate an auth token

### ISSUE THREAD

**Issue by sicute** [stargate/stargate#746]
i have been deploy startgate node with current cassandra server 3.x.
i get problem when generate auth token without user cassandra (error 400).
if i generate auth token using user cassandra was working fine. 
My cassandra was disable login for user cassandra and split with 2 user ( 1 superuzer , 1 regular user)  .
I try both still failed.
any miss step was missing and clue ? 
Thanks

**Comment by sicute** [comment]
Yes respond was 400
and here  result 
[developer@ip-xxxx ~]$ curl -L -X POST 'http://localhost:8081/v1/auth' \
>   -H 'Content-Type: application/json' \
>   --data-raw '{
>     "username": “uzer_test”,
>     "password": “xxx”
> }'
{"code":400,"message":"Unable to process JSON"}[developer@ip-xx-xx1-xx-xx ~]$

127.0.0.1 - - [10/Mar/2021:03:43:45 +0000] "POST /v1/auth HTTP/1.1" 400 47 "-" "curl/7.61.1" 4

And here was using cassandra user : 
[developer@ip-xxxxx ~]$ curl -v -L -X POST 'http://localhost:8081/v1/auth' \
>   -H 'Content-Type: application/json' \
>   --data-raw '{
>     "username": "cassandra",
>     "password": "xxxx"
> }'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
> POST /v1/auth HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 68
>
* upload completely sent off: 68 out of 68 bytes
< HTTP/1.1 201 Created
< Date: Wed, 10 Mar 2021 03:46:08 GMT
< Content-Type: application/json
< Content-Length: 52
<
* Connection #0 to host localhost left intact
{"authToken":"fa234524-96bd-4445-a13b-ea2dfca8dfa0"}[developer@ip-xxx ~]$

and here log in console 
27.0.0.1 - - [10/Mar/2021:03:45:57 +0000] "GET / HTTP/1.0" 200 10 "-" "ELB-HealthChecker/2.0" 3
WARN  [Native-Transport-Requests-1] 2021-03-10 11:46:09,184 FBUtilities.java:334 - Trigger directory doesn't exist, please create it and try again.
127.0.0.1 - - [10/Mar/2021:03:46:09 +0000] "POST /v1/auth HTTP/1.1" 201 52 "-" "curl/7.61.1" 238
127.0.0.1 - - [10/Mar/2021:03:46:27 +0000] "GET / HTTP/1.0" 200 10 "-" "ELB-HealthChecker/2.0" 1

**Comment by eribeiro** [comment]
Hi @sicute, 
```
"username": “uzer_test”,
```
My two cents: the quotes around `uzer_test` are not the same as the quotes (the right ones) around username, so the error (`"Unable to process JSON"`) is correct for this particular snippet.

**Comment by dougwettlaufer** [comment]
Any luck yet @sicute ?

**Comment by sicute** [comment]
After restart and change code was working now . 
Thanks sorry late respond
