### ISSUE TITLE
Publish integration tests as a normal jar with dependencies

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#774]
Currently the Stargate integration tests are published as a "fat" jar with all the dependencies embedded.

This is sometimes inconvenient for downstream projects as it effectively prevents intelligent dependency management for test code.

Integration tests should be published as a normal jar with dependencies declared in its Maven manifest.

This way, downstream projects can control dependencies using regular build-time dependency management mechanisms.

**Comment by jasonstack** [comment]
is there a way to walkaround io/netty from testing-1.0.13-all.jar?  I tried shaded-plugin but it didn't remove netty package

**Comment by dimas-b** [comment]
@jasonstack : I'm planning to convert this "fat" jar to normal jars with declared dependencies. Then, you should be able to upgrade or exclude dependencies in Maven. Will this help?

Sorry, it's taking long as I'm busy with some other work too :running_man:

**Comment by jasonstack** [comment]
I think I have found a workaround by repacking the uber jar with shade plugin to remove netty..

**Comment by dimas-b** [comment]
Nice :) Sorry for taking a long time on this. I got busy with other issues :man_shrugging:
