### ISSUE TITLE
Better status codes for table not exist/table already exists errors

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#775]
Currently, if you create a table with the same name as an existing table, a 500 is returned. In a similar vein, if you try to read from a table that doesn't exist, a 500 is returned.  These should both be 4XX errors; 400 for the former and 404 for the latter

**Comment by ivansenic** [comment]
@EricBorczuk I can quickly take this and create my first ever Stargate PR :)..

**Comment by mvandenbrink** [comment]
Hi @EricBorczuk and @ivansenic, it is better to use HTTP Error 409 (Conflict) if the table (resource) already exists, see [RFC 7231](https://tools.ietf.org/html/rfc7231#page-60). HTTP Error 400 is used for a malformed or invalid request. For a non existent table there are 2 options, use the HTTP Error 404 (Not Found) or the HTTP Error 410 (Gone). Both are acceptable choices to use as HTTP error when a table doesn't exists (anymore). Keep in mind that HTTP Error 404 can also indicate that there is mistake in the URI Path. If HTTP Error 404 is used, it is recommended to response with an error body message that the client should check before the conclusion will be made that the table or document don't exists.

**Comment by dougwettlaufer** [comment]
+1 for returning `409` on name exists and 404 when table is missing.

**Comment by ivansenic** [comment]
OK, I am taking this, thanks for the input.
