### ISSUE TITLE
Add new options for selecting persistence module to load

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#780]
Breaking up https://github.com/stargate/stargate/issues/768 one of the tasks is to add new options for selecting which persistence module to use. For backwards compatibility we don't want to break the current method of `--dse` flag with `--cluster-version` but we also want to add another option.

I see at leaset two ways we can go about this. One is to add two new flags `--type` and change `--cluster-version` to not require a number. In this case `--type` would be DSE, Cassandra, ... and `--cluster-version` would remain like it is today. We could then use these two flags to decide which jar to load. The other way is to add another flag like `--persistence` or `--backend` which will have a value matching the second half of the jar name. For our current persistence modules the possible values would be `persistence-cassandra-3.11`, `persistence-cassandra-4.0`, and `persistence-dse-6.8`.

Going with the second option would mean only one flag would be required on startup but the first option could be easier in terms of what value to provide the flag by avoiding issues with dashes and such.

**Comment by jeffreyscarpenter** [comment]
this has been addressed in v2.1
