### ISSUE TITLE
Restarting stargate immediately results in startup failure

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#782]
If I stop stargate and immediately restart it, stargate fails to start with a -1 error code.

If I wait 10 - 30 seconds between stopping stargate and restarting, it starts up successfully.

Is there a consistent/safe amount of time to wait between stopping and restarting stargate?

**Comment by dougwettlaufer** [comment]
@mpenick I _think_ you looked into this one before (or maybe @dimas-b?). If I remember correctly this came down to how long it took for the other nodes in the cluster to "forget" about your stargate node. This is a related issue https://github.com/stargate/stargate/issues/587.

**Comment by dimas-b** [comment]
This looks like the same problem as in #587.

By default storage nodes will expire old data about Stargate 30 sec after disconnection.

**Comment by john-gress** [comment]
Thanks for the info, and as always thanks for your quick response!
