### ISSUE TITLE
UserDefinedType Resource in the schema RestApi

### ISSUE THREAD

**Issue by clun** [stargate/stargate#790]
To amend the schema definition with REST API,  it would be required to create a `UserDefinedType` resource

With the following URL: 

```
/v2/schemas/keyspaces/{keyspaceName}/udts
```

With the following operations (update is not allowed on a UDT)

```
- getAllUdts()
- getOneUdt(String udtName)
- createUdt(UdtAdd u)
- deleteUdt(String udtName)
```

**Comment by eribeiro** [comment]
This issue is a duplicate of https://github.com/stargate/stargate/issues/579
