### ISSUE TITLE
Configuration options around auth

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#792]
For some use cases auth is being handled completely out of band from Stargate thus making the available auth related modules a burden. We need to add a new config option that will do the following

1. Disable auth-api module
1. Not create auth related keyspace/table
1. NOOP authn/z related calls in all other modules
1. As possible, remove auth related dependencies in other modules

Aside from disabling the auth-api module, one way to accomplish the other items would be to add a new `auth-noop-service` that satisfies the authentication interfaces but is a NOOP for every call since the expectation is that the requests have already been authenticated and authorized.

**Comment by dougwettlaufer** [comment]
@marksurnin is there anything I missed from our discussion earlier?

**Comment by marksurnin** [comment]
@dougwettlaufer that sounds good, thanks! Yes, we went with a NoopAuthnTableBasedService that extends AuthnTableBasedService.

**Comment by caniko** [comment]
What is the connection between this issue, and the `auth` field under `StarfieldSpex` on K8ssandra ([docs link](https://docs-v2.k8ssandra.io/reference/crd/stargate/))?
