### ISSUE TITLE
JVM OnOutOfMemoryError configuration warning on startup

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#793]
When I start stargate, I'm seeing the following warning:

<pre><code>
2021-03-22 13:44:14,231 [main] WARN  o.a.cassandra.service.StartupChecks - The JVM is not configured to stop on OutOfMemoryError which can cause data corruption. Use one of the following JVM options to configure the behavior on OutOfMemoryError:  -XX:+ExitOnOutOfMemoryError, -XX:+CrashOnOutOfMemoryError, or -XX:OnOutOfMemoryError="<cmd args>;<cmd args>"
</code></pre>

I've checked the conf/cassandra-env.sh file and it has this setting:
`JVM_ON_OUT_OF_MEMORY_ERROR_OPT="-XX:OnOutOfMemoryError=kill -9 %p"`

Any ideas why I'm seeing this warning when starting stargate?

**Comment by dougwettlaufer** [comment]
Hi @john-gress , how are you starting stargate? The flag you reference will be specific to Cassandra itself so for stargate you'll need to use something like the following (heap setting are for example only, will require tuning)

```sh
JAVA_OPTS='-XX:+CrashOnOutOfMemoryError -Xmx1024M -Xms1024M ' ./starctl \
--cluster-name stargate --cluster-version 4.0 --simple-snitch --listen 127.0.0.2 \
--cluster-seed 127.0.0.1 --enable-auth
```

We plan to put out some docs related to this and other recommended java_opts for tuning and performance.

**Comment by john-gress** [comment]
This makes sense. We're not setting JAVA_OPTS when running starctl. We'll add that to our systemd unit file. Thanks!

**Comment by john-gress** [comment]
@dougwettlaufer - As mentioned above, were some docs created for tuning and performance?

**Comment by dougwettlaufer** [comment]
Nothing yet @john-gress but I've created https://github.com/stargate/docs/issues/114 so it doesn't get lost. If you have something specific I'd be happy to offer suggestions.

**Comment by john-gress** [comment]
Thanks @dougwettlaufer.

We're getting ready to deploy stargate into production and wanted to double-check our settings against any published recommendations. So far, stargate is running well with the settings we have, so I think we're good for now.
