### ISSUE TITLE
Persistence API does not surface all index properties

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#803]
A custom index can specify options as a `map<text,text>`:

```
CREATE CUSTOM INDEX fn_contains ON cyclist_name (firstname) USING 'org.apache.cassandra.index.sasi.SASIIndex'
WITH OPTIONS = { 'mode': 'CONTAINS' };
```

`QueryBuilderImpl` allows a custom class, but has no method to provide options:

```java
dataStore
    .queryBuilder()
    .create()
    .custom("org.apache.cassandra.index.sasi.SASIIndex")
    .index("fn_contains")
    .on("ks", "cyclist_name")
    .column("firstname")
    .???
```

`SecondaryIndex` has a property to indicate whether an index is custom, but there's no way to retrieve the class nor the options.

**Comment by eribeiro** [comment]
Hi @olim7t, I have written a __preliminary__ PR, but I have a couple of questions:

1) I tried to write an `BuiltIndexTest` and change `PersistenceTest` to add additional parameters, but it seems like they either don't run or fail to run;

2) QueryBuilder's options after column looks strange. Maybe we could rearrange to something like below?
```
dataStore
    .queryBuilder()
    .create()
    .index("fn_contains")
    .on("ks", "cyclist_name")
    .column("firstname")
    .custom("org.apache.cassandra.index.sasi.SASIIndex")
    .options(optionMap)
```

3) When writing this PR I found an error on C* 4.0's `IndexMetadata#appendCqlTo`, but it was fixed early this month: https://issues.apache.org/jira/browse/CASSANDRA-16482 (I don't think it impacts those tests but I am not sure).
