### ISSUE TITLE
DocumentResourceV2 should return 404 (not found) and not 204 (no content) in few cases

### ISSUE THREAD

**Issue by clun** [stargate/stargate#804]
On most of the methods in the class `DocumentResourceV2` we are working with a document id.

An http code 404 maybe be returned if the underlying document does not exist instead of 204.

* get a Document (getDoc)
* getDocPath
* deleteDoc()
* deleteDocPath()

Specially for delete, 204 is the status code for success. so 204 is both code for sucess and not found as of today

**Comment by dougwettlaufer** [comment]
@EricBorczuk a 404 vs a 204 requires a read before write. Correct? What are your thoughts on this?

Per the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.7) I can see how the case could be made for 204 being valid for everything

> or 204 (No Content) if the action has been enacted but the response does not include an entity.

**Comment by jeffreyscarpenter** [comment]
Won't fix.
