### ISSUE TITLE
Figure out how to deploy protobuf files for gRPC services

### ISSUE THREAD

**Issue by mpenick** [stargate/stargate#818]
Here are a couple resources with ideas (from SO):

https://medium.com/namely-labs/how-we-build-grpc-services-at-namely-52a3ae9e7c35
https://www.bugsnag.com/blog/libraries-for-grpc-services

I've created a new repo where Stargate protobuf files will live:

https://github.com/stargate/stargate-grpc-proto

There seem like there are two approaches that we can take:
1) We build libraries for different languages in the `stargate-grpc-proto` repo and distribute those artifacts. Our official clients (`stargate-grpc-go-client`, `stargate-grpc-java-client`) would pull those artifacts. We could add more languages as the community requests them.
2) The official and community clients build the proto libraries by using a subtree/submodule (or downloading) the protobuf files from the repo.

Note: We could also do a hybrid model where we build artifacts in the protobuf repo for official clients and community clients build the stubs themselves.

**Comment by jeffreyscarpenter** [comment]
Won't do. Proto files live in main stargate repo.
