### ISSUE TITLE
Update row using GQL with `ifExists: true` response needs updates when the row doesn't actually get inserted/upserted

### ISSUE THREAD

**Issue by msmygit** [stargate/stargate#843]
I've a table with below schema:

```
CREATE TABLE restkeyspace.cyclist_semi_pro (
    id int PRIMARY KEY,
    affiliation map<text, text>,
    age int,
    country text,
    firstname text,
    lastname text,
    registration date
);
```

It has below values to begin with:

```
token@cqlsh:restkeyspace> SELECT * FROM restkeyspace.cyclist_semi_pro ;

 id | affiliation            | age | country | firstname | lastname | registration
----+------------------------+-----+---------+-----------+----------+--------------
  2 | {'name': 'Rotar Club'} |  31 |     FRA |       Joe |    Maddy |   2020-07-22
  4 |                   null |  31 |     FRA |       Joe |     Dude |   2020-10-02
  3 |      {'Smart': 'Dude'} |  31 |     IND |        JJ |     JACK |   2020-07-22

(3 rows)
```

If I try to run a GraphQL API to update a row (which doesn't exist `id=1`) using the following (notice the usage of `ifExists: true`):

```
curl --location --request POST 'https://DBID-REGION.apps.astra.datastax.com/api/graphql/restkeyspace' \
--header 'x-cassandra-token: AstraCS:blah:blah' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"mutation cyclist_semi_pro {\n  update: updatecyclist_semi_pro(value: {id:1, firstname:\"Herman\"},ifExists: true ) { \n    value {\n      id\n      firstname\n    }\n  }\n}","variables":{}}'
```

I get an update/response that feels like it upserted the data into the table:

```
{
    "data": {
        "update": {
            "value": {
                "id": 1,
                "firstname": "Herman"
            }
        }
    }
}
```

When I query the table again, I don't see the row with `id = 1`:

```
token@cqlsh:restkeyspace> SELECT * FROM restkeyspace.cyclist_semi_pro ;

 id | affiliation            | age | country | firstname | lastname | registration
----+------------------------+-----+---------+-----------+----------+--------------
  2 | {'name': 'Rotar Club'} |  31 |     FRA |       Joe |    Maddy |   2020-07-22
  4 |                   null |  31 |     FRA |       Joe |     Dude |   2020-10-02
  3 |      {'Smart': 'Dude'} |  31 |     IND |        JJ |     JACK |   2020-07-22

(3 rows)
```

I would like to understand why? (or) if we need to modify the response to state it didn't actually insert/upsert that data into the table. FWIW, if I use ifExists: false, I see the row getting inserted which also has the same exact response structure. TIA!

> Olivier Michallat — Today at 11:02 AM
Yes, we need to change the response. The query works as expected (the row doesn't exist so it's not updated), but the response data simply mirrors the input data, which is wrong. We need to check the [applied]  field in the CQL response instead.

Discord reference: https://discord.com/channels/745831180213158001/766642967976476672/831536741093343232

**Comment by ivansenic** [comment]
@olim7t let me tackle this..

**Comment by ivansenic** [comment]
Furthermore the `applied` value returned is always `null`, no matter if the update was applied or not.
