### ISSUE TITLE
updateColumn should allow altering type

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#845]
In [updateColumn](https://github.com/stargate/stargate/blob/c664c8f02cb249140a66ca6d5a9695b1e126af90/restapi/src/main/java/io/stargate/web/resources/v2/schemas/ColumnsResource.java#L357) for both v1 and v2 we are only renaming the column and ignoring the typeDefinition provided. Instead you should be able to rename or change the type of the column

Reference:

* https://docs.datastax.com/en/cql-oss/3.3/cql/cql_using/useAlterColType.html

**Comment by tjake** [comment]
Changing types is dangerous and has been removed https://cassandra.apache.org/doc/latest/cql/changes.html#id2

**Comment by dougwettlaufer** [comment]
@tjake so is the doc I linked to outdated?

**Comment by tjake** [comment]
Yeah
