### ISSUE TITLE
Consistent logging

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#85]
In Stargate many modules import `logback-core`, which is probably not ideal. It make log operation obscure in runtime since logging is not controlled in one place.

Most modules should probably import only `slf4j`. Then, we could have a separate OSGi bundle that would contain an isolated set of jars implementing `slf4` and control logging in runtime.

Downstream project will have the option of providing their own log implementation bundles or simply overwrite the default `logback.xml` config.

**Comment by tatu-at-datastax** [comment]
Refactoring for Stargate V2 will require thinking through logging aspects (also due to move to Quarkus).
Closing as being tied to SGv1 design; will create new issue(s) as necessary.
