### ISSUE TITLE
Add ability to "push" to an array path in a document

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#854]
Similar to javascript's Array.proto.push(), add some functionality to be able to push a value onto an array path.  There are a few things to consider here:

1) The syntax/URL for such an action should be consistent with what exists already, i.e. you should still supply a document path in the URL
2) read-before-write should be avoided, or if it's absolutely necessary, the push functionality should be decoupled from other write operations
3) Needs to error out if a push is attempted on a non-array

**Comment by EricBorczuk** [comment]
This functionality is similar to Mongo's $push: https://docs.mongodb.com/manual/reference/operator/update/push/

**Comment by ranjitg2021** [comment]
Thank you for tracking this known limitation. I have a client that is currently able to perform a Push and Pop operation in Couchbase DB. They recently purchased DSE 6.8 from us and will be using Stargate for API access.

Given the ask, are there plans to include this in an upcoming release?

**Comment by EricBorczuk** [comment]
@ranjitg2021 I am going to be working on this next!
