### ISSUE TITLE
Consider defaulting to ScyllaDB over Cassandara

### ISSUE THREAD

**Issue by impredicative** [stargate/stargate#87]
[Scylla](https://github.com/scylladb/scylla) evidently offers significantly better performance, while also being a wide store. Please consider this independent benchmark as of 2020:

https://www.datasciencecentral.com/profiles/blogs/scylla-vs-cassandra-performance-comparison

Or is latency not important to this project? Why should users have to pay more to get the same performance?

**Comment by dougwettlaufer** [comment]
Hi @impredicative! Thanks for checking out our project! Stargate is built for pluggability, we have https://github.com/stargate/api-extensions for extending the outward facing APIs for interacting with your data and https://github.com/stargate/persistence-extensions for adding additional support for other storage systems. We always welcome PRs so if ScyllaDB is something you're interested in then feel free to add support to stargate/persistence-extensions. 

Thanks again for your interest!
