### ISSUE TITLE
Rest API should include count(*)/total record count for a given query 

### ISSUE THREAD

**Issue by rampalagummi** [stargate/stargate#870]
Having count(*) or total record count for a given query is useful in many ways to the applications, for example page count during pagination, etc..

**Comment by dimas-b** [comment]
Is the exact record count required in this case or an estimate?

**Comment by dimas-b** [comment]
Could this be merged with #823?

**Comment by dimas-b** [comment]
@rampalagummi : Please confirm that an estimate for the row count is acceptable for your use case(s). Thx!

I think we can provide that estimate based on the data that is already available to the coordinator code, so it should be efficient.

**Comment by rampalagummi** [comment]
Yes! row count estimation  is acceptable.
