### ISSUE TITLE
Add tracing support for the Stargate

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#883]
The Stargate project is currently missing a generic tracing support, which would provide more deeper insights on the performance of the incoming requests. Being an open-souce project we should be as flexible as possible, especially with respect to configuration. We should provide user a possibility to:

* Turn tracing on/off
* Define tracing properties like sampling rate, etc
* Define it's own back-end for the traces (being Zipkin, Jaerger or a custom one)
* Provide out-of-the box instrumentation for the services we provide

Considering that both OpenTracing and OpenCensus have been merged to [OpenTelemetry](https://opentelemetry.io/) project, we should consider the OpenTelemetry as the target implementation. Other ideas are welcome.

**Comment by ivansenic** [comment]
@tub Hi Toby, this might be interesting to you. Please share any requirements or insights you might have. Thanks :+1:

**Comment by tub** [comment]
We looked into this when we were first planning on adding tracing support. Wingtips looks like a nice abstraction layer if you wanted to be tracing framework agnostic: https://github.com/Nike-Inc/wingtips

**Comment by ivansenic** [comment]
Definitely on our V2 roadmap.
