### ISSUE TITLE
Unable to use "$in" with timestamp field

### ISSUE THREAD

**Issue by dougwettlaufer** [stargate/stargate#887]
Given a table with a timestamp column, this request currently fails

```sh
localhost:8082/v2/keyspaces/testks/foo?where={"id": {"$eq":"454674e1-571d-45bc-bd46-be6e9b6165ed"}, "created": {"$in": ["2021-04-21T18:42:22.139Z"]}}
```

The reason for this is that no matter what the array for the `IN` condition is being treated as an array of Strings. Instead we need to convert to an array of whatever the type is for that column.

**Comment by eribeiro** [comment]
Hi @dougwettlaufer, would you mind if I take this issue? I have been refactoring WhereParser recently. 🙂

**Comment by dougwettlaufer** [comment]
@eribeiro I already have a PR up. Not sure why it didn't link to the issue.

**Comment by eribeiro** [comment]
@dougwettlaufer GH automatically linked the issue because I referenced it, but my branch was still WIP and it was not my intention to link to this issue. **Sorry about that!** I am gonna delete my branch asap.

**Comment by dougwettlaufer** [comment]
No worries, thanks @eribeiro!
