### ISSUE TITLE
Logging every REST API call

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#896]
I'm running stargate as a systemd process and running into an issue with every REST API call being logged to /var/log/messages. I have configured the logback.xml to send output to a file, and I see logs in that file. Interestingly, all the logs seem to be coming from "starctl", which I believe has exited after starting the stargate java server.

In a production environment, I don't think it makes sense to log every REST API call, so the goal here would be to stop those logs from showing up in any output.

Any ideas?

==========================================================

Here's an example of a log message going to /var/log/messages and not going into the configured logback file:
<pre><code>
Apr 26 15:25:20 localhost starctl: 127.0.0.1 - - [26/Apr/2021:21:25:20 +0000] "POST /v2/keyspaces/DPI/Stats5S HTTP/1.1" 201 68 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_272)" 37
</code></pre>

Here's the contents of the logback.xml file:
        <?xml version="1.0" encoding="UTF-8"?>

```
    <!-- For Assistance related to logback-translator or configuration  -->
    <!-- files in general, please contact the logback user mailing list -->
    <!-- at http://www.qos.ch/mailman/listinfo/logback-user             -->
    <!--                                                                -->
    <!-- For professional support please see                            -->
    <!--    http://www.qos.ch/shop/products/professionalSupport         -->
    <!--                                                                -->
    <configuration>
       <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
          <!--See also http://logback.qos.ch/manual/appenders.html#RollingFileAppender-->
          <file>/var/log/probe/cassandra/stargate.log</file>
          <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
             <fileNamePattern>/var/log/probe/cassandra/stargate.%i.gz</fileNamePattern>
             <minIndex>1</minIndex>
             <maxIndex>3</maxIndex>
          </rollingPolicy>
          <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
             <maxFileSize>20MB</maxFileSize>
          </triggeringPolicy>
          <encoder>
             <pattern>%date [%thread] %-5level %logger{35} - %msg%n</pattern>
          </encoder>
       </appender>
       <root level="INFO">
          <appender-ref ref="FILE" />
       </root>
    </configuration>
```

**Comment by dougwettlaufer** [comment]
What stargate version are you currently running? This PR helped improve our access log config and was added in v1.0.18

https://github.com/stargate/stargate/pull/816

**Comment by john-gress** [comment]
We're using 1.0.15. I'll pull your latest and give it a try.

I'll close this for now.
