### ISSUE TITLE
Provide helper scripts / maven commands for building with local DSE jars

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#899]
Stargate contributors that are also DSE customers still have difficulties building and testing the DSE Persistence module locally.

The Stargate project could provide a script or a maven target to make required Maven artifacts from a _local_ DSE installation. The artifacts would be published to the _local_ Maven repository and should be usable for building DSE modules locally.

CI will continue to use existing (private) DSE artifacts.

**Comment by jeffreyscarpenter** [comment]
we have the equivalent of this
