### ISSUE TITLE
Pass all fetcher context via HttpAwareContext

### ISSUE THREAD

**Issue by olim7t** [stargate/stargate#945]
`CassandraFetcher` and all of its subclasses receive `authorizationService` and `dataStoreFactory` via the constructor. This generates a very tedious refactoring if we need to add a new argument or remove an old one (there is no automated way to change all the constructors at once AFAICT).

Such context components should be passed via `HttpAwareContext` instead.

Incidentally, we should rename that class, it already handles more than HTTP-related stuff. `CassandraFetcherContext` feels appropriate.

**Comment by ivansenic** [comment]
@olim7t you can change all consturctors with refactoring in Intellij, right click on constructor `Refactor -> Change signature`. If you do it in a base class, it will be applied to all sub-classes as well.

**Comment by olim7t** [comment]
I think I tried that, are you sure it applies to constructors as well?

But anyway, beyond "refactorability" I still think using the context is the better option.
