### ISSUE TITLE
Query plan analysis for combined and-queries

### ISSUE THREAD

**Issue by Geertex** [stargate/stargate#973]
When combining different and-clauses there is a difference in complexity of the search depending on the size of the individual results of the and-clauses.
I.E. when querying for (A = '123' and B = '321') it could be that the separate clause (A = '123') has 1,000,000 results and (B = '321') has 10,000 results.
In that case it is less complex to first resolve (B = '321'), which has a smaller amount of results, and then filter for (A = '123') among those 10,000 results.
This would require repeating analysis of the data to determine the more efficiënt approach.
It might also be needed to have user-input on the intesity and interval on which this analysis is done and perhaps specify the relevant fields for such an analysis.

**Comment by dimas-b** [comment]
@Geertex : Could you have a look at the example in the top-level comment on ##980? Does it look helpful for you? Thx!

**Comment by Geertex** [comment]
@dimas-b I took me a while to answer, sorry for that.
When also looking at the example from ivansenic I noticed the rowcounts on the different queries.
If those are indeed the counts for the sub-queries for each and-clause then those counts would centainly be helpfull to optimize combined and-queries.
Great stuff and I am looking forward to the next docker-image to test it!

**Comment by dimas-b** [comment]
Yes, row counts are what we actually fetch from the database.

`executionCount` can also be thought of as "page count" because we make one storage request per result set page and by default storage pages as set to 1000 rows.

**Comment by ivansenic** [comment]
@Geertex In #981 we are doing quite an optimization on the query types and amounts. There are multiple optimization for the collection search. Thus, it would be meaningful to wait for that to be merged to master in order to do some detailed analysis, otherwise you might get results that would change in a week or two.
