### ISSUE TITLE
Inconsistencies in C* RequestFailureReason mapping for DSE

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#982]
Stargate has its own enum for "RequestFailureReason" - `org.apache.cassandra.stargate.exceptions.RequestFailureReason` that defines error codes for various failure reasons.

However, these codes differ between C* 3.11/ 4.0, Stargate and DSE.

Stargate handles C* OSS `RequestFailureReason` correctly, but may map DSE reasons _incorrectly_.

Cf. `persistence-dse-6.8/src/main/java/io/stargate/db/dse/impl/Conversion.java`

E.g. in DSE error code `2` means `INDEX_NOT_AVAILABLE` but in Stargate it means `TIMEOUT`. Also DSE has more error code than Stargate.

**Comment by FRosner** [comment]
Related: https://datastax.jira.com/browse/DB-1204
